### ISSUE TITLE
Run error

### ISSUE THREAD

**Issue by testAccountDeltas** [codeceptjs/CodeceptJS#1021]
#### What are you trying to achieve?

Run scripts

#### What do you get instead?

Could not include object I from module 'steps_file.js'
Cannot find module 'steps_file.js'

Error:
    at loadSupportObject (C:\Users\user\AppData\Roaming\npm\node_modules\codeceptjs\lib\container.js:203:11)
    at getSupportObject (C:\Users\user\AppData\Roaming\npm\node_modules\codeceptjs\lib\container.js:191:12)
    at createSupportObjects (C:\Users\user\AppData\Roaming\npm\node_modules\codeceptjs\lib\container.js:148:21)
    at Function.create (C:\Users\user\AppData\Roaming\npm\node_modules\codeceptjs\lib\container.js:33:25)
    at Codecept.init (C:\Users\user\AppData\Roaming\npm\node_modules\codeceptjs\lib\codecept.js:47:15)
    at Command.module.exports (C:\Users\user\AppData\Roaming\npm\node_modules\codeceptjs\lib\command\run.js:36:14)
    at Command.listener (C:\Users\user\AppData\Roaming\npm\node_modules\codeceptjs\node_modules\commander\index.js:315:8)
    at emitTwo (events.js:126:13)
    at Command.emit (events.js:214:7)
    at Command.parseArgs (C:\Users\user\AppData\Roaming\npm\node_modules\codeceptjs\node_modules\commander\index.js:651:12)

> Provide console output if related. Use `--verbose` mode for more details.

```bash
ОС Name:                      microsoft Windows 10 corporation
ОС Version:                        10.0.14393 Н/Д build 14393

C:\nodejs>node -v
v8.11.1

C:\nodejs>npm -v
5.6.0

C:\nodejs>npm install -g codeceptjs
C:\Users\user\AppData\Roaming\npm\codeceptjs -> C:\Users\user\AppData\Roaming\npm\node_modules\codeceptjs\bin\codecept.js
+ codeceptjs@1.1.7
updated 1 package in 6.727s

C:\nodejs>npm install -g webdriverio
C:\Users\user\AppData\Roaming\npm\wdio -> C:\Users\user\AppData\Roaming\npm\node_modules\webdriverio\bin\wdio
+ webdriverio@4.12.0
updated 1 package in 13.647s

C:\nodejs>npm install -g nightmare
+ nightmare@3.0.1
updated 1 package in 14.597s

C:\nodejs>codeceptjs init

  Welcome to CodeceptJS initialization tool
  It will prepare and configure a test environment for you

Installing to C:\nodejs
? Where are your tests located? Scripts
? What helpers do you want to use?
? Where should logs, screenshots, and reports to be stored? logs
? Would you like to extend I object with custom steps? Yes
? Do you want to choose localization for tests? ru-RU
? Where would you like to place custom steps? steps_file.js
Adding default test mask: Scripts/*_test.js
Steps file created at C:\nodejs\steps_file.js
Config created at C:\nodejs\codecept.json
Directory for temporary output files created at `_output`
Almost done! Create your first test by executing `codeceptjs gt` (generate test) command

C:\nodejs>codeceptjs generate:test
Creating a new test...
----------------------
? Filename of a test TestScriptMy
? Feature which is being tested Sempe Scrit run
Test for TestScriptMy was created in C:\nodejs\Scripts\TestScriptMy_test.js

C:\nodejs>codeceptjs run --steps

Could not include object I from module 'steps_file.js'
Cannot find module 'steps_file.js'

Error:
    at loadSupportObject (C:\Users\user\AppData\Roaming\npm\node_modules\codeceptjs\lib\container.js:203:11)
    at getSupportObject (C:\Users\user\AppData\Roaming\npm\node_modules\codeceptjs\lib\container.js:191:12)
    at createSupportObjects (C:\Users\user\AppData\Roaming\npm\node_modules\codeceptjs\lib\container.js:148:21)
    at Function.create (C:\Users\user\AppData\Roaming\npm\node_modules\codeceptjs\lib\container.js:33:25)
    at Codecept.init (C:\Users\user\AppData\Roaming\npm\node_modules\codeceptjs\lib\codecept.js:47:15)
    at Command.module.exports (C:\Users\user\AppData\Roaming\npm\node_modules\codeceptjs\lib\command\run.js:36:14)
    at Command.listener (C:\Users\user\AppData\Roaming\npm\node_modules\codeceptjs\node_modules\commander\index.js:315:8)
    at emitTwo (events.js:126:13)
    at Command.emit (events.js:214:7)
    at Command.parseArgs (C:\Users\user\AppData\Roaming\npm\node_modules\codeceptjs\node_modules\commander\index.js:651:12)

```

### Details

* CodeceptJS version: new
* NodeJS Version: v8.11.1
* Operating System: win 10
* Protractor || WebDriverIO || Nightmare version (if related) 
* Configuration file: new

```js
{
  "tests": "Scripts/*_test.js",
  "timeout": 10000,
  "output": "logs",
  "helpers": {},
  "include": {
    "I": "steps_file.js"
  },
  "bootstrap": false,
  "mocha": {},
  "name": "nodejs",
  "translation": "ru-RU"
}
```

**Comment by Rhymond** [comment]
You need to use `space` key while selecting helpers
