### ISSUE TITLE
[WebdriverIO] .waitForInvisible fails due to "stale element reference" error

### ISSUE THREAD

**Issue by JLRishe** [codeceptjs/CodeceptJS#1040]
I have a particular part of one of my tests that fails about 1 out of every 10 attempts on a specific `waitForInvisible()` call, which fails even though the element has gone away with plenty of time to spare.

The relevant part of my test looks like this:

```js
const cellSelector = ".ms-List-cell"
const deleteButtonSelector = "div.CommandBar-mainArea div.CommandBarItem i.ms-Icon--Delete";

I.waitForVisible("div.StandaloneList-listView", 20);
I.click("div.ms-DetailsList div.ms-DetailsHeader div.ms-DetailsHeader-cell.ms-DetailsHeader-cellIsCheck");
I.waitForVisible(deleteButtonSelector, 20);
I.waitForInvisible('.od-LoadingSpinner');
I.click(deleteButtonSelector);
I.waitForVisible("div.od-StandardDialog", 20);
I.click("div.od-StandardDialog div.od-Dialog-inner div.od-Dialog-actionsRight button");

I.waitForInvisible(cellSelector, 40);      // <-- error occurs here
```

By looking at the console output from Selenium, it looks like Selenium is being continually polled for the indicated 40-second period, but every polling attempt after the first two or so fail due to a `stale element reference: element is not attached to the page document` exception (console output below).

Is there any way to avert this problem within CodeceptJS? I'm guessing it is due to some portion of the DOM being swapped out, but I am not running this code within a `within()` block and there are no obvious page navigation changes during the course of the `waitForInvisible()` command.

Selenium output:

```
Session ID: 8b8782be620d04530d182702f1a49e29
13:43:33.787 INFO - Executing: [is displayed: 10 [[ChromeDriver: chrome on XP (8b8782be620d04530d182702f1a49e29)] -> css selector: .ms-List-cell]])
13:43:34.154 INFO - Executing: [execute script: return (function () {
      return {
        height: document.body.scrollHeight,
        width: document.body.scrollWidth
      };
    }).apply(null, arguments), []])
13:43:34.439 WARN - Exception thrown
org.openqa.selenium.StaleElementReferenceException: stale element reference: element is not attached to the page document
  (Session info: chrome=66.0.3359.117)
  (Driver info: chromedriver=2.38.552522 (437e6fbedfa8762dec75e2c5b3ddb86763dc9dcb),platform=Windows NT 10.0.16299 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 11 milliseconds
For documentation on this error, please visit: http://seleniumhq.org/exceptions/stale_element_reference.html
Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
System info: host: '......', ip: '.....', os.name: 'Windows 10', os.arch: 'x86', os.version: '10.0', java.version: '1.8.0_161'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities [{applicationCacheEnabled=false, rotatable=false, mobileEmulationEnabled=false, networkConnectionEnabled=false, chrome={chromedriverVersion=2.38.552522 (437e6fbedfa8762dec75e2c5b3ddb86763dc9dcb), userDataDir=.......}, takesHeapSnapshot=true, pageLoadStrategy=normal, databaseEnabled=false, handlesAlerts=true, hasTouchScreen=false, version=66.0.3359.117, platform=XP, browserConnectionEnabled=false, nativeEvents=true, acceptSslCerts=false, acceptInsecureCerts=false, locationContextEnabled=true, webStorageEnabled=true, browserName=chrome, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true, setWindowRect=true, unexpectedAlertBehaviour=}]
Session ID: 8b8782be620d04530d182702f1a49e29
        at sun.reflect.GeneratedConstructorAccessor100.newInstance(Unknown Source)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
        at java.lang.reflect.Constructor.newInstance(Unknown Source)
        at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:215)
        at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:167)
        at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:671)
        at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:272)
        at org.openqa.selenium.remote.RemoteWebElement.isDisplayed(RemoteWebElement.java:313)
        at sun.reflect.GeneratedMethodAccessor12.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.openqa.selenium.support.events.EventFiringWebDriver$EventFiringWebElement$1.invoke(EventFiringWebDriver.java:332)
        at com.sun.proxy.$Proxy5.isDisplayed(Unknown Source)
        at org.openqa.selenium.support.events.EventFiringWebDriver$EventFiringWebElement.isDisplayed(EventFiringWebDriver.java:386)
        at sun.reflect.GeneratedMethodAccessor12.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.openqa.selenium.remote.server.KnownElements$1.invoke(KnownElements.java:64)
        at com.sun.proxy.$Proxy6.isDisplayed(Unknown Source)
        at org.openqa.selenium.remote.server.handler.GetElementDisplayed.call(GetElementDisplayed.java:32)
        at org.openqa.selenium.remote.server.handler.GetElementDisplayed.call(GetElementDisplayed.java:23)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at org.openqa.selenium.remote.server.DefaultSession$1.run(DefaultSession.java:176)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
13:43:34.440 WARN - Exception: stale element reference: element is not attached to the page document
  (Session info: chrome=66.0.3359.117)
  (Driver info: chromedriver=2.38.552522 (437e6fbedfa8762dec75e2c5b3ddb86763dc9dcb),platform=Windows NT 10.0.16299 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 11 milliseconds
For documentation on this error, please visit: http://seleniumhq.org/exceptions/stale_element_reference.html
Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
System info: host: '......', ip: '.......', os.name: 'Windows 10', os.arch: 'x86', os.version: '10.0', java.version: '1.8.0_161'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities [{applicationCacheEnabled=false, rotatable=false, mobileEmulationEnabled=false, networkConnectionEnabled=false, chrome={chromedriverVersion=2.38.552522 (437e6fbedfa8762dec75e2c5b3ddb86763dc9dcb), userDataDir=C:\Users\Jimmy\AppData\Local\Temp\scoped_dir20804_6552}, takesHeapSnapshot=true, pageLoadStrategy=normal, databaseEnabled=false, handlesAlerts=true, hasTouchScreen=false, version=66.0.3359.117, platform=XP, browserConnectionEnabled=false, nativeEvents=true, acceptSslCerts=false, acceptInsecureCerts=false, locationContextEnabled=true, webStorageEnabled=true, browserName=chrome, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true, setWindowRect=true, unexpectedAlertBehaviour=}]
```

**Comment by JLRishe** [comment]
After looking at the Selenium logs a little more closely, it looks like Selenium is receiving a repeated stream of `is displayed` queries, whereas normal execution of `waitForInvisible` causes an alternating stream of `find elements` and `is displayed`.

This would explain why the error is occurring repeatedly. The elements selected on this line:

```js
const res = await this.browser.elements(withStrictLocator.call(this, locator));
```

are being used in this line

```js
const selected = await forEachAsync(res.value, async el => this.browser.elementIdDisplayed(el.ELEMENT));
```

and if any of these elements are detached from the DOM are detached between the time the first and second lines execute, this error condition will occur.

The question is why the `is displayed` request is sent repeatedly. Does Webdriver have some kind of retry logic that repeatedly sends the same request to Selenium until it succeeds?

**Comment by lubosek** [comment]
Facing the same issue.

**Comment by lubosek** [comment]
I think that there's some issue with handling the "stale element exception" coming back from selenium. 
I have following scenario:

```
Walkthrough --
  Routing and navigation
   I am on page ""
   I grab text from "small"
v1.31.0 Jihlava - Build #702 cc390db0
   I grab current url
   I see element Login page headline
   I see element Username
   I see element Password
   I fill field Username, "xy"
   I fill field Partition, "xy"
   I fill field Password, "xy"
   I click Submit button
   I see element Logout
   I click Dashboards
   I grab number of visible elements "div.slds-spinner_container"
1
   I grab number of visible elements "div.slds-spinner_container"
```
The spinner is there on the page load and should disappear once the page is loaded but during the second call to 'I grab...' stale element reference error is returned and the test gets into infinite loop sending the same commands to selenium server and even no time out stops it from it.
