### ISSUE TITLE
TypeError: Cannot set property 'state' of undefined

### ISSUE THREAD

**Issue by NaLLiFFuNT** [codeceptjs/CodeceptJS#1051]
#### What are you trying to achieve?
I try to cover registration by test. Sometime i got this weird error.

````bash
12:17:00 node_1    |    Error processing test.passed event:
12:17:00 node_1    |    TypeError: Cannot convert undefined or null to object
12:17:00 node_1    |     at EventEmitter.event.dispatcher.on (/app/node_modules/codeceptjs/lib/listener/steps.js:50:5)
12:17:00 node_1    |     at EventEmitter.emit (events.js:185:15)
12:17:00 node_1    |     at EventEmitter.emit (domain.js:421:20)
12:17:00 node_1    |     at Object.emit (/app/node_modules/codeceptjs/lib/event.js:47:28)
12:17:00 node_1    |     at recorder.add (/app/node_modules/codeceptjs/lib/scenario.js:65:54)
12:17:00 node_1    |     at <anonymous>
12:17:00 node_1    |     at process._tickCallback (internal/process/next_tick.js:118:7)
12:17:00 node_1    |    [1] Error | TypeError: Cannot set property 'state' of undefined
````

#### What do you get instead?

> Provide console output if related. Use `--verbose` mode for more details.

```bash
12:15:13 chrome_1  | 09:15:13.515 INFO [GridLauncherV3.launch] - Selenium build info: version: '3.11.0', revision: 'e59cfb3'
12:15:13 chrome_1  | 09:15:13.516 INFO [GridLauncherV3$1.launch] - Launching a standalone Selenium Server on port 4444
12:15:13 chrome_1  | 2018-05-07 09:15:13.672:INFO::main: Logging initialized @650ms to org.seleniumhq.jetty9.util.log.StdErrLog
12:15:13 chrome_1  | 09:15:13.928 INFO [SeleniumServer.boot] - Welcome to Selenium for Workgroups....
12:15:13 chrome_1  | 09:15:13.929 INFO [SeleniumServer.boot] - Selenium Server is up and running on port 4444
12:15:14 node_1    | 
12:15:14 node_1    | > hygger-selenium-test@1.0.0 test /app
12:15:14 node_1    | > codeceptjs run --steps --verbose
12:15:14 node_1    | 
12:15:14 node_1    | creating output directory: /app/output
12:15:15 node_1    | CodeceptJS v1.1.7
12:15:15 node_1    | Using test root "/app"
12:15:15 node_1    | 
12:15:15 node_1    | landing is alive --
12:15:15 node_1    |    [1] Starting recording promises
12:15:15 node_1    |    Emitted | suite.before ([object Object])
12:15:15 node_1    |    [1] Queued | hook WebDriverIO._beforeSuite()
12:15:15 node_1    |    [1] Queued | hook Mailer._beforeSuite()
12:15:15 node_1    |  > [Session] Starting singleton browser session
12:15:15 chrome_1  | 09:15:15.496 INFO [ActiveSessionFactory.apply] - Capabilities are: Capabilities {browserName: chrome, handlesAlerts: true, javascriptEnabled: true, locationContextEnabled: true, loggingPrefs: org.openqa.selenium.logging..., requestOrigins: {name: webdriverio, url: http://webdriver.io, version: 4.12.0}, rotatable: true}
12:15:15 chrome_1  | 09:15:15.499 INFO [ActiveSessionFactory.lambda$apply$11] - Matched factory org.openqa.selenium.remote.server.ServicedSession$Factory (provider: org.openqa.selenium.chrome.ChromeDriverService)
12:15:15 chrome_1  | Starting ChromeDriver 2.37.544315 (730aa6a5fdba159ac9f4c1e8cbc59bf1b5ce12b7) on port 16438
12:15:15 chrome_1  | Only local connections are allowed.
12:15:16 chrome_1  | 09:15:16.494 INFO [ProtocolHandshake.createSession] - Detected dialect: OSS
12:15:17 chrome_1  | 09:15:17.122 INFO [RemoteSession$Factory.lambda$performHandshake$0] - Started new session fd17d9f3c3fd17299fba032c8679eeab (org.openqa.selenium.chrome.ChromeDriverService)
12:15:17 node_1    |  open landing
12:15:17 node_1    |    Emitted | test.before
12:15:17 node_1    |    [1] Queued | hook WebDriverIO._before()
12:15:17 node_1    |    [1] Queued | hook Mailer._before()
12:15:17 node_1    |    Emitted | test.start ([object Object])
12:15:17 node_1    |    Emitted | step.before (I am on page "https://example.com")
12:15:17 node_1    |    [1] Queued | hook WebDriverIO._beforeStep()
12:15:17 node_1    |    [1] Queued | hook Mailer._beforeStep()
12:15:17 node_1    |    [1] Queued | amOnPage: "https://example.com"
12:15:17 node_1    |    Emitted | step.after (I am on page "https://example.com")
12:15:17 node_1    |    [1] Queued | hook WebDriverIO._afterStep()
12:15:17 node_1    |    [1] Queued | hook Mailer._afterStep()
12:15:17 node_1    |    [1] Queued | step passed
12:15:17 node_1    |    [1] Queued | return result
12:15:17 node_1    |    Emitted | step.before (I see "Example")
12:15:17 node_1    |    [1] Queued | hook WebDriverIO._beforeStep()
12:15:17 node_1    |    [1] Queued | hook Mailer._beforeStep()
12:15:17 node_1    |    [1] Queued | see: "Example"
12:15:17 node_1    |    Emitted | step.after (I see "Example")
12:15:17 node_1    |    [1] Queued | hook WebDriverIO._afterStep()
12:15:17 node_1    |    [1] Queued | hook Mailer._afterStep()
12:15:17 node_1    |    [1] Queued | step passed
12:15:17 node_1    |    [1] Queued | return result
12:15:17 node_1    |    [1] Queued | fire test.passed
12:15:17 node_1    |    [1] Queued | finish test
12:15:17 node_1    |    Emitted | step.start (I am on page "https://example.com")
12:15:17 node_1    |  • I am on page "https://example.com"
12:15:20 node_1    |    Emitted | step.passed (I am on page "https://example.com")
12:15:20 node_1    |    Step finished in 3.044 sec
12:15:20 node_1    |    Emitted | step.start (I see "Example")
12:15:20 node_1    |  • I see "Example"
12:15:20 node_1    |  > [SmartWait (5000ms)] Locating body in 5000
12:15:20 node_1    |    Emitted | step.passed (I see "Example")
12:15:20 node_1    |    Step finished in 0.179 sec
12:15:20 node_1    |    Emitted | test.passed ([object Object])
12:15:20 node_1    |    [1] Queued | hook WebDriverIO._passed()
12:15:20 node_1    |    [1] Queued | hook Mailer._passed()
12:15:20 node_1    |  ✓ OK in 3237ms
12:15:20 node_1    | 
12:15:20 node_1    |    Emitted | test.after
12:15:20 node_1    |    [1] Queued | hook WebDriverIO._after()
12:15:20 node_1    |    [1] Queued | hook Mailer._after()
12:15:20 node_1    |  > [Session] cleaning cookies and localStorage
12:15:20 node_1    |    Emitted | suite.after ([object Object])
12:15:20 node_1    |    [1] Queued | hook WebDriverIO._afterSuite()
12:15:20 node_1    |    [1] Queued | hook Mailer._afterSuite()
12:15:20 node_1    | landing is alive --
12:15:20 node_1    |    Emitted | suite.before ([object Object])
12:15:20 node_1    |    [1] Queued | hook WebDriverIO._beforeSuite()
12:15:20 node_1    |    [1] Queued | hook Mailer._beforeSuite()
12:15:20 node_1    |  open landing
12:15:20 node_1    |    Emitted | test.before
12:15:20 node_1    |    [1] Queued | hook WebDriverIO._before()
12:15:20 node_1    |    [1] Queued | hook Mailer._before()
12:15:20 node_1    |    Emitted | test.start ([object Object])
12:15:20 node_1    |    Emitted | step.before (I am on page "https://example.com")
12:15:20 node_1    |    [1] Queued | hook WebDriverIO._beforeStep()
12:15:20 node_1    |    [1] Queued | hook Mailer._beforeStep()
12:15:20 node_1    |    [1] Queued | amOnPage: "https://example.com"
12:15:20 node_1    |    Emitted | step.after (I am on page "https://example.com")
12:15:20 node_1    |    [1] Queued | hook WebDriverIO._afterStep()
12:15:20 node_1    |    [1] Queued | hook Mailer._afterStep()
12:15:20 node_1    |    [1] Queued | step passed
12:15:20 node_1    |    [1] Queued | return result
12:15:20 node_1    |    Emitted | step.before (I see "Example")
12:15:20 node_1    |    [1] Queued | hook WebDriverIO._beforeStep()
12:15:20 node_1    |    [1] Queued | hook Mailer._beforeStep()
12:15:20 node_1    |    [1] Queued | see: "Example"
12:15:20 node_1    |    Emitted | step.after (I see "Example")
12:15:20 node_1    |    [1] Queued | hook WebDriverIO._afterStep()
12:15:20 node_1    |    [1] Queued | hook Mailer._afterStep()
12:15:20 node_1    |    [1] Queued | step passed
12:15:20 node_1    |    [1] Queued | return result
12:15:20 node_1    |    Emitted | step.before (I dont see "Please use your work email address to sign up")
12:15:20 node_1    |    [1] Queued | hook WebDriverIO._beforeStep()
12:15:20 node_1    |    [1] Queued | hook Mailer._beforeStep()
12:15:20 node_1    |    [1] Queued | dontSee: "Please use your work email address to sign up"
12:15:20 node_1    |    Emitted | step.after (I dont see "Please use your work email address to sign up")
12:15:20 node_1    |    [1] Queued | hook WebDriverIO._afterStep()
12:15:20 node_1    |    [1] Queued | hook Mailer._afterStep()
12:15:20 node_1    |    [1] Queued | step passed
12:15:20 node_1    |    [1] Queued | return result
12:15:20 node_1    |    Emitted | step.before (I click ".btn.show_join")
12:15:20 node_1    |    [1] Queued | hook WebDriverIO._beforeStep()
12:15:20 node_1    |    [1] Queued | hook Mailer._beforeStep()
12:15:20 node_1    |    [1] Queued | click: ".btn.show_join"
12:15:20 node_1    |    Emitted | step.after (I click ".btn.show_join")
12:15:20 node_1    |    [1] Queued | hook WebDriverIO._afterStep()
12:15:20 node_1    |    [1] Queued | hook Mailer._afterStep()
12:15:20 node_1    |    [1] Queued | step passed
12:15:20 node_1    |    [1] Queued | return result
12:15:20 node_1    |    Emitted | step.before (I see "Please use your work email address to sign up")
12:15:20 node_1    |    [1] Queued | hook WebDriverIO._beforeStep()
12:15:20 node_1    |    [1] Queued | hook Mailer._beforeStep()
12:15:20 node_1    |    [1] Queued | see: "Please use your work email address to sign up"
12:15:20 node_1    |    Emitted | step.after (I see "Please use your work email address to sign up")
12:15:20 node_1    |    [1] Queued | hook WebDriverIO._afterStep()
12:15:20 node_1    |    [1] Queued | hook Mailer._afterStep()
12:15:20 node_1    |    [1] Queued | step passed
12:15:20 node_1    |    [1] Queued | return result
12:15:20 node_1    |    Emitted | step.before (I fill field "input[type=email]", "rega1127.5af0191d@example.com")
12:15:20 node_1    |    [1] Queued | hook WebDriverIO._beforeStep()
12:15:20 node_1    |    [1] Queued | hook Mailer._beforeStep()
12:15:20 node_1    |    [1] Queued | fillField: "input[type=email]", "rega1127.5af0191d@example.com"
12:15:20 node_1    |    Emitted | step.after (I fill field "input[type=email]", "rega1127.5af0191d@example.com")
12:15:20 node_1    |    [1] Queued | hook WebDriverIO._afterStep()
12:15:20 node_1    |    [1] Queued | hook Mailer._afterStep()
12:15:20 node_1    |    [1] Queued | step passed
12:15:20 node_1    |    [1] Queued | return result
12:15:20 node_1    |    Emitted | step.before (I press key "Enter")
12:15:20 node_1    |    [1] Queued | hook WebDriverIO._beforeStep()
12:15:20 node_1    |    [1] Queued | hook Mailer._beforeStep()
12:15:20 node_1    |    [1] Queued | pressKey: "Enter"
12:15:20 node_1    |    Emitted | step.after (I press key "Enter")
12:15:20 node_1    |    [1] Queued | hook WebDriverIO._afterStep()
12:15:20 node_1    |    [1] Queued | hook Mailer._afterStep()
12:15:20 node_1    |    [1] Queued | step passed
12:15:20 node_1    |    [1] Queued | return result
12:15:20 node_1    |    Emitted | step.before (I see "Confirmation email was sent to")
12:15:20 node_1    |    [1] Queued | hook WebDriverIO._beforeStep()
12:15:20 node_1    |    [1] Queued | hook Mailer._beforeStep()
12:15:20 node_1    |    [1] Queued | see: "Confirmation email was sent to"
12:15:20 node_1    |    Emitted | step.after (I see "Confirmation email was sent to")
12:15:20 node_1    |    [1] Queued | hook WebDriverIO._afterStep()
12:15:20 node_1    |    [1] Queued | hook Mailer._afterStep()
12:15:20 node_1    |    [1] Queued | step passed
12:15:20 node_1    |    [1] Queued | return result
12:15:20 node_1    |    [1] Queued | say I'm going to check email. it takes 10 second
12:15:20 node_1    |    Emitted | step.before (I wait 10)
12:15:20 node_1    |    [1] Queued | hook WebDriverIO._beforeStep()
12:15:20 node_1    |    [1] Queued | hook Mailer._beforeStep()
12:15:20 node_1    |    [1] Queued | wait: 10
12:15:20 node_1    |    Emitted | step.after (I wait 10)
12:15:20 node_1    |    [1] Queued | hook WebDriverIO._afterStep()
12:15:20 node_1    |    [1] Queued | hook Mailer._afterStep()
12:15:20 node_1    |    [1] Queued | step passed
12:15:20 node_1    |    [1] Queued | return result
12:15:20 node_1    |    [1] Queued | _ => event.dispatcher.once(event.step.passed, _ => recorder.retries.pop())
12:15:20 node_1    |    Emitted | step.before (I grab confrim email link after registration "rega1127.5af0191d@example.com")
12:15:20 node_1    |    [1] Queued | hook WebDriverIO._beforeStep()
12:15:20 node_1    |    [1] Queued | hook Mailer._beforeStep()
12:15:20 node_1    |    [1] Queued | grabConfrimEmailLinkAfterRegistration: "rega1127.5af0191d@example.com"
12:15:20 node_1    |    Emitted | step.after (I grab confrim email link after registration "rega1127.5af0191d@example.com")
12:15:20 node_1    |    [1] Queued | hook WebDriverIO._afterStep()
12:15:20 node_1    |    [1] Queued | hook Mailer._afterStep()
12:15:20 node_1    |    [1] Queued | step passed
12:15:20 node_1    |    [1] Queued | return result
12:15:20 node_1    |    Emitted | step.start (I am on page "https://example.com")
12:15:20 node_1    |  • I am on page "https://example.com"
12:15:21 node_1    |    Emitted | step.passed (I am on page "https://example.com")
12:15:21 node_1    |    Step finished in 0.826 sec
12:15:21 node_1    |    Emitted | step.start (I see "Example")
12:15:21 node_1    |  • I see "Example"
12:15:21 node_1    |  > [SmartWait (5000ms)] Locating body in 5000
12:15:21 node_1    |    Emitted | step.passed (I see "Example")
12:15:21 node_1    |    Step finished in 0.159 sec
12:15:21 node_1    |    Emitted | step.start (I dont see "Please use your work email address to sign up")
12:15:21 node_1    |  • I dont see "Please use your work email address to sign up"
12:15:22 node_1    |    Emitted | step.passed (I dont see "Please use your work email address to sign up")
12:15:22 node_1    |    Step finished in 0.44 sec
12:15:22 node_1    |    Emitted | step.start (I click ".btn.show_join")
12:15:22 node_1    |  • I click ".btn.show_join"
12:15:22 node_1    |  > [SmartWait (5000ms)] Locating .btn.show_join in 5000
12:15:22 node_1    |    Emitted | step.passed (I click ".btn.show_join")
12:15:22 node_1    |    Step finished in 0.196 sec
12:15:22 node_1    |    Emitted | step.start (I see "Please use your work email address to sign up")
12:15:22 node_1    |  • I see "Please use your work email address to sign up"
12:15:22 node_1    |  > [SmartWait (5000ms)] Locating body in 5000
12:15:22 node_1    |    Emitted | step.passed (I see "Please use your work email address to sign up")
12:15:22 node_1    |    Step finished in 0.189 sec
12:15:22 node_1    |    Emitted | step.start (I fill field "input[type=email]", "rega1127.5af0191d@example.com")
12:15:22 node_1    |  • I fill field "input[type=email]", "rega1127.5af0191d@example.com"
12:15:33 node_1    |    Emitted | step.passed (I fill field "input[type=email]", "rega1127.5af0191d@example.com")
12:15:33 node_1    |    Step finished in 10.459 sec
12:15:33 node_1    |    Emitted | step.start (I press key "Enter")
12:15:33 node_1    |  • I press key "Enter"
12:15:33 node_1    |    Emitted | step.passed (I press key "Enter")
12:15:33 node_1    |    Step finished in 0.096 sec
12:15:33 node_1    |    Emitted | step.start (I see "Confirmation email was sent to")
12:15:33 node_1    |  • I see "Confirmation email was sent to"
12:15:33 node_1    |  > [SmartWait (5000ms)] Locating body in 5000
12:15:33 node_1    |    Emitted | step.passed (I see "Confirmation email was sent to")
12:15:33 node_1    |    Step finished in 0.321 sec
12:15:33 node_1    |    I'm going to check email. it takes 10 second
12:15:33 node_1    |    Emitted | step.start (I wait 10)
12:15:33 node_1    |  • I wait 10
12:15:43 node_1    |    Emitted | step.passed (I wait 10)
12:15:43 node_1    |    Step finished in 10.011 sec
12:15:43 node_1    |    Emitted | step.start (I grab confrim email link after registration "rega1127.5af0191d@example.com")
12:15:43 node_1    |  • I grab confrim email link after registration "rega1127.5af0191d@example.com"
12:15:51 node_1    |  ✖ FAILED in undefinedms
12:15:51 node_1    | 
12:15:51 node_1    |    Emitted | test.after
12:15:51 node_1    |    [1] Queued | hook WebDriverIO._after()
12:15:51 node_1    |    [1] Queued | hook Mailer._after()
12:16:51 node_1    |    [1] Retrying... Attempt #2
12:16:51 node_1    |    Emitted | step.start (I grab confrim email link after registration "rega1127.5af0191d@example.com")
12:16:51 node_1    |  • I grab confrim email link after registration "rega1127.5af0191d@example.com"
12:16:57 node_1    | Message #24283
12:16:57 node_1    | (#24283) Body ['TEXT'] found, 95049 total bytes
12:16:57 node_1    | (#24283) Body ['TEXT'] (16204/95049)
12:16:57 node_1    | (#24283) Parsed header: { from: [ 'Example <info@example.com>' ] }
12:16:57 node_1    | (#24283) Body ['TEXT'] (32588/95049)
12:16:57 node_1    | (#24283) Body ['TEXT'] (48972/95049)
12:16:57 node_1    | (#24283) Body ['TEXT'] (65356/95049)
12:16:57 node_1    | (#24283) Body ['TEXT'] (81740/95049)
12:16:57 node_1    | (#24283) Body ['TEXT'] (95049/95049)
12:16:57 node_1    | (#24283) Body ['TEXT'] Finished
12:16:57 node_1    | (#24283) Attributes: { date: 2018-05-07T09:15:37.000Z,
12:16:57 node_1    |   flags: [ '\\Recent', 'encrypted' ],
12:16:57 node_1    |   uid: 24680 }
12:16:57 node_1    | (#24283) Finished
12:16:57 node_1    | https://accounts.example.com/sign-up/account?token=edee8772-fee2-4b68-a66f-9727a7679ca5&isTest=1
12:16:57 node_1    | undefined
12:16:57 node_1    |    Emitted | step.passed (I grab confrim email link after registration "rega1127.5af0191d@example.com")
12:16:57 node_1    |    Step finished in 6.57 sec
12:16:57 node_1    |    [1] Queued | say https://accounts.example.com/sign-up/account?token=edee8772-fee2-4b68-a66f-9727a7679ca5&isTest=1
12:16:57 node_1    |    Emitted | step.before (I am on page "https://accounts.example.com/sign-up/account?token=edee8772-fee2-4b68-a66f-9727a7679ca5&isTest=1")
12:16:57 node_1    |    [1] Queued | hook WebDriverIO._beforeStep()
12:16:57 node_1    |    [1] Queued | hook Mailer._beforeStep()
12:16:57 node_1    |    [1] Queued | amOnPage: "https://accounts.example.com/sign-up/account?token=edee8772-fee2-4b68-a66f-9727a7679ca5&isTest=1"
12:16:57 node_1    |    Emitted | step.after (I am on page "https://accounts.example.com/sign-up/account?token=edee8772-fee2-4b68-a66f-9727a7679ca5&isTest=1")
12:16:57 node_1    |    [1] Queued | hook WebDriverIO._afterStep()
12:16:57 node_1    |    [1] Queued | hook Mailer._afterStep()
12:16:57 node_1    |    [1] Queued | step passed
12:16:57 node_1    |    [1] Queued | return result
12:16:57 node_1    |    Emitted | step.before (I see "Create Account")
12:16:57 node_1    |    [1] Queued | hook WebDriverIO._beforeStep()
12:16:57 node_1    |    [1] Queued | hook Mailer._beforeStep()
12:16:57 node_1    |    [1] Queued | see: "Create Account"
12:16:57 node_1    |    Emitted | step.after (I see "Create Account")
12:16:57 node_1    |    [1] Queued | hook WebDriverIO._afterStep()
12:16:57 node_1    |    [1] Queued | hook Mailer._afterStep()
12:16:57 node_1    |    [1] Queued | step passed
12:16:57 node_1    |    [1] Queued | return result
12:16:57 node_1    |  > [Session] cleaning cookies and localStorage
12:16:57 node_1    |    [1] Queued | fire test.passed
12:16:57 node_1    |    [1] Queued | finish test
12:16:58 node_1    |    https://accounts.example.com/sign-up/account?token=edee8772-fee2-4b68-a66f-9727a7679ca5&isTest=1
12:16:58 node_1    |    Emitted | step.start (I am on page "https://accounts.example.com/sign-up/account?token=edee8772-fee2-4b68-a66f-9727a7679ca5&isTest=1")
12:16:58 node_1    |  • I am on page "https://accounts.example.com/sign-up/account?token=edee8772-fee2-4b68-a66f-9727a7679ca5&isTest=1"
12:16:58 node_1    |    Emitted | suite.after ([object Object])
12:16:58 node_1    |    [1] Queued | hook WebDriverIO._afterSuite()
12:16:58 node_1    |    [1] Queued | hook Mailer._afterSuite()
12:16:58 node_1    | Connection ended
12:17:00 node_1    |    Emitted | step.passed (I am on page "https://accounts.example.com/sign-up/account?token=edee8772-fee2-4b68-a66f-9727a7679ca5&isTest=1")
12:17:00 node_1    |    Step finished in 2.305 sec
12:17:00 node_1    |    Emitted | step.start (I see "Create Account")
12:17:00 node_1    |  • I see "Create Account"
12:17:00 node_1    |  > [SmartWait (5000ms)] Locating body in 5000
12:17:00 node_1    |    Emitted | step.passed (I see "Create Account")
12:17:00 node_1    |    Step finished in 0.09 sec
12:17:00 node_1    |    Emitted | test.passed ([object Object])
12:17:00 node_1    |    Error processing test.passed event:
12:17:00 node_1    |    TypeError: Cannot convert undefined or null to object
12:17:00 node_1    |     at EventEmitter.event.dispatcher.on (/app/node_modules/codeceptjs/lib/listener/steps.js:50:5)
12:17:00 node_1    |     at EventEmitter.emit (events.js:185:15)
12:17:00 node_1    |     at EventEmitter.emit (domain.js:421:20)
12:17:00 node_1    |     at Object.emit (/app/node_modules/codeceptjs/lib/event.js:47:28)
12:17:00 node_1    |     at recorder.add (/app/node_modules/codeceptjs/lib/scenario.js:65:54)
12:17:00 node_1    |     at <anonymous>
12:17:00 node_1    |     at process._tickCallback (internal/process/next_tick.js:118:7)
12:17:00 node_1    |    [1] Error | TypeError: Cannot set property 'state' of undefined
12:17:00 node_1    |    [1] Starting <teardown> session
12:17:00 node_1    |    Emitted | test.failed ([object Object])
12:17:00 node_1    |    [1] <teardown> Queued | hook WebDriverIO._failed()
12:17:00 node_1    |    [1] <teardown> Queued | hook Mailer._failed()
12:17:00 node_1    |    [1] <teardown> Queued | () => done(err)
12:17:00 node_1    |    [1] <teardown> Stopping recording promises
12:17:00 node_1    | 
12:17:00 node_1    | -- FAILURES:
12:17:00 node_1    | 
12:17:00 node_1    |   1) landing is alive
12:17:00 node_1    |        open landing:
12:17:00 node_1    |      Cannot set property 'state' of undefined
12:17:00 node_1    |   
12:17:00 node_1    |   Scenario Steps:
12:17:00 node_1    |   
12:17:00 node_1    |   - I.grabConfrimEmailLinkAfterRegistration("rega1127.5af0191d@example.com") at Test.Scenario (/app/tests/reg_from_landing_test.js:18:92)
12:17:00 node_1    |   - I.wait(10) at Test.Scenario (/app/tests/reg_from_landing_test.js:17:7)
12:17:00 node_1    |   - I.see("Confirmation email was sent to") at Test.Scenario (/app/tests/reg_from_landing_test.js:15:7)
12:17:00 node_1    |   - I.pressKey("Enter") at Test.Scenario (/app/tests/reg_from_landing_test.js:14:7)
12:17:00 node_1    |   - I.fillField("input[type=email]", "rega1127.5af0191d@example.com") at Test.Scenario (/app/tests/reg_from_landing_test.js:13:7)
12:17:00 node_1    |   - I.see("Please use your work email address to sign up") at Test.Scenario (/app/tests/reg_from_landing_test.js:12:7)
12:17:00 node_1    |   - I.click(".btn.show_join") at Test.Scenario (/app/tests/reg_from_landing_test.js:11:7)
12:17:00 node_1    |   - I.dontSee("Please use your work email address to sign up") at Test.Scenario (/app/tests/reg_from_landing_test.js:10:7)
12:17:00 node_1    |   - I.see("Example") at Test.Scenario (/app/tests/reg_from_landing_test.js:9:7)
12:17:00 node_1    |   - I.amOnPage("https://example.com") at Test.Scenario (/app/tests/reg_from_landing_test.js:8:7)
12:17:00 node_1    |   
12:17:00 node_1    |   TypeError: Cannot set property 'state' of undefined
12:17:00 node_1    |       at /app/node_modules/mocha/lib/runner.js:589:20
12:17:00 node_1    |       at done (/app/node_modules/mocha/lib/runnable.js:301:5)
12:17:00 node_1    |       at /app/node_modules/mocha/lib/runnable.js:392:7
12:17:00 node_1    |       at recorder.add (/app/node_modules/codeceptjs/lib/scenario.js:66:43)
12:17:00 node_1    |       at <anonymous>
12:17:00 node_1    |       at process._tickCallback (internal/process/next_tick.js:118:7)
12:17:00 node_1    | 
12:17:00 node_1    | 
12:17:00 node_1    |   FAIL  | 1 passed, 1 failed   // 2m
12:17:00 node_1    |    Emitted | global.result ([object Object])
12:17:00 node_1    |    [1] <teardown> Queued | hook WebDriverIO._finishTest()
12:17:00 node_1    |    [1] <teardown> Queued | hook Mailer._finishTest()
12:17:00 node_1    |    Emitted | global.after ([object Object])
12:17:00 node_1    |  > Screenshot has been saved to /app/output/open_landing_'after_all'_hook__codeceptjs.afterSuite.failed.png
12:17:00 node_1    |  ✖ FAILED in 99687ms
12:17:00 node_1    | 
12:17:00 chrome_1  | 09:17:00.760 INFO [ActiveSessions$1.onStop] - Removing session fd17d9f3c3fd17299fba032c8679eeab (org.openqa.selenium.chrome.ChromeDriverService)
12:22:01 node_1    | Connection ended
12:22:01 node_1    | npm ERR! code ELIFECYCLE
12:22:01 node_1    | npm ERR! errno 1
12:22:01 node_1    | npm ERR! example-selenium-test@1.0.0 test: `codeceptjs run --steps --verbose`
12:22:01 node_1    | npm ERR! Exit status 1
12:22:01 node_1    | npm ERR! 
12:22:01 node_1    | npm ERR! Failed at the hygger-selenium-test@1.0.0 test script.
12:22:01 node_1    | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
12:22:01 node_1    | 
12:22:01 node_1    | npm ERR! A complete log of this run can be found in:
12:22:01 node_1    | npm ERR!     /root/.npm/_logs/2018-05-07T09_22_01_531Z-debug.log
12:22:02 regatest_node_1 exited with code 1
12:22:02 Stopping regatest_chrome_1 ... 

```

> Provide test source code if related

```js

Scenario('open landing', async (I) => {
    I.amOnPage('https://example.com');
    I.see('example');
    I.dontSee('Please use your work email address to sign up');
    I.click('.btn.show_join');
    I.see('Please use your work email address to sign up');
    I.fillField('input[type=email]', email);
    I.pressKey('Enter');
    I.see('Confirmation email was sent to');
    I.say(`I'm going to check email. it takes 10 second`);
    I.wait(10);
    const link = await I.retry({ retries: 3, minTimeout: 60*1000, maxTimeout: 61 * 1000 }).grabConfrimEmailLinkAfterRegistration(email);
    I.say(link);
    I.amOnPage(link);
    I.see('Create Account');

});
```

### Details

* CodeceptJS version:  CodeceptJS v1.1.7
* NodeJS Version:  FROM node:9.10.1
* Operating System: run in Docker on macOS
* WebDriverIO is used
* Configuration file:

```js
# codecept.json
{
  "output": "./output",
  "helpers": {
    "WebDriverIO": {
      "url": "https://example.com",
      "host": "chrome",
      "port": 4444,
      "smartWait": 5000,
      "browser": "chrome",
      "restart": false,
      "windowSize": "maximize",
      "timeouts": {
        "script": 60000,
        "page load": 10000
      }
    },
    "Mailer": {
      "require": "./helpers/mailer_helper.js"
    }
  },
  "include": {},
  "mocha": {},
  "bootstrap": false,
  "teardown": null,
  "hooks": [],
  "tests": "./tests/*.js",
  "timeout": 10000,
  "name": "example-selenium-test"
}
```

**Comment by NaLLiFFuNT** [comment]
the mail helper looks like

````js
class Mailer extends Helper {

  // before/after hooks
  _before() {
    // remove if not used
  }

  _after() {
    // remove if not used
  }

  // add custom methods here
  // If you need to access other helpers
  // use: this.helpers['helperName']
  async grabConfrimEmailLinkAfterRegistration(email) {
    return new Promise((resolve, reject) => {
        if ( haveTheMail ) {
            resolve('link from email');
         } else  {
            reject(new Error('no email'));
        }
    })
  }
}
````
