### ISSUE TITLE
def command cannot handle parameter destruction

### ISSUE THREAD

**Issue by GerroDen** [codeceptjs/CodeceptJS#1261]
#### What are you trying to achieve?
I run `codeceptjs def` to create the `steps.d.ts` in my ui test root folder.
The configuration is correct and the tests run.

#### What do you get instead?
I get an error in the console and no ts file is created.

```bash
node_modules/codeceptjs/lib/parser.js:14
    const paramValue = paramName.split('=');
                                 ^

TypeError: paramName.split is not a function
    at module.exports.toTypeDef (/home/lkimmel/mahou/microblog/node_modules/codeceptjs/lib/parser.js:14:34)
    at addAllMethodsInObject (/home/lkimmel/mahou/microblog/node_modules/codeceptjs/lib/command/definitions.js:218:20)
    at codecept.init (/home/lkimmel/mahou/microblog/node_modules/codeceptjs/lib/command/definitions.js:187:27)
    at module.exports (/home/lkimmel/mahou/microblog/node_modules/codeceptjs/lib/hooks.js:26:13)
    at Codecept.bootstrap (/home/lkimmel/mahou/microblog/node_modules/codeceptjs/lib/codecept.js:86:5)
    at Codecept.init (/home/lkimmel/mahou/microblog/node_modules/codeceptjs/lib/codecept.js:38:10)
    at Command.module.exports (/home/lkimmel/mahou/microblog/node_modules/codeceptjs/lib/command/definitions.js:163:12)
    at Command.listener (/home/lkimmel/mahou/microblog/node_modules/commander/index.js:315:8)
    at Command.emit (events.js:182:13)
    at Command.parseArgs (/home/lkimmel/mahou/microblog/node_modules/commander/index.js:654:12)
```

My page object has methods defined in ES8 like this:
```js
const I = actor();

class PageObject {
	addPermissionsToSpace({x, y, z}) {
		// ...
	}
}

module.exports = new PageObject();
```

When i remove the destruction part the command is running. It would be great to use the full ES8 features and get a ts file for code completion. :)

### Details

* CodeceptJS version: 1.4.3
* NodeJS Version: v10.9.0
* Operating System: Ubuntu 16.04 LTS

**Comment by pablopaul** [comment]
@GerroDen please try to add a empty object as default param like “addPermissions({x, y, z} = {}) - does this help?

**Comment by GerroDen** [comment]
@pablopaul yes that works.
I am looking forward to a nicer support :> ;)

**Comment by pablopaul** [comment]
@GerroDen why not giving it a try yourself?
