### ISSUE TITLE
Test w/multiple async scenarios & callback function throws error 

### ISSUE THREAD

**Issue by adams0619** [codeceptjs/CodeceptJS#1272]
#### What are you trying to achieve?

I've created a test file with 2 `Scenarios` with one test using `Yahoo.com` & the other test using `Google.com`. I am using an internally hosted package (`aat`) to validate a11y & am using `async / await` syntax to wait for callback function from my a11y test to return before passing / failing a test. However, I have noticed that only one test runs, the other test never runs and fails immediately. The error I am getting points to an internal Codeceptjs method where a test's arguments are extracted. Please help me determine where I might be going wrong in my implementation?

#### What do you get instead?
```bash
CodeceptJS v1.4.3
Using test root "/Users/${home_dir}/test-ccjs"
Helpers: Nightmare
Plugins: screenshotOnFail
test --
   [1] Starting recording promises
   Emitted | suite.before ([object Object])
› [Session] Starting singleton browser session
  yahoo first @callback
   Emitted | test.before ([object Object])
   Emitted | test.start ([object Object])
   Emitted | step.before (I am on page "http://yahoo.com")
   Emitted | step.after (I am on page "http://yahoo.com")
   Emitted | step.before (I fill field "p", "github nightmare")
   Emitted | step.after (I fill field "p", "github nightmare")
   Emitted | step.before (I click "#uh-search-button")
   Emitted | step.after (I click "#uh-search-button")
   Emitted | step.before (I wait for element "#main")
   Emitted | step.after (I wait for element "#main")
   Emitted | step.before (I see element "#main .searchCenterMiddle li a")
   Emitted | step.after (I see element "#main .searchCenterMiddle li a")
   Emitted | step.before (I see element "//a[contains(@href,'github.com/segmentio/nightmare')]")
   Emitted | step.after (I see element "//a[contains(@href,'github.com/segmentio/nightmare')]")
   Emitted | step.before (I see "segmentio/nightmare", "#main li a")
   Emitted | step.after (I see "segmentio/nightmare", "#main li a")
   Emitted | step.before (I execute script () => {
        return document.body.innerHTML;
    })
   Emitted | step.after (I execute script () => {
        return document.body.innerHTML;
    })
   Emitted | step.start (I am on page "http://yahoo.com")
    I am on page "http://yahoo.com"
    › log: DARLA notice: 405
    › log: DARLA notice: 405
    › warn: yui: NOT loaded: highlander-vertical-video
    › warn: yui: NOT loaded: highlander-client-templates-viewer-controls-atomic
    › warn: yui: NOT loaded: highlander-vertical-video
    › warn: yui: NOT loaded: highlander-vertical-video
    › warn: yui: NOT loaded: highlander-client-templates-viewer-controls-atomic
    › warn: yui: NOT loaded: highlander-client-templates-viewer-controls-atomic
    › warn: yui: NOT loaded: highlander-vertical-video
    › [URL] https://www.yahoo.com/
    › [Code] 200
    › [Headers] {"accept-ch":["device-memory, dpr, width, viewport-width, rtt, downlink, ect"],"accept-ch-lifetime":["604800"],"age":["0"],"cache-control":["no-store, no-cache, max-age=0, private"],"…
   Emitted | step.passed (I am on page "http://yahoo.com")
   Emitted | step.finish (I am on page "http://yahoo.com")
   Emitted | step.start (I fill field "p", "github nightmare")
    I fill field "p", "github nightmare"
   Emitted | step.passed (I fill field "p", "github nightmare")
   Emitted | step.finish (I fill field "p", "github nightmare")
   Emitted | step.start (I click "#uh-search-button")
    I click "#uh-search-button"
   Emitted | step.passed (I click "#uh-search-button")
   Emitted | step.finish (I click "#uh-search-button")
   Emitted | step.start (I wait for element "#main")
    I wait for element "#main"
   Emitted | step.passed (I wait for element "#main")
   Emitted | step.finish (I wait for element "#main")
   Emitted | step.start (I see element "#main .searchCenterMiddle li a")
    I see element "#main .searchCenterMiddle li a"
   Emitted | step.passed (I see element "#main .searchCenterMiddle li a")
   Emitted | step.finish (I see element "#main .searchCenterMiddle li a")
   Emitted | step.start (I see element "//a[contains(@href,'github.com/segmentio/nightmare')]")
    I see element "//a[contains(@href,'github.com/segmentio/nightmare')]"
   Emitted | step.passed (I see element "//a[contains(@href,'github.com/segmentio/nightmare')]")
   Emitted | step.finish (I see element "//a[contains(@href,'github.com/segmentio/nightmare')]")
   Emitted | step.start (I see "segmentio/nightmare", "#main li a")
    I see "segmentio/nightmare", "#main li a"
   Emitted | step.passed (I see "segmentio/nightmare", "#main li a")
   Emitted | step.finish (I see "segmentio/nightmare", "#main li a")
   Emitted | step.start (I execute script () => {
        return document.body.innerHTML;
    })
    I execute script () => {
        return document.body.innerHTML;
    }
   Emitted | step.passed (I execute script () => {
        return document.body.innerHTML;
    })
   Emitted | step.finish (I execute script () => {
        return document.body.innerHTML;
    })

   Emitted | test.passed ([object Object])
   Emitted | test.finish ([object Object])
  ✔ OK in 53728ms
   Emitted | test.after ([object Object])
› [Session] cleaning up
  google @callback
   Emitted | test.before ([object Object])
   Emitted | test.start ([object Object])
  ✖ FAILED in 1ms
   Emitted | test.after ([object Object])
› [Session] cleaning up
   Emitted | suite.after ([object Object])
-- FAILURES:
  1) test
       google @callback:
     Error: Object of type function (){for(var e=[],t=0;t<this.length;t++)e.indexOf(this[t])==-1&&e.push(this[t]);return e} is not defined in container
      at getInjectedArguments (node_modules/codeceptjs/lib/scenario.js:242:13)
      at Context.test.fn (node_modules/codeceptjs/lib/scenario.js:76:26)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)

  FAIL  | 1 passed, 1 failed   // 54s
   Emitted | global.result ([object Object])
   Emitted | global.after ([object Object])
```

> Provide test source code if related

```js
Feature('test')

Scenario('yahoo first @callback', async (I) => {
    I.amOnPage('http://yahoo.com');
    I.fillField('p', 'github nightmare');
    I.click('#uh-search-button');
    I.waitForElement('#main');
    I.seeElement('#main .searchCenterMiddle li a');
    I.seeElement("//a[contains(@href,'github.com/segmentio/nightmare')]");
    I.see('segmentio/nightmare','#main li a');
    let html = await I.executeScript( () => {
        return document.body.innerHTML;
    });
    await I.a11y(html)
});

Scenario('google @callback', async (I) => {
    I.amOnPage('http://google.com');
    I.fillField('.glFyf', 'github nigthmare');
    I.click('input[name="btnK"]');
    I.seeElement("//a[contains(@href,'github.com/segmentio/nightmare')]");
    let html = await I.executeScript( () => {
        return document.body.innerHTML;
    });
    await I.a11y(html)
});
```

### Details

* CodeceptJS version: v1.4.3
* NodeJS Version: v8.11.4
* Operating System: macOS High Siera (10.13.6)
* Protractor || WebDriverIO || Nightmare version (if related) - **Nightmare** v3.0.1
* Configuration file:

```js
{
  "output": "./output",
  "helpers": {
    "Nightmare": {
      "url": "http://www.yahoo.com",
      "show": true,
      "restart": false
    }
  },
  "include": {
    "I": "./a11y_actor_steps.js"
  },
  "mocha": {},
  "bootstrap": false,
  "teardown": null,
  "hooks": [],
  "gherkin": {},
  "plugins": {
    "screenshotOnFail": {
      "enabled": true
    }
  },
  "tests": "./*_test.js",
  "timeout": 10000,
  "name": "test-ccjs"
}
```

The contents of my custom step file (`a11y_actor_steps.js`) are as follows :
```js
let expect = require('chai').expect;
let AAT = require("aat");

module.exports = function () {
    return actor({
        a11y: (html) => {
            return new Promise( (done, reject) => {
                AAT.testHTML(html, function (data) {
                    // This is the callback function that we need to wait for before passing / failing the test
                    try {
                        expect(data.violations.count).to.equal(2);
                        resolve();
                    } catch(e) {
                        reject(e)
                    }
                });
            });
        }
    })
};
```

**Comment by DavertMik** [comment]
Not sure of the actual issue, but for your case it's recommended to create a new Helper https://codecept.io/helpers/#helpers Use helpers wherever you need to run low-level methods. Use `actor` when you need to combine high-level methods, group actions, etc.

So you can create `AccesibilityHelper` and include it as you  do for Nightmare
I think in this case everything should be fine. If you return a promise in a helper's method you won't need to use await, btw.

**Comment by adams0619** [comment]
@DavertMik Before trying this I tried the solution you presented (as an additional Helper w/o the `await`), but I still came out with the same error. When I debug the issue the error is caused from `scenario.js` inside the `getInjectedArguments` function. The following loop:
```js
for (const key in params) {
   const obj = params[key];
   ...
}
```
ends up having an invalid key that is not found in the `params` object. I'm not quite sure why this is the case.

**Comment by GSasu** [comment]
@adams0619 It looks to me that most of your async code is waiting for the innerHTML to be returned.
In this case you have multiple options:
try getting the text using a xpath or css selector with https://codecept.io/helpers/WebDriverIO/#grabtextfrom
build your own helper with webdriverIo http://webdriver.io/api/property/getText.html

or use an xpath selector that directly targets your innerHTML text ie.:
//*[contains(@class, 'someClassName')][contains(text(), 'your text here')]

**Comment by adams0619** [comment]
@GSasu I specifically need to test against the `HTML` elements in order to verify accessibility through `aria-labels` and the likes, but I went ahead and tried running my tests using `WebdriverIO` and using the `grabTMLFrom` method, but am still running into the same issue. 

Given what I saw from the error itself while debugging, I would think the errors comes from how `codeceptjs` is breaking down the `Scenarios` and passing the tests function arguments to Mocha.

**Comment by GSasu** [comment]
@adams0619 Accessibility tests are usually done with specific tools. Nevertheless, when you say that you want to test aria-labels, what exactly do you want to tests more precisely? Maybe with these details I could come up with a better solution or helper.

**Comment by adams0619** [comment]
@GSasu the company I work for has an in-house accessibility (a11y) testing solution that I am using. It takes in the HTML DOM for the webpage you want to test and scans for any a11y violations such as missing `aria-labels`, `tabindex`, etc

What I am trying to do is add `codeceptjs` as a tool to help create an automated end-to-end a11y testing solution. By adding the in-house a11y testing tool as helper I was able to connect the two and get it running, but ran into the issues I've described above when attempting to write multiple `Scenarios`. 

Please take a looks at my attempt to fix this problem in PR #1290

**Comment by DavertMik** [comment]
Found an issue in your code:

You call `resolve()` but you pass `done` instead of resolve
```
        a11y: (html) => {
            return new Promise( (done, reject) => {
                AAT.testHTML(html, function (data) {
                    // This is the callback function that we need to wait for before passing / failing the test
                    try {
                        expect(data.violations.count).to.equal(2);
                        resolve();
                    } catch(e) {
                        reject(e)
                    }
                });
            });
        }
    })
```

**Comment by DavertMik** [comment]
In other news: I can't reproduce this issue
