### ISSUE TITLE
Shell mode not opening a browser with Pupeeteer

### ISSUE THREAD

**Issue by allenhwkim** [codeceptjs/CodeceptJS#1331]
#### What are you trying to achieve?
Trying to test puppeteer as interactive shell mode

#### What do you get instead?
I see "FAIL" message when I try `I.amOnPage('https://www.google.com')`
![image](https://user-images.githubusercontent.com/1437734/48657382-16e6f580-e9fe-11e8-9e99-b9421201ce29.png)

> Provide console output if related. Use `--verbose` mode for more details.

```bash
codeceptjs shell --verbose
String interactive shell for current suite...
   [1] Starting recording promises
   Emitted | suite.before ([object Object])
   Emitted | test.before
   Error processing test.before event:
   TypeError: Cannot read property 'config' of undefined
    at EventEmitter.event.dispatcher.on (/Users/allen.kim/gitlab/ovr-client-new/node_modules/codeceptjs/lib/listener/config.js:33:19)
    at EventEmitter.emit (events.js:165:20)
    at Object.emit (/Users/allen.kim/gitlab/ovr-client-new/node_modules/codeceptjs/lib/event.js:49:28)
    at codecept.init (/Users/allen.kim/gitlab/ovr-client-new/node_modules/codeceptjs/lib/command/interactive.js:25:11)
    at module.exports (/Users/allen.kim/gitlab/ovr-client-new/node_modules/codeceptjs/lib/hooks.js:26:13)
    at Codecept.bootstrap (/Users/allen.kim/gitlab/ovr-client-new/node_modules/codeceptjs/lib/codecept.js:85:5)
    at Codecept.init (/Users/allen.kim/gitlab/ovr-client-new/node_modules/codeceptjs/lib/codecept.js:38:10)
    at Command.module.exports (/Users/allen.kim/gitlab/ovr-client-new/node_modules/codeceptjs/lib/command/interactive.js:14:12)
    at Command.listener (/Users/allen.kim/gitlab/ovr-client-new/node_modules/codeceptjs/node_modules/commander/index.js:315:8)
    at Command.emit (events.js:160:13)
   [1] Starting <pause> session
 Interactive shell started
 Press ENTER to resume test
 - Use JavaScript syntax to try steps in action
 - Press TAB twice to see all available commands
 - Enter next to run the next step
 I.amOnPage('https://www.google.com')
   Emitted | step.before (I am on page "https://www.google.com")
   Emitted | step.after (I am on page "https://www.google.com")
   Emitted | step.start (I am on page "https://www.google.com")
   [1] <pause> Error | TypeError: Cannot read property 'goto' of undefined
   Emitted | step.failed (I am on page "https://www.google.com")
   Emitted | step.finish (I am on page "https://www.google.com")
 FAIL  Cannot read property 'goto' of undefined
```

> Provide test source code if related
N/A

### Details

* CodeceptJS version: 1.3
* NodeJS Version: 9.4
* Operating System: Mac Os X El Capitan
* Protractor || WebDriverIO || Nightmare version (if related) Pupeeteer 1.7.7
* Configuration file:

```js
{
  "tests": "scenarios/**/*.test.js",
  "timeout": 10000,
  "output": "./reports",
  "mocha": {
    "reporterOptions": {
        "reportDir": "./reports"
    }
  },
  "helpers": {
    "puppeteer": {
      "show": true,
      "url": "https://local-cfa.rogers.com:9201",
      "chrome": {
        "ignoreHTTPSErrors": true,
        "timeout": 0
      },
      "Mochawesome": {
        "uniqueScreenshotNames": "true"
      }
    }
  },
  "include": {
    "I": "./scenarios/codecept-steps.js"
  },
  "bootstrap": false,
  "name": "app"
}
```

**Comment by PeterNgTr** [comment]
I believe you fixed it here https://github.com/Codeception/CodeceptJS/pull/1332
