### ISSUE TITLE
Could not load helper WebDriver from module './helper/WebDriver'

### ISSUE THREAD

**Issue by jbricenoz** [codeceptjs/CodeceptJS#1409]
#### What are you trying to achieve?
Run just a test script using `codeceptjs run` command.

#### What do you get instead?

```
Could not load helper WebDriver from module './helper/WebDriver':
Required modules are not installed.

RUN: [sudo] npm install -g webdriverio@^5.1.0
Error: 
    at createHelpers (/usr/local/lib/node_modules/codeceptjs/lib/container.js:152:13)
    at Function.create (/usr/local/lib/node_modules/codeceptjs/lib/container.js:32:25)
    at Codecept.init (/usr/local/lib/node_modules/codeceptjs/lib/codecept.js:55:15)
    at Command.module.exports (/usr/local/lib/node_modules/codeceptjs/lib/command/run.js:35:14)
    at Command.listener (/usr/local/lib/node_modules/codeceptjs/node_modules/commander/index.js:315:8)
    at Command.emit (events.js:182:13)
    at Command.parseArgs (/usr/local/lib/node_modules/codeceptjs/node_modules/commander/index.js:654:12)
    at Command.parse (/usr/local/lib/node_modules/codeceptjs/node_modules/commander/index.js:474:21)
    at Object.<anonymous> (/usr/local/lib/node_modules/codeceptjs/bin/codecept.js:142:9)
    at Module._compile (internal/modules/cjs/loader.js:689:30)

```

### Details

* CodeceptJS version: **v2.0.1**
* NodeJS Version: **v10.15.0**
* Operating System: Mac OS Sierra
* Protractor || WebDriverIO || Nightmare version (if related)
* webdriverio@5.2.0
* Configuration file:

```js
exports.config = {
  tests: './*_test.js',
  output: './output',
  helpers: {
    WebDriver: {
      url: 'http://projects.midomain.com',
      browser: 'chrome'
    }
  },
  include: {
    I: './steps_file.js'
  },
  bootstrap: null,
  mocha: {},
  name: 'web-codeceptjs'
}
```

**Comment by peijianju** [comment]
Hi, if this is still a problem, you could try to install concepts and webdriverio in local package.json and use `npm run` to call `codeceptjs`. Use local dependencies instead of global ones.

**Comment by vborodulin** [comment]
you should use npm/yarn scrips to run codeceptjs instance inside your project and use WebDriver deps in project folder.
Using ```codeceptjs run``` command codeceptjs try find global installed WebDriver
