### ISSUE TITLE
Codeceptjs Windows 10 not running (Node v10.14.2)

### ISSUE THREAD

**Issue by alexperezmmt** [codeceptjs/CodeceptJS#1427]
#### What are you trying to achieve?
I'm trying to run codeceptjs in a Windows 10 machine
#### What do you get instead?
When I run the command `node node_modules/.bin/codeceptjs init` as the documentation says
I got:
```
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^

SyntaxError: missing ) after argument list
    at new Script (vm.js:79:7)
    at createScript (vm.js:251:10)
    at Object.runInThisContext (vm.js:303:10)
    at Module._compile (internal/modules/cjs/loader.js:657:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:282:19)
```
> Provide console output if related. Use `--verbose` mode for more details.

```bash
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^

SyntaxError: missing ) after argument list
    at new Script (vm.js:79:7)
    at createScript (vm.js:251:10)
    at Object.runInThisContext (vm.js:303:10)
    at Module._compile (internal/modules/cjs/loader.js:657:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:282:19)
```
### Details

* CodeceptJS version: latest
* NodeJS Version: v10.14.2
* Operating System: Windows 10

The command stop the execution showing that error message and I cannot continue with the process.
Any help, please?

Thanks

**Comment by ngadiyak** [comment]
@DavertMik plz fix docs
