### ISSUE TITLE
CodeceptJS with Applitools

### ISSUE THREAD

**Issue by jordiponsllaurado** [codeceptjs/CodeceptJS#1488]
#### What are you trying to achieve?
I'm trying to sent an image to Applitools Eyes

#### What do you get instead?
I'm not able to open the connection with applitools

> Provide console output if related. Use `--verbose` mode for more details.

```bash
Cannot read property 'sessionID' of undefined
  ypeError: Cannot read property 'sessionID' of undefined
      at Eyes.getAUTSessionId (node_modules/@applitools/eyes.webdriverio/src/Eyes.js:1361:85)
      at _validateSessionOpen.then.then.then (node_modules/@applitools/eyes.sdk.core/lib/EyesBase.js:1571:26)
      at <anonymous>
      at process._tickDomainCallback (internal/process/next_tick.js:228:7)
```

> Provide test source code if related

```js
Scenario('Live Preview', async I => {
  await I.amOnPage('?0')
  const {Eyes, Target} = require('@applitools/eyes.webdriverio');


  const browser = this.helpers['WebDriver'].browser
  const eyes = new Eyes();
  await eyes.setApiKey("API KEY")
  try {
    await eyes.setForceFullPageScreenshot(true)
    await eyes.open(browser, 'Test', 'Preview')
    // await loadFromJson()
    await eyes.check("Login Window test", Target.window());
    await eyes.close()
  } finally {
    // If the test was aborted before eyes.close was called ends the test as aborted.
    await eyes.abortIfNotClosed();
  }
})
```

### Details

* CodeceptJS version:
* NodeJS Version:
* Operating System:
* Protractor || WebDriverIO || Nightmare version (if related)
* Configuration file:

```js
{
  "output": "./output",
  "helpers": {
    "WebDriver": {
      "url": "http://localhost:9000",
      "browser": "chrome",
      "windowSize": "1280x800",
      "show": true,
    },
  },
  "mocha": {},
  "bootstrap": false,
  "teardown": null,
  "hooks": [],
  "tests": "./tests/features/visual/*.js",
  "timeout": 10000,
  "name": "builder"
}

```

**Comment by DavertMik** [comment]
They use older API of webdriverio. 
Since webdriverio v5 API has changed. However, I'm not sure how to specify that new version to Applitools

**Comment by elgalu** [comment]
still an issue?

**Comment by DavertMik** [comment]
not sure, I will close it for now
