### ISSUE TITLE
With Typesscript unable to use multiple await in one scenario. 

### ISSUE THREAD

**Issue by sudeepsarkar2017** [codeceptjs/CodeceptJS#1575]
#### What are you trying to achieve?
trying to use multiple awaits in one scenario using typescript (working fine with javascript)
  
#### What do you get instead?
session terminates
> Provide console output if related. Use `--verbose` mode for more details.
"NoSuchSessionError: This driver instance does not have a valid session ID (did you call WebDriver.quit()?) and may no longer be used."

         "after all" hook: codeceptjs.afterSuite:
     This driver instance does not have a valid session ID (did you call WebDriver.quit()?) and may no longer be used.
  oSuchSessionError: This driver instance does not have a valid session ID (did you call WebDriver.quit()?) and may no longer be used.
      at session_.flow_.promise (C:\Users\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver.js:847:16)
      at new ManagedPromise (C:\Users\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:1077:7)
      at ControlFlow.promise (C:\Users\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2505:12)
      at promise.finally (C:\Users\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver.js:846:34)
      at C:\Users\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:1684:12
      at ManagedPromise.invokeCallback_ (C:\Users\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:1376:14)
      at TaskQueue.execute_ (C:\Users\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:3084:14)
      at TaskQueue.executeNext_ (C:\Users\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:3067:27)
      at asyncRun (C:\Users\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2927:27)
      at C:\Users\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:668:7
  From: Task: WebDriver.findElements(By(xpath, //a[@title='Deelnemer (Alt+Ctrl+D)']))
      at thenableWebDriverProxy.schedule (C:\Users\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver.js:807:17)
      at thenableWebDriverProxy.findElements (C:\Users\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver.js:1048:19)
      at ptor.waitForAngular.then (C:\Users\AppData\Roaming\npm\node_modules\protractor\built\element.js:159:44)
      at ManagedPromise.invokeCallback_ (C:\Users\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:1376:14)
      at TaskQueue.execute_ (C:\Users\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:3084:14)
      at TaskQueue.executeNext_ (C:\Users\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:3067:27)
      at asyncRun (C:\Users\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2927:27)
      at C:\Users\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:668:7
      at process._tickCallback (internal/process/next_tick.js:68:7)

> Provide test source code if related
let text1 = await I.grabTextFrom($locator)
let text1 = await I.grabTextFrom($locator)

### Details

* CodeceptJS version: 2.0.8
* NodeJS Version: v10.15.2
* Operating System: windows 10 
* Protractor || WebDriverIO || Nightmare version (if related): protractor
* Configuration file:

```js
exports.config = {
  tests: '../Test_Scripts/test.js',
  output: '../output',
  helpers: {
    Protractor: {
      url: 'http://localhost.topicus.nl:8080/',
      // driver: 'direct',
      browser: 'chrome',
      rootElement: false,
      angular: false,
      capabilities: {
        chromeOptions: {
          args: ["start-maximized"]
        }
      },
      // directConnect: true,

    }
  },
  include: {
    I: "../Common/Utilities.js",
  },  
  bootstrap: null,
  mocha: {},
  name: 'codeCept_Automation'
}

**Comment by philqa** [comment]
+1

**Comment by karunandrii** [comment]
+1
any news about this?

**Comment by LukoyanovE** [comment]
Not sure there are problem in codecept, can anybody to provide example, where it does not work?

I am use awaits and it works

**Comment by sudeepsarkar2017** [comment]
The issue is with es6,  it's working fine with es2017 and above

**Comment by bokas5** [comment]
Not sure I'm following here. How to make this work? Can someone write an example?
