### ISSUE TITLE
Unable to use UIAutomator2

### ISSUE THREAD

**Issue by ichanmrg** [codeceptjs/CodeceptJS#1594]
#### What are you trying to achieve?
Use the UiAutomator2 as the desiredCapability of the Appium helper. Only way to see elements after a certain pop-up is to use UiAutomator2. Somewhat related to [this issue.](https://github.com/appium/appium/issues/7806)

#### What do you get instead?

> Provide console output if related. Use `--verbose` mode for more details.

```bash
# paste output here
  1) GC: 4 Players 5 Ways Hole 1 Start
       Create 4 Players 5 Ways Hole 1 Start match.:
     An unknown server-side error occurred while processing the command. Original error: Could not proxy. Proxy error: Could not proxy command to remote server. Original error: 404 - undefined
  
  Scenario Steps:
  
  - I.click("//*[contains(@text,"Create Match")]") at Object.createMatch (steps_file.js:45:12)
  
  unknown error: An unknown server-side error occurred while processing the command. Original error: Could not proxy. Proxy error: Could not proxy command to remote server. Original error: 404 - undefined
      at getErrorFromResponseBody (/usr/local/lib/node_modules/webdriverio/node_modules/webdriver/build/utils.js:343:10)
      at Request._callback (/usr/local/lib/node_modules/webdriverio/node_modules/webdriver/build/request.js:121:64)
      at Request.self.callback (/usr/local/lib/node_modules/webdriverio/node_modules/request/request.js:185:22)
      at Request.EventEmitter.emit (domain.js:441:20)
      at Request.<anonymous> (/usr/local/lib/node_modules/webdriverio/node_modules/request/request.js:1161:10)
      at Request.EventEmitter.emit (domain.js:441:20)
      at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/webdriverio/node_modules/request/request.js:1083:12)


  FAIL  | 0 passed, 1 failed   // 33s
    Emitted | global.result ([object Object])
    Emitted | global.after ([object Object])
```

> Provide test source code if related

```js
// paste test
I.click('//*[contains(@text,"Create Match")]');
```

### Details

* CodeceptJS version: 2.0.8
* NodeJS Version: 10.15.3
* Operating System: macOS 10.14.4
* Protractor || WebDriverIO || Nightmare version (if related)
* Configuration file:

```js
# paste suite config here
{
  "tests": "./tests/*_test/*_test.js",
  "timeout": 10000,
  "plugins": {
    "allure": {
      "enabled": true
    },
    "retryFailedStep": {
      "enabled": true
    },
     "screenshotOnFail": {
       "enabled": true
    },
    "autoDelay": {
      "enabled": true
    }
  },
  "output": "./output",
  "helpers": {
    "Appium": {
      "smartWait": 240000,
      "restart": true,
      "app": "/app/loc/app.apk",
      "platform": "Android",
      "version": "ANY",
      "device": "Samsung Galaxy S8",
      "host": "localhost",
      "port": 4723,
      "desiredCapabilities": {
        "automationName": "uiautomator2"
      }
    }
  },
  "include": {
    "I": "./steps_file.js"
  },
  "mocha": {
    "reporterOptions": {
      "codeceptjs-cli-reporter": {
        "stdout": "-",
        "options": {
          "verbose": false,
          "steps": true
        }
      },
      "mochawesome": {
        "stdout": "./output/console.log",
        "uniqueScreenshotNames": "true",
        "options": {
          "reportDir": "./output",
          "reportFilename": "report"
        }
      },
      "mocha-junit-reporter": {
        "stdout": "-",
        "options": {
          "mochaFile": "./output/report-as-junit.xml"
        }
      }
    }
  },
  "bootstrap": false,
  "name": "GC"
}
```

**Comment by eduardofinotti** [comment]
Yes, I had the same problem here and when I used the UIAutomator2 it worked. But to emulator device the problem doesn't happen, just to real device android.
