### ISSUE TITLE
Cannot read property 'emit' of undefined

### ISSUE THREAD

**Issue by karunandrii** [codeceptjs/CodeceptJS#1696]
#### What are you trying to achieve?
I'm using typescript with nightmare helper, run with ts-node. Using async/await in tests. Tell me if you need more info.  
#### What do you get instead?

> Provide console output if related. Use `--verbose` mode for more details.

```bash
#     
Emitted | test.passed ([object Object])
    Error processing test.passed event:
    TypeError: Cannot read property 'emit' of undefined
    at EventEmitter.event.dispatcher.on (\node_modules\codeceptjs\lib\listener\mocha.js:14:18)
    at EventEmitter.emit (events.js:194:15)
    at EventEmitter.emit (domain.js:441:20)
    at Object.emit (\node_modules\codeceptjs\lib\event.js:49:28)
    at recorder.add (\node_modules\codeceptjs\lib\scenario.js:58:17)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    Emitted | test.finish ([object Object])
  √ OK in 97305ms

    Emitted | step.start (I wait for text (''))
      I wait for text ('')
    Emitted | test.after ([object Object])
    Emitted | step.passed (I wait for text (''))
    Emitted | step.finish (I wait for text (''))
    Emitted | step.start (I wait 1)
    I wait 1
    Emitted | step.passed (I wait 1)
    Emitted | step.finish (I wait 1)
    Emitted | step.start (I dont see element present "")
      I dont see element present ""
    Emitted | step.passed (I dont see element present "")
    Emitted | step.finish (I dont see element present "")
    Emitted | step.start (I see checkbox is checked "")
      I see checkbox is checked ""
    Emitted | step.passed (I see checkbox is checked "")
    Emitted | step.finish (I see checkbox is checked "")
    Emitted | step.start (I wait 1)
    I wait 1
    Emitted | step.passed (I wait 1)
    Emitted | step.finish (I wait 1)
    Emitted | suite.after ([object Object])
```

> Provide test source code if related

```js
// 
Scenario('Test', async (I) => {
    ....

    await po.some(); -> promise
    await po.some(); -> promise
    await po.some(); -> promise
    await po.some(); -> promise
    po.some(); - void
    po.some(); - void
});
```

### Details

* CodeceptJS version: v2.1.3
* NodeJS Version: v10.15.1
* Operating System: Win10
* Nightmare: v3.0.1
* Configuration file:

```js
# 
        Nightmare: {
            url: url,
            show: false,
            openDevTools: false,
            waitForTimeout: 90000,
            windowSize: "1920x1080",
            typeInterval: 50,
            pollInterval: 50,
            webPreferences: {
                partition: 'nopersist'
            }
        },
mocha: {
        reporterOptions: {
            "codeceptjs-cli-reporter": {
                stdout: "-",
                options: {
                    verbose: false,
                    steps: false,
                    debug: true
                }
            },
            "mocha-junit-reporter": {
                stdout: "-",
                options: {
                    mochaFile: path.join(OUTPUT_DIR, 'test_result.xml')
                }
            },
            "mochawesome": {
                stdout: "-",
                options: {
                    reportDir: path.join(OUTPUT_DIR, 'htmlReport'),
                    reportFilename: "report",
                    reportTitle: "Acceptance End-to-End Testing",
                    inlineAssets: true
                }
            }
        }
    },
require: ["nightmare-download-manager"],
```

**Comment by VikalpP** [comment]
Can you provide this issue reproduction example?🙂
