### ISSUE TITLE
Appium Helper: 'smartWait' is not work with fillField

### ISSUE THREAD

**Issue by hoang-pham** [codeceptjs/CodeceptJS#1780]
#### What are you trying to achieve?
I applied 'smartWait = 5000' when test on Android device but it not work with method 'fillField'. It just wait about 2555ms
#### What do you get instead?

> Provide console output if related. Use `--verbose` mode for more details.

```bash
smartWait --
    [1] Starting recording promises
    Emitted | suite.before ([object Object])
  smartWait
    Emitted | test.before ([object Object])
    Emitted | test.start ([object Object])
    Emitted | step.before (I fill field "HHHHH", "Display")
    Emitted | step.after (I fill field "HHHHH", "Display")
    Emitted | step.start (I fill field "HHHHH", "Display")
    I fill field "HHHHH", "Display"
    [1] Error | Error: Field "android=new UiSelector().text("HHHHH")" was not found by text|CSS|XPath
    Emitted | step.failed (I fill field "HHHHH", "Display")
    Emitted | step.finish (I fill field "HHHHH", "Display")
    [1] Error | Error: Field "android=new UiSelector().text("HHHHH")" was not found by text|CSS|XPath
    [1] Starting <teardown> session
    Emitted | test.failed ([object Object])
    Emitted | test.finish ([object Object])
    [1] <teardown> Stopping recording promises
 » <screenshotOnFail> Test failed, saving screenshot
 » Screenshot has been saved to E:\GondolaProject\codecept_project\output\smartWait.failed.png
  × FAILED in 2555ms

    [2] Starting recording promises
    Emitted | test.after ([object Object])
    Emitted | suite.after ([object Object])

-- FAILURES:

  1) smartWait
       smartWait:
     Field "android=new UiSelector().text("HHHHH")" was not found by text|CSS|XPath
  
  Scenario Steps:
  
  - I.fillField("HHHHH", "Display") at Test.Scenario (src\smartwait_test.js:4:7)
  
  Error: Field "android=new UiSelector().text("HHHHH")" was not found by text|CSS|XPath
      at new ElementNotFound (node_modules\codeceptjs\lib\helper\errors\ElementNotFound.js:14:11)
      at assertElementExists (node_modules\codeceptjs\lib\helper\WebDriver.js:2288:11)
      at Appium.fillField (node_modules\codeceptjs\lib\helper\WebDriver.js:779:5)
      at process._tickCallback (internal/process/next_tick.js:68:7)


  FAIL  | 0 passed, 1 failed   // 14s
    Emitted | global.result ([object Object])
    Emitted | global.after ([object Object])
```

> Provide test source code if related

```js
Feature("smartWait");

Scenario("smartWait", (I) => {
    I.fillField("HHHHH", "Display");
});
```

### Details

* CodeceptJS version: 2.2.0
* NodeJS Version: v10.16.0
* Operating System: Window 10 
* Protractor || WebDriverIO || Nightmare version (if related)
* Configuration file:

```js
   Appium: {
      platform: 'Android',
      device: 'emulator',
      smartWait: 5000,
      desiredCapabilities: {
        appPackage: "com.android.settings",
        appActivity: ".Settings",
      }
    }
```

**Comment by xMutaGenx** [comment]
This is working correctly, as per documentation https://codecept.io/acceptance#smartwait you need to have a strict or more specific locator and fuzzy locator of `"Display"` will not work.
```
I.fillField('user', 'davert'); // DISABLED, not a specific locator
I.fillField({name: 'password'}, '123456'); // ENABLED, strict locator
```

Hope this helps.
