### ISSUE TITLE
Errors thrown when initialising codeceptJS with Appium

### ISSUE THREAD

**Issue by GSasu** [codeceptjs/CodeceptJS#1991]
Initialised a new appium based project with codeceptjs and after answering all prompts, a list of errors was thrown.

node - 12.11.0
npm - 6.12.0
codecept - v2.3.5
appium - 1.15.1

Output:
```js
./node_modules/.bin/codeceptjs init     

  Welcome to CodeceptJS initialization tool
  It will prepare and configure a test environment for you

Installing to /Users/gabe/Development/mobile-app/test-service
? Where are your tests located? ./*_test.js
? What helpers do you want to use? Appium
? Where should logs, screenshots, and reports to be stored? ./output
? Would you like to extend the "I" object with custom steps? Yes
? Where would you like to place custom steps? ./steps_file.js
? Do you want to choose localization for tests? English (no localization)
Configure helpers...
? [Appium] Application package. Path to file or url http://localhost
? [Appium] Mobile Platform iOS
? [Appium] Device to run tests on emulator

Steps file created at /Users/gabe/Development/mobile-app/test-service/steps_file.js
Config created at /Users/gabe/Development/mobile-app/test-service/codecept.conf.js
Directory for temporary output files created at './output'
Intellisense enabled in /Users/gabe/Development/mobile-app/test-service/jsconfig.json
Error in async function appendField(field, value) {
    if (this.isWeb) return super.appendField(field, value);
    return super.appendField(parseLocator.call(this, field), value);
  }
{ SyntaxError: super is only allowed in object methods and classes (2:27)
    at Parser.raise (/Users/gabe/Development/mobile-app/test-service/node_modules/babylon/lib/index.js:776:15)
    at Parser.parseExprAtom (/Users/gabe/Development/mobile-app/test-service/node_modules/babylon/lib/index.js:2993:16)
    at Parser.parseExprSubscripts (/Users/gabe/Development/mobile-app/test-service/node_modules/babylon/lib/index.js:2757:21)
    at Parser.parseMaybeUnary (/Users/gabe/Development/mobile-app/test-service/node_modules/babylon/lib/index.js:2736:21)
    at Parser.parseExprOps (/Users/gabe/Development/mobile-app/test-service/node_modules/babylon/lib/index.js:2643:21)
    at Parser.parseMaybeConditional (/Users/gabe/Development/mobile-app/test-service/node_modules/babylon/lib/index.js:2615:21)
    at Parser.parseMaybeAssign (/Users/gabe/Development/mobile-app/test-service/node_modules/babylon/lib/index.js:2562:21)
    at Parser.parseExpression (/Users/gabe/Development/mobile-app/test-service/node_modules/babylon/lib/index.js:2515:21)
    at Parser.parseReturnStatement (/Users/gabe/Development/mobile-app/test-service/node_modules/babylon/lib/index.js:4314:28)
    at Parser.parseStatementContent (/Users/gabe/Development/mobile-app/test-service/node_modules/babylon/lib/index.js:3996:21) pos: 70, loc: Position { line: 2, column: 27 } }
Error in async function checkOption(field) {
    if (this.isWeb) return super.checkOption(field);
    return super.checkOption(parseLocator.call(this, field));
  }
{ SyntaxError: super is only allowed in object methods and classes (2:27)
    at Parser.raise (/Users/gabe/Development/mobile-app/test-service/node_modules/babylon/lib/index.js:776:15)
    at Parser.parseExprAtom (/Users/gabe/Development/mobile-app/test-service/node_modules/babylon/lib/index.js:2993:16)
    at Parser.parseExprSubscripts (/Users/gabe/Development/mobile-app/test-service/node_modules/babylon/lib/index.js:2757:21)
    at Parser.parseMaybeUnary (/Users/gabe/Development/mobile-app/test-service/node_modules/babylon/lib/index.js:2736:21)
    at Parser.parseExprOps (/Users/gabe/Development/mobile-app/test-service/node_modules/babylon/lib/index.js:2643:21)
    at Parser.parseMaybeConditional (/Users/gabe/Development/mobile-app/test-service/node_modules/babylon/lib/index.js:2615:21)
    at Parser.parseMaybeAssign (/Users/gabe/Development/mobile-app/test-service/node_modules/babylon/lib/index.js:2562:21)
    at Parser.parseExpression (/Users/gabe/Development/mobile-app/test-service/node_modules/babylon/lib/index.js:2515:21)
    at Parser.parseReturnStatement (/Users/gabe/Development/mobile-app/test-service/node_modules/babylon/lib/index.js:4314:28)
    at Parser.parseStatementContent (/Users/gabe/Development/mobile-app/test-service/node_modules/babylon/lib/index.js:3996:21) pos: 63, loc: Position { line: 2, column: 27 } }
Error in async function click(locator, context) {
    if (this.isWeb) return super.click(locator, context);
    return super.click(parseLocator.call(this, locator), parseLocator.call(this, context));
  }
{ SyntaxError: super is only allowed in object methods and classes (2:27)
    at Parser.raise (/Users/gabe/Development/mobile-app/test-service/node_modules/babylon/lib/index.js:776:15)
    at Parser.parseExprAtom (/Users/gabe/Development/mobile-app/test-service/node_modules/babylon/lib/index.js:2993:16)
    at Parser.parseExprSubscripts (/Users/gabe/Development/mobile-app/test-service/node_modules/babylon/lib/index.js:2757:21)
    at Parser.parseMaybeUnary (/Users/gabe/Development/mobile-app/test-service/node_modules/babylon/lib/index.js:2736:21)
    at Parser.parseExprOps (/Users/gabe/Development/mobile-app/test-service/node_modules/babylon/lib/index.js:2643:21)
    at Parser.parseMaybeConditional (/Users/gabe/Development/mobile-app/test-service/node_modules/babylon/lib/index.js:2615:21)
    at Parser.parseMaybeAssign (/Users/gabe/Development/mobile-app/test-service/node_modules/babylon/lib/index.js:2562:21)
    at Parser.parseExpression (/Users/gabe/Development/mobile-app/test-service/node_modules/babylon/lib/index.js:2515:21)
    at Parser.parseReturnStatement (/Users/gabe/Development/mobile-app/test-service/node_modules/babylon/lib/index.js:4314:28)
    at Parser.parseStatementContent (/Users/gabe/Development/mobile-app/test-service/node_modules/babylon/lib/index.js:3996:21) pos: 68, loc: Position { line: 2, column: 27 } }
Error in async function dontSeeCheckboxIsChecked(field) {
    if (this.isWeb) return super.dontSeeCheckboxIsChecked(field);
    return super.dontSeeCheckboxIsChecked(parseLocator.call(this, field));
  }
{ SyntaxError: super is only allowed in object methods and classes (2:27)
    at Parser.raise (/Users/gabe/Development/mobile-app/test-service/node_modules/babylon/lib/index.js:776:15)
    at Parser.parseExprAtom (/Users/gabe/Development/mobile-app/test-service/node_modules/babylon/lib/index.js:2993:16)
    at Parser.parseExprSubscripts (/Users/gabe/Development/mobile-app/test-service/node_modules/babylon/lib/index.js:2757:21)
    at Parser.parseMaybeUnary (/Users/gabe/Development/mobile-app/test-service/node_modules/babylon/lib/index.js:2736:21)
    at Parser.parseExprOps (/Users/gabe/Development/mobile-app/test-service/node_modules/babylon/lib/index.js:2643:21)
    at Parser.parseMaybeConditional (/Users/gabe/Development/mobile-app/test-service/node_modules/babylon/lib/index.js:2615:21)
    at Parser.parseMaybeAssign (/Users/gabe/Development/mobile-app/test-service/node_modules/babylon/lib/index.js:2562:21)
    at Parser.parseExpression (/Users/gabe/Development/mobile-app/test-service/node_modules/babylon/lib/index.js:2515:21)
    at Parser.parseReturnStatement (/Users/gabe/Development/mobile-app/test-service/node_modules/babylon/lib/index.js:4314:28)
    at Parser.parseStatementContent (/Users/gabe/Development/mobile-app/test-service/node_modules/babylon/lib/index.js:3996:21) pos: 76, loc: Position { line: 2, column: 27 } }
Error in async function dontSeeElement(locator) {
    if (this.isWeb) return super.dontSeeElement(locator);
    return super.dontSeeElement(parseLocator.call(this, locator));
  }
{ SyntaxError: super is only allowed in object methods and classes (2:27)
    at Parser.raise (/Users/gabe/Development/mobile-app/test-service/node_modules/babylon/lib/index.js:776:15)
    at Parser.parseExprAtom (/Users/gabe/Development/mobile-app/test-service/node_modules/babylon/lib/index.js:2993:16)
    at Parser.parseExprSubscripts (/Users/gabe/Development/mobile-app/test-service/node_modules/babylon/lib/index.js:2757:21)
    at Parser.parseMaybeUnary (/Users/gabe/Development/mobile-app/test-service/node_modules/babylon/lib/index.js:2736:21)
    at Parser.parseExprOps (/Users/gabe/Development/mobile-app/test-service/node_modules/babylon/lib/index.js:2643:21)
    at Parser.parseMaybeConditional (/Users/gabe/Development/mobile-app/test-service/node_modules/babylon/lib/index.js:2615:21)
    at Parser.parseMaybeAssign (/Users/gabe/Development/mobile-app/test-service/node_modules/babylon/lib/index.js:2562:21)
    at Parser.parseExpression (/Users/gabe/Development/mobile-app/test-service/node_modules/babylon/lib/index.js:2515:21)
    at Parser.parseReturnStatement (/Users/gabe/Development/mobile-app/test-service/node_modules/babylon/lib/index.js:4314:28)
    at Parser.parseStatementContent (/Users/gabe/Development/mobile-app/test-service/node_modules/babylon/lib/index.js:3996:21) pos: 68, loc: Position { line: 2, column: 27 } }
Error in async function dontSeeInField(field, value) {
    if (this.isWeb) return super.dontSeeInField(field, value);
    return super.dontSeeInField(parseLocator.call(this, field), value);
  }
{ SyntaxError: super is only allowed in object methods and classes (2:27)
    at Parser.raise (/Users/gabe/Development/mobile-app/test-service/node_modules/babylon/lib/index.js:776:15)
    at Parser.parseExprAtom (/Users/gabe/Development/mobile-app/test-service/node_modules/babylon/lib/index.js:2993:16)
    at Parser.parseExprSubscripts (/Users/gabe/Development/mobile-app/test-service/node_modules/babylon/lib/index.js:2757:21)
    at Parser.parseMaybeUnary (/Users/gabe/Development/mobile-app/test-service/node_modules/babylon/lib/index.js:2736:21)
    at Parser.parseExprOps (/Users/gabe/Development/mobile-app/test-service/node_modules/babylon/lib/index.js:2643:21)
    at Parser.parseMaybeConditional (/Users/gabe/Development/mobile-app/test-service/node_modules/babylon/lib/index.js:2615:21)
    at Parser.parseMaybeAssign (/Users/gabe/Development/mobile-app/test-service/node_modules/babylon/lib/index.js:2562:21)
    at Parser.parseExpression (/Users/gabe/Development/mobile-app/test-service/node_modules/babylon/lib/index.js:2515:21)
    at Parser.parseReturnStatement (/Users/gabe/Development/mobile-app/test-service/node_modules/babylon/lib/index.js:4314:28)
    at Parser.parseStatementContent (/Users/gabe/Development/mobile-app/test-service/node_modules/babylon/lib/index.js:3996:21) pos: 73, loc: Position { line: 2, column: 27 } }
Error in async function dontSee(text, context = null) {
    if (this.isWeb) return super.dontSee(text, context);
    return super.dontSee(text, parseLocator.call(this, context));
  }
{ SyntaxError: super is only allowed in object methods and classes (2:27)
    at Parser.raise (/Users/gabe/Development/mobile-app/test-service/node_modules/babylon/lib/index.js:776:15)
    at Parser.parseExprAtom (/Users/gabe/Development/mobile-app/test-service/node_modules/babylon/lib/index.js:2993:16)
    at Parser.parseExprSubscripts (/Users/gabe/Development/mobile-app/test-service/node_modules/babylon/lib/index.js:2757:21)
    at Parser.parseMaybeUnary (/Users/gabe/Development/mobile-app/test-service/node_modules/babylon/lib/index.js:2736:21)
    at Parser.parseExprOps (/Users/gabe/Development/mobile-app/test-service/node_modules/babylon/lib/index.js:2643:21)
    at Parser.parseMaybeConditional (/Users/gabe/Development/mobile-app/test-service/node_modules/babylon/lib/index.js:2615:21)
    at Parser.parseMaybeAssign (/Users/gabe/Development/mobile-app/test-service/node_modules/babylon/lib/index.js:2562:21)
    at Parser.parseExpression (/Users/gabe/Development/mobile-app/test-service/node_modules/babylon/lib/index.js:2515:21)
    at Parser.parseReturnStatement (/Users/gabe/Development/mobile-app/test-service/node_modules/babylon/lib/index.js:4314:28)
    at Parser.parseStatementContent (/Users/gabe/Development/mobile-app/test-service/node_modules/babylon/lib/index.js:3996:21) pos: 74, loc: Position { line: 2, column: 27 } }
Error in async function fillField(field, value) {
    value = value.toString();
    if (this.isWeb) return super.fillField(field, value);
    return super.fillField(parseLocator.call(this, field), value);
  }
{ SyntaxError: super is only allowed in object methods and classes (3:27)
    at Parser.raise (/Users/gabe/Development/mobile-app/test-service/node_modules/babylon/lib/index.js:776:15)
    at Parser.parseExprAtom (/Users/gabe/Development/mobile-app/test-service/node_modules/babylon/lib/index.js:2993:16)
    at Parser.parseExprSubscripts (/Users/gabe/Development/mobile-app/test-service/node_modules/babylon/lib/index.js:2757:21)
    at Parser.parseMaybeUnary (/Users/gabe/Development/mobile-app/test-service/node_modules/babylon/lib/index.js:2736:21)
    at Parser.parseExprOps (/Users/gabe/Development/mobile-app/test-service/node_modules/babylon/lib/index.js:2643:21)
    at Parser.parseMaybeConditional (/Users/gabe/Development/mobile-app/test-service/node_modules/babylon/lib/index.js:2615:21)
    at Parser.parseMaybeAssign (/Users/gabe/Development/mobile-app/test-service/node_modules/babylon/lib/index.js:2562:21)
    at Parser.parseExpression (/Users/gabe/Development/mobile-app/test-service/node_modules/babylon/lib/index.js:2515:21)
    at Parser.parseReturnStatement (/Users/gabe/Development/mobile-app/test-service/node_modules/babylon/lib/index.js:4314:28)
    at Parser.parseStatementContent (/Users/gabe/Development/mobile-app/test-service/node_modules/babylon/lib/index.js:3996:21) pos: 98, loc: Position { line: 3, column: 27 } }
Error in async function grabTextFrom(locator) {
    if (this.isWeb) return super.grabTextFrom(locator);
    return super.grabTextFrom(parseLocator.call(this, locator));
  }
{ SyntaxError: super is only allowed in object methods and classes (2:27)
    at Parser.raise (/Users/gabe/Development/mobile-app/test-service/node_modules/babylon/lib/index.js:776:15)
    at Parser.parseExprAtom (/Users/gabe/Development/mobile-app/test-service/node_modules/babylon/lib/index.js:2993:16)
    at Parser.parseExprSubscripts (/Users/gabe/Development/mobile-app/test-service/node_modules/babylon/lib/index.js:2757:21)
    at Parser.parseMaybeUnary (/Users/gabe/Development/mobile-app/test-service/node_modules/babylon/lib/index.js:2736:21)
    at Parser.parseExprOps (/Users/gabe/Development/mobile-app/test-service/node_modules/babylon/lib/index.js:2643:21)
    at Parser.parseMaybeConditional (/Users/gabe/Development/mobile-app/test-service/node_modules/babylon/lib/index.js:2615:21)
    at Parser.parseMaybeAssign (/Users/gabe/Development/mobile-app/test-service/node_modules/babylon/lib/index.js:2562:21)
    at Parser.parseExpression (/Users/gabe/Development/mobile-app/test-service/node_modules/babylon/lib/index.js:2515:21)
    at Parser.parseReturnStatement (/Users/gabe/Development/mobile-app/test-service/node_modules/babylon/lib/index.js:4314:28)
    at Parser.parseStatementContent (/Users/gabe/Development/mobile-app/test-service/node_modules/babylon/lib/index.js:3996:21) pos: 66, loc: Position { line: 2, column: 27 } }
Error in async function grabValueFrom(locator) {
    if (this.isWeb) return super.grabValueFrom(locator);
    return super.grabValueFrom(parseLocator.call(this, locator));
  }
{ SyntaxError: super is only allowed in object methods and classes (2:27)
    at Parser.raise (/Users/gabe/Development/mobile-app/test-service/node_modules/babylon/lib/index.js:776:15)
    at Parser.parseExprAtom (/Users/gabe/Development/mobile-app/test-service/node_modules/babylon/lib/index.js:2993:16)
    at Parser.parseExprSubscripts (/Users/gabe/Development/mobile-app/test-service/node_modules/babylon/lib/index.js:2757:21)
    at Parser.parseMaybeUnary (/Users/gabe/Development/mobile-app/test-service/node_modules/babylon/lib/index.js:2736:21)
    at Parser.parseExprOps (/Users/gabe/Development/mobile-app/test-service/node_modules/babylon/lib/index.js:2643:21)
    at Parser.parseMaybeConditional (/Users/gabe/Development/mobile-app/test-service/node_modules/babylon/lib/index.js:2615:21)
    at Parser.parseMaybeAssign (/Users/gabe/Development/mobile-app/test-service/node_modules/babylon/lib/index.js:2562:21)
    at Parser.parseExpression (/Users/gabe/Development/mobile-app/test-service/node_modules/babylon/lib/index.js:2515:21)
    at Parser.parseReturnStatement (/Users/gabe/Development/mobile-app/test-service/node_modules/babylon/lib/index.js:4314:28)
    at Parser.parseStatementContent (/Users/gabe/Development/mobile-app/test-service/node_modules/babylon/lib/index.js:3996:21) pos: 67, loc: Position { line: 2, column: 27 } }
Error in async function seeCheckboxIsChecked(field) {
    if (this.isWeb) return super.seeCheckboxIsChecked(field);
    return super.seeCheckboxIsChecked(parseLocator.call(this, field));
  }
{ SyntaxError: super is only allowed in object methods and classes (2:27)
    at Parser.raise (/Users/gabe/Development/mobile-app/test-service/node_modules/babylon/lib/index.js:776:15)
    at Parser.parseExprAtom (/Users/gabe/Development/mobile-app/test-service/node_modules/babylon/lib/index.js:2993:16)
    at Parser.parseExprSubscripts (/Users/gabe/Development/mobile-app/test-service/node_modules/babylon/lib/index.js:2757:21)
    at Parser.parseMaybeUnary (/Users/gabe/Development/mobile-app/test-service/node_modules/babylon/lib/index.js:2736:21)
    at Parser.parseExprOps (/Users/gabe/Development/mobile-app/test-service/node_modules/babylon/lib/index.js:2643:21)
    at Parser.parseMaybeConditional (/Users/gabe/Development/mobile-app/test-service/node_modules/babylon/lib/index.js:2615:21)
    at Parser.parseMaybeAssign (/Users/gabe/Development/mobile-app/test-service/node_modules/babylon/lib/index.js:2562:21)
    at Parser.parseExpression (/Users/gabe/Development/mobile-app/test-service/node_modules/babylon/lib/index.js:2515:21)
    at Parser.parseReturnStatement (/Users/gabe/Development/mobile-app/test-service/node_modules/babylon/lib/index.js:4314:28)
    at Parser.parseStatementContent (/Users/gabe/Development/mobile-app/test-service/node_modules/babylon/lib/index.js:3996:21) pos: 72, loc: Position { line: 2, column: 27 } }
Error in async function seeElement(locator) {
    if (this.isWeb) return super.seeElement(locator);
    return super.seeElement(parseLocator.call(this, locator));
  }
{ SyntaxError: super is only allowed in object methods and classes (2:27)
    at Parser.raise (/Users/gabe/Development/mobile-app/test-service/node_modules/babylon/lib/index.js:776:15)
    at Parser.parseExprAtom (/Users/gabe/Development/mobile-app/test-service/node_modules/babylon/lib/index.js:2993:16)
    at Parser.parseExprSubscripts (/Users/gabe/Development/mobile-app/test-service/node_modules/babylon/lib/index.js:2757:21)
    at Parser.parseMaybeUnary (/Users/gabe/Development/mobile-app/test-service/node_modules/babylon/lib/index.js:2736:21)
    at Parser.parseExprOps (/Users/gabe/Development/mobile-app/test-service/node_modules/babylon/lib/index.js:2643:21)
    at Parser.parseMaybeConditional (/Users/gabe/Development/mobile-app/test-service/node_modules/babylon/lib/index.js:2615:21)
    at Parser.parseMaybeAssign (/Users/gabe/Development/mobile-app/test-service/node_modules/babylon/lib/index.js:2562:21)
    at Parser.parseExpression (/Users/gabe/Development/mobile-app/test-service/node_modules/babylon/lib/index.js:2515:21)
    at Parser.parseReturnStatement (/Users/gabe/Development/mobile-app/test-service/node_modules/babylon/lib/index.js:4314:28)
    at Parser.parseStatementContent (/Users/gabe/Development/mobile-app/test-service/node_modules/babylon/lib/index.js:3996:21) pos: 64, loc: Position { line: 2, column: 27 } }
Error in async function seeInField(field, value) {
    if (this.isWeb) return super.seeInField(field, value);
    return super.seeInField(parseLocator.call(this, field), value);
  }
{ SyntaxError: super is only allowed in object methods and classes (2:27)
    at Parser.raise (/Users/gabe/Development/mobile-app/test-service/node_modules/babylon/lib/index.js:776:15)
    at Parser.parseExprAtom (/Users/gabe/Development/mobile-app/test-service/node_modules/babylon/lib/index.js:2993:16)
    at Parser.parseExprSubscripts (/Users/gabe/Development/mobile-app/test-service/node_modules/babylon/lib/index.js:2757:21)
    at Parser.parseMaybeUnary (/Users/gabe/Development/mobile-app/test-service/node_modules/babylon/lib/index.js:2736:21)
    at Parser.parseExprOps (/Users/gabe/Development/mobile-app/test-service/node_modules/babylon/lib/index.js:2643:21)
    at Parser.parseMaybeConditional (/Users/gabe/Development/mobile-app/test-service/node_modules/babylon/lib/index.js:2615:21)
    at Parser.parseMaybeAssign (/Users/gabe/Development/mobile-app/test-service/node_modules/babylon/lib/index.js:2562:21)
    at Parser.parseExpression (/Users/gabe/Development/mobile-app/test-service/node_modules/babylon/lib/index.js:2515:21)
    at Parser.parseReturnStatement (/Users/gabe/Development/mobile-app/test-service/node_modules/babylon/lib/index.js:4314:28)
    at Parser.parseStatementContent (/Users/gabe/Development/mobile-app/test-service/node_modules/babylon/lib/index.js:3996:21) pos: 69, loc: Position { line: 2, column: 27 } }
Error in async function see(text, context) {
    if (this.isWeb) return super.see(text, context);
    return super.see(text, parseLocator.call(this, context));
  }
{ SyntaxError: super is only allowed in object methods and classes (2:27)
    at Parser.raise (/Users/gabe/Development/mobile-app/test-service/node_modules/babylon/lib/index.js:776:15)
    at Parser.parseExprAtom (/Users/gabe/Development/mobile-app/test-service/node_modules/babylon/lib/index.js:2993:16)
    at Parser.parseExprSubscripts (/Users/gabe/Development/mobile-app/test-service/node_modules/babylon/lib/index.js:2757:21)
    at Parser.parseMaybeUnary (/Users/gabe/Development/mobile-app/test-service/node_modules/babylon/lib/index.js:2736:21)
    at Parser.parseExprOps (/Users/gabe/Development/mobile-app/test-service/node_modules/babylon/lib/index.js:2643:21)
    at Parser.parseMaybeConditional (/Users/gabe/Development/mobile-app/test-service/node_modules/babylon/lib/index.js:2615:21)
    at Parser.parseMaybeAssign (/Users/gabe/Development/mobile-app/test-service/node_modules/babylon/lib/index.js:2562:21)
    at Parser.parseExpression (/Users/gabe/Development/mobile-app/test-service/node_modules/babylon/lib/index.js:2515:21)
    at Parser.parseReturnStatement (/Users/gabe/Development/mobile-app/test-service/node_modules/babylon/lib/index.js:4314:28)
    at Parser.parseStatementContent (/Users/gabe/Development/mobile-app/test-service/node_modules/babylon/lib/index.js:3996:21) pos: 63, loc: Position { line: 2, column: 27 } }
Error in async function selectOption(select, option) {
    if (this.isWeb) return super.selectOption(select, option);
    throw new Error('Should be used only in Web context. In native context use \'click\' method instead');
  }
{ SyntaxError: super is only allowed in object methods and classes (2:27)
    at Parser.raise (/Users/gabe/Development/mobile-app/test-service/node_modules/babylon/lib/index.js:776:15)
    at Parser.parseExprAtom (/Users/gabe/Development/mobile-app/test-service/node_modules/babylon/lib/index.js:2993:16)
    at Parser.parseExprSubscripts (/Users/gabe/Development/mobile-app/test-service/node_modules/babylon/lib/index.js:2757:21)
    at Parser.parseMaybeUnary (/Users/gabe/Development/mobile-app/test-service/node_modules/babylon/lib/index.js:2736:21)
    at Parser.parseExprOps (/Users/gabe/Development/mobile-app/test-service/node_modules/babylon/lib/index.js:2643:21)
    at Parser.parseMaybeConditional (/Users/gabe/Development/mobile-app/test-service/node_modules/babylon/lib/index.js:2615:21)
    at Parser.parseMaybeAssign (/Users/gabe/Development/mobile-app/test-service/node_modules/babylon/lib/index.js:2562:21)
    at Parser.parseExpression (/Users/gabe/Development/mobile-app/test-service/node_modules/babylon/lib/index.js:2515:21)
    at Parser.parseReturnStatement (/Users/gabe/Development/mobile-app/test-service/node_modules/babylon/lib/index.js:4314:28)
    at Parser.parseStatementContent (/Users/gabe/Development/mobile-app/test-service/node_modules/babylon/lib/index.js:3996:21) pos: 73, loc: Position { line: 2, column: 27 } }
Error in async function waitForElement(locator, sec = null) {
    if (this.isWeb) return super.waitForElement(locator, sec);
    return super.waitForElement(parseLocator.call(this, locator), sec);
  }
{ SyntaxError: super is only allowed in object methods and classes (2:27)
    at Parser.raise (/Users/gabe/Development/mobile-app/test-service/node_modules/babylon/lib/index.js:776:15)
    at Parser.parseExprAtom (/Users/gabe/Development/mobile-app/test-service/node_modules/babylon/lib/index.js:2993:16)
    at Parser.parseExprSubscripts (/Users/gabe/Development/mobile-app/test-service/node_modules/babylon/lib/index.js:2757:21)
    at Parser.parseMaybeUnary (/Users/gabe/Development/mobile-app/test-service/node_modules/babylon/lib/index.js:2736:21)
    at Parser.parseExprOps (/Users/gabe/Development/mobile-app/test-service/node_modules/babylon/lib/index.js:2643:21)
    at Parser.parseMaybeConditional (/Users/gabe/Development/mobile-app/test-service/node_modules/babylon/lib/index.js:2615:21)
    at Parser.parseMaybeAssign (/Users/gabe/Development/mobile-app/test-service/node_modules/babylon/lib/index.js:2562:21)
    at Parser.parseExpression (/Users/gabe/Development/mobile-app/test-service/node_modules/babylon/lib/index.js:2515:21)
    at Parser.parseReturnStatement (/Users/gabe/Development/mobile-app/test-service/node_modules/babylon/lib/index.js:4314:28)
    at Parser.parseStatementContent (/Users/gabe/Development/mobile-app/test-service/node_modules/babylon/lib/index.js:3996:21) pos: 80, loc: Position { line: 2, column: 27 } }
Error in async function waitForVisible(locator, sec = null) {
    if (this.isWeb) return super.waitForVisible(locator, sec);
    return super.waitForVisible(parseLocator.call(this, locator), sec);
  }
{ SyntaxError: super is only allowed in object methods and classes (2:27)
    at Parser.raise (/Users/gabe/Development/mobile-app/test-service/node_modules/babylon/lib/index.js:776:15)
    at Parser.parseExprAtom (/Users/gabe/Development/mobile-app/test-service/node_modules/babylon/lib/index.js:2993:16)
    at Parser.parseExprSubscripts (/Users/gabe/Development/mobile-app/test-service/node_modules/babylon/lib/index.js:2757:21)
    at Parser.parseMaybeUnary (/Users/gabe/Development/mobile-app/test-service/node_modules/babylon/lib/index.js:2736:21)
    at Parser.parseExprOps (/Users/gabe/Development/mobile-app/test-service/node_modules/babylon/lib/index.js:2643:21)
    at Parser.parseMaybeConditional (/Users/gabe/Development/mobile-app/test-service/node_modules/babylon/lib/index.js:2615:21)
    at Parser.parseMaybeAssign (/Users/gabe/Development/mobile-app/test-service/node_modules/babylon/lib/index.js:2562:21)
    at Parser.parseExpression (/Users/gabe/Development/mobile-app/test-service/node_modules/babylon/lib/index.js:2515:21)
    at Parser.parseReturnStatement (/Users/gabe/Development/mobile-app/test-service/node_modules/babylon/lib/index.js:4314:28)
    at Parser.parseStatementContent (/Users/gabe/Development/mobile-app/test-service/node_modules/babylon/lib/index.js:3996:21) pos: 80, loc: Position { line: 2, column: 27 } }
Error in async function waitForInvisible(locator, sec = null) {
    if (this.isWeb) return super.waitForInvisible(locator, sec);
    return super.waitForInvisible(parseLocator.call(this, locator), sec);
  }
{ SyntaxError: super is only allowed in object methods and classes (2:27)
    at Parser.raise (/Users/gabe/Development/mobile-app/test-service/node_modules/babylon/lib/index.js:776:15)
    at Parser.parseExprAtom (/Users/gabe/Development/mobile-app/test-service/node_modules/babylon/lib/index.js:2993:16)
    at Parser.parseExprSubscripts (/Users/gabe/Development/mobile-app/test-service/node_modules/babylon/lib/index.js:2757:21)
    at Parser.parseMaybeUnary (/Users/gabe/Development/mobile-app/test-service/node_modules/babylon/lib/index.js:2736:21)
    at Parser.parseExprOps (/Users/gabe/Development/mobile-app/test-service/node_modules/babylon/lib/index.js:2643:21)
    at Parser.parseMaybeConditional (/Users/gabe/Development/mobile-app/test-service/node_modules/babylon/lib/index.js:2615:21)
    at Parser.parseMaybeAssign (/Users/gabe/Development/mobile-app/test-service/node_modules/babylon/lib/index.js:2562:21)
    at Parser.parseExpression (/Users/gabe/Development/mobile-app/test-service/node_modules/babylon/lib/index.js:2515:21)
    at Parser.parseReturnStatement (/Users/gabe/Development/mobile-app/test-service/node_modules/babylon/lib/index.js:4314:28)
    at Parser.parseStatementContent (/Users/gabe/Development/mobile-app/test-service/node_modules/babylon/lib/index.js:3996:21) pos: 82, loc: Position { line: 2, column: 27 } }
Error in async function waitForText(text, sec = null, context = null) {
    if (this.isWeb) return super.waitForText(text, sec, context);
    return super.waitForText(text, sec, parseLocator.call(this, context));
  }
{ SyntaxError: super is only allowed in object methods and classes (2:27)
    at Parser.raise (/Users/gabe/Development/mobile-app/test-service/node_modules/babylon/lib/index.js:776:15)
    at Parser.parseExprAtom (/Users/gabe/Development/mobile-app/test-service/node_modules/babylon/lib/index.js:2993:16)
    at Parser.parseExprSubscripts (/Users/gabe/Development/mobile-app/test-service/node_modules/babylon/lib/index.js:2757:21)
    at Parser.parseMaybeUnary (/Users/gabe/Development/mobile-app/test-service/node_modules/babylon/lib/index.js:2736:21)
    at Parser.parseExprOps (/Users/gabe/Development/mobile-app/test-service/node_modules/babylon/lib/index.js:2643:21)
    at Parser.parseMaybeConditional (/Users/gabe/Development/mobile-app/test-service/node_modules/babylon/lib/index.js:2615:21)
    at Parser.parseMaybeAssign (/Users/gabe/Development/mobile-app/test-service/node_modules/babylon/lib/index.js:2562:21)
    at Parser.parseExpression (/Users/gabe/Development/mobile-app/test-service/node_modules/babylon/lib/index.js:2515:21)
    at Parser.parseReturnStatement (/Users/gabe/Development/mobile-app/test-service/node_modules/babylon/lib/index.js:4314:28)
    at Parser.parseStatementContent (/Users/gabe/Development/mobile-app/test-service/node_modules/babylon/lib/index.js:3996:21) pos: 90, loc: Position { line: 2, column: 27 } }
TypeScript Definitions provide autocompletion in Visual Studio Code and other IDEs
Definitions were generated in steps.d.ts

 Almost done! Next step:
 Create your first test by executing `npx codeceptjs gt` command 
```

Let me know if additional help or information is needed for this.

**Comment by mirao** [comment]
I can confirm the same issue when running `codeceptjs def` in a folder with my Appium tests. It doesn't happen in folder with WebDriver tests.

**Used SW:**

- NodeJS v10.16.3, CodeceptJS 2.3.3

**Comment by mirao** [comment]
> I can confirm the same issue when running codeceptjs def in a folder with my Appium tests. It doesn't happen in folder with WebDriver tests.

Not an issue for me anymore. I use `codeceptjs def` regularly with CodeceptJS 3.0.x, NodeJS 12, Appium 1.15 without any problem.
