### ISSUE TITLE
[Puppeteer] Private api _clickablePoint() doesn't exist

### ISSUE THREAD

**Issue by karunandrii** [codeceptjs/CodeceptJS#2244]
#### What are you trying to achieve?
Use **moveCursorTo()**

#### What do you get instead?
  TypeError: els[0]._clickablePoint is not a function
      at Puppeteer.moveCursorTo (node_modules\codeceptjs\lib\helper\Puppeteer.js:632:26)
      at processTicksAndRejections (internal/process/task_queues.js:94:5)

> Provide console output if related. Use `--verbose` mode for more details.

```bash
CodeceptJS v2.5.0
Helpers: REST, Puppeteer
Plugins: screenshotOnFail

@MoveCursorTo test --
    [1] Starting recording promises
    Emitted | suite.before ([object Object])
  test
    Emitted | test.before ([object Object])
    Emitted | hook.start ([object Object])
    Emitted | step.before (I am on page "https://codecept.io/")
    Emitted | step.after (I am on page "https://codecept.io/")
    Emitted | step.start (I am on page "https://codecept.io/")
    I am on page "https://codecept.io/"
    » [Url] https://codecept.io/
    Emitted | step.passed (I am on page "https://codecept.io/")
    Emitted | step.finish (I am on page "https://codecept.io/")
    Emitted | hook.passed ([object Object])
    Emitted | test.start ([object Object])
    Emitted | step.before (I wait for element "div.playwright-home")
    Emitted | step.after (I wait for element "div.playwright-home")
    Emitted | step.before (I move cursor to "div.playwright-home")
    Emitted | step.after (I move cursor to "div.playwright-home")
    Emitted | step.before (I click "div.playwright-home")
    Emitted | step.after (I click "div.playwright-home")
    Emitted | step.start (I wait for element "div.playwright-home")
    I wait for element "div.playwright-home"
    Emitted | step.passed (I wait for element "div.playwright-home")
    Emitted | step.finish (I wait for element "div.playwright-home")
    Emitted | step.start (I move cursor to "div.playwright-home")
    I move cursor to "div.playwright-home"
    [1] Error | TypeError: els[0]._clickablePoint is not a function
    Emitted | step.failed (I move cursor to "div.playwright-home")
    Emitted | step.finish (I move cursor to "div.playwright-home")
    [1] Error | TypeError: els[0]._clickablePoint is not a function
    Emitted | step.failed (I click "div.playwright-home")
    Emitted | step.finish (I click "div.playwright-home")
    [1] Error | TypeError: els[0]._clickablePoint is not a function
    [1] Starting <teardown> session
    Emitted | test.failed ([object Object])
    Emitted | test.finish ([object Object])
    [1] <teardown> Stopping recording promises
  × FAILED in 1443ms

    [2] Starting recording promises
    Emitted | test.after ([object Object])
    Emitted | suite.after ([object Object])

-- FAILURES:

  1) @MoveCursorTo test
       test:
     els[0]._clickablePoint is not a function

  TypeError: els[0]._clickablePoint is not a function
      at Puppeteer.moveCursorTo (node_modules\codeceptjs\lib\helper\Puppeteer.js:632:26)
      at processTicksAndRejections (internal/process/task_queues.js:94:5)
```

> Provide test source code if related

```js
Feature('@MoveCursorTo test');

Before(I => {
    I.amOnPage('https://codecept.io/');
});

Scenario('test', async I => {
    I.waitForElement('div.playwright-home');
    I.moveCursorTo('div.playwright-home');
    I.click('div.playwright-home');
});
```

### Details

* CodeceptJS version: 2.5.0
* NodeJS Version: 12.14.1
* Operating System: Win 10
* puppeteer
* Configuration file:

```js
Default for puppeteer.
```

**Comment by DavertMik** [comment]
Looks like Puppeteer has updated its API and we are using their internal method so this explains why a test fails. Any volunteer to fix this?

**Comment by idxn** [comment]
@DavertMik I still see the _clickablePoint in https://github.com/puppeteer/puppeteer/blob/master/lib/JSHandle.js

**Comment by suniljaiswal01** [comment]
@DavertMik  Anyone looking into this issue? If not, then i can check.

**Comment by terrisgit** [comment]
Is there an ETA when this fix will be on npm?
