### ISSUE TITLE
Session was terminated due to ORPHAN

### ISSUE THREAD

**Issue by storenth** [codeceptjs/CodeceptJS#2286]
#### What are you trying to achieve?
Fill a field with too long text string.
```javascript
I.fillField('Много слов и символов, более 5к+');
```
#### What do you get instead?
Recurrent cycle with `I.fillField()` loop, mean text continue fill with same text again and again while browser timeout reached.
> npx codeceptjs run --verbose` output:
```bash
    [1] Error | unknown error: java.net.ConnectException: Connection refused (Connection refused)
✖ FAILED in 119866ms
(node:6095) UnhandledPromiseRejectionWarning: unknown error: Session [a45131973530a1c29845754e40f9d25f] was terminated due to ORPHAN
    at getErrorFromResponseBody (/home/storenth/interfax/publishing-qa/webdriverio_ifx/node_modules/webdriver/build/utils.js:124:10)
    at Request._callback (/home/storenth/interfax/publishing-qa/webdriverio_ifx/node_modules/webdriver/build/request.js:111:64)
    at Request.self.callback (/home/storenth/interfax/publishing-qa/webdriverio_ifx/node_modules/request/request.js:185:22)
    at Request.emit (events.js:219:5)
    at Request.EventEmitter.emit (domain.js:482:12)
    at Request.<anonymous> (/home/storenth/interfax/publishing-qa/webdriverio_ifx/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:219:5)
    at Request.EventEmitter.emit (domain.js:482:12)
    at IncomingMessage.<anonymous> (/home/storenth/interfax/publishing-qa/webdriverio_ifx/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:308:28)
(node:6095) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:6095) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

> Provide test source code if related

```js
Scenario('e2e demo @mvc', async (I) => {
    I.amOnPage('/your/page');
    let writeNewsText = `Длинный текст 5к+ слов`;
    I.waitForVisible({ css: '[class=new-todo]'}, 15);
    I.fillField({ css: '[class=new-todo]'}, writeNewsText);
});
```

### Details

* CodeceptJS version: codeceptjs@2.5.0
* NodeJS Version: v13.3.0
* npm version: 6.13.4
* Operating System: Ubuntu Linux
* webdriverio@5.22.4
* Configuration file:
```js
WebDriver: {
      manualStart: false,
      url: process.env.CODECEPT_URL,
      host: process.env.SELENOID_HOST,
      port: parseInt(process.env.SELENOID_PORT),
      browser: 'chrome',
      desiredCapabilities: {
        selenoidOptions: {
          browserName: 'chrome',
          browserVersion: '75.0',
          enableVNC: true,
          enableLog: true,
          sessionTimeout: '7m'
        }
      },
      windowSize: 'maximize',
      waitForNavigation: [
        'load',
        'domcontentloaded',
        'networkidle0'
      ]
    }
```

**Comment by DavertMik** [comment]
Sorry, no ideas here
