### ISSUE TITLE
Getting error ECONNREFUSED while running in CirclCI.Appium+Codeceptjs+XCUITEST

### ISSUE THREAD

**Issue by vishalpaliwal1** [codeceptjs/CodeceptJS#2290]
#### What are you trying to achieve?

Trying to run a simple script in circleci with codeceptjs using appium and ios simulator..
Pre-starting Appium in background..

iOS Simulator+Appium+CodeceptJS into Circle CI : 

But getting connection refuse error.

appium logs:

https://gist.github.com/vishalpaliwal1/990802e2f29fec6bedd171664e764207

Checked with Appium ...their response:-

```
It's clearly visible from the log that the client terminates session creation connection after exactly 90 seconds even though the response has not been received. Please make sure you use the most recent client version and the HTTP timeouts are configured properly there.

Unfortunately, there is nothing more we could here from the server side.
Closed as not an issue.
```

#### What do you get instead?

```
> npx codeceptjs run --steps --verbose --config=./codecept.conf.js

creating output directory: /Users/distiller/cem-qa/cem-qa-mobile/output
CodeceptJS v2.5.0
Using test root "/Users/distiller/cem-qa/cem-qa-mobile"
Helpers: Appium
Plugins: screenshotOnFail, retryFailedStep

test user login --
    [1] Starting recording promises
    Emitted | suite.before ([object Object])
  test app installed and sign in to the APP
    Emitted | test.before ([object Object])
    Emitted | test.start ([object Object])
    Emitted | step.before (I run on android () => {
        I.seeAppIsInstalled("com.kaddra.cem.members.app.test");
        I.seeElement('//android.widget.TextView[@content-desc="Sign_in"]');
        I.tap('//android.widget.TextView[@content-desc="Sign_in"]');
      })
    Emitted | step.after (I run on android () => {
        I.seeAppIsInstalled("com.kaddra.cem.members.app.test");
        I.seeElement('//android.widget.TextView[@content-desc="Sign_in"]');
        I.tap('//android.widget.TextView[@content-desc="Sign_in"]');
      })
    Emitted | step.before (I run on i o s () => {
        I.seeElement('~SIGN IN');
        I.tap('~SIGN IN');
        I.fillField('~EMAIL', globals.username);
        I.fillField('~Password', globals.password);
        I.tap('~SIGN IN');
        I.seeElement('~MARKET_HEADER_TITLE');
        I.seeElement('~FOOTER_BUTTON_Profile');
      })
    Emitted | step.after (I run on i o s () => {
        I.seeElement('~SIGN IN');
        I.tap('~SIGN IN');
        I.fillField('~EMAIL', globals.username);
        I.fillField('~Password', globals.password);
        I.tap('~SIGN IN');
        I.seeElement('~MARKET_HEADER_TITLE');
        I.seeElement('~FOOTER_BUTTON_Profile');
      })
    Emitted | step.before (I close app )
    Emitted | step.after (I close app )
    Emitted | step.start (I run on android () => {
        I.seeAppIsInstalled("com.kaddra.cem.members.app.test");
        I.seeElement('//android.widget.TextView[@content-desc="Sign_in"]');
        I.tap('//android.widget.TextView[@content-desc="Sign_in"]');
      })
    I run on android () => {
        I.seeAppIsInstalled("com.kaddra.cem.members.app.test");
        I.seeElement('//android.widget.TextView[@content-desc="Sign_in"]');
        I.tap('//android.widget.TextView[@content-desc="Sign_in"]');
      }
    Emitted | step.passed (I run on android () => {
        I.seeAppIsInstalled("com.kaddra.cem.members.app.test");
        I.seeElement('//android.widget.TextView[@content-desc="Sign_in"]');
        I.tap('//android.widget.TextView[@content-desc="Sign_in"]');
      })
    Emitted | step.finish (I run on android () => {
        I.seeAppIsInstalled("com.kaddra.cem.members.app.test");
        I.seeElement('//android.widget.TextView[@content-desc="Sign_in"]');
        I.tap('//android.widget.TextView[@content-desc="Sign_in"]');
      })
    Emitted | step.start (I run on i o s () => {
        I.seeElement('~SIGN IN');
        I.tap('~SIGN IN');
        I.fillField('~EMAIL', globals.username);
        I.fillField('~Password', globals.password);
        I.tap('~SIGN IN');
        I.seeElement('~MARKET_HEADER_TITLE');
        I.seeElement('~FOOTER_BUTTON_Profile');
      })
    I run on i o s () => {
        I.seeElement('~SIGN IN');
        I.tap('~SIGN IN');
        I.fillField('~EMAIL', globals.username);
        I.fillField('~Password', globals.password);
        I.tap('~SIGN IN');
        I.seeElement('~MARKET_HEADER_TITLE');
        I.seeElement('~FOOTER_BUTTON_Profile');
      }
    [1] Starting <iOS-only actions> session
    Emitted | step.before (I see element "~SIGN IN")
    Emitted | step.after (I see element "~SIGN IN")
    Emitted | step.before (I tap "~SIGN IN")
    Emitted | step.after (I tap "~SIGN IN")
    Emitted | step.before (I fill field "~EMAIL", "***********************m")
    Emitted | step.after (I fill field "~EMAIL", "**********************")
    Emitted | step.before (I fill field "~Password", "***********")
    Emitted | step.after (I fill field "~Password", "**************")
    Emitted | step.before (I tap "~SIGN IN")
    Emitted | step.after (I tap "~SIGN IN")
    Emitted | step.before (I see element "~MARKET_HEADER_TITLE")
    Emitted | step.after (I see element "~MARKET_HEADER_TITLE")
    Emitted | step.before (I see element "~FOOTER_BUTTON_Profile")
    Emitted | step.after (I see element "~FOOTER_BUTTON_Profile")
    Emitted | step.start (I see element "~SIGN IN")
    Appium: _runWithCaps 
      I see element "~SIGN IN"
      › [SmartWait (5000ms)] Locating ~SIGN IN in 5000
    [1] <iOS-only actions> Retrying... Attempt #2
      › [SmartWait (5000ms)] Locating ~SIGN IN in 5000
    [1] <iOS-only actions> Retrying... Attempt #3
      › [SmartWait (5000ms)] Locating ~SIGN IN in 5000
    [1] <iOS-only actions> Retrying... Attempt #4
      › [SmartWait (5000ms)] Locating ~SIGN IN in 5000
    [1] <iOS-only actions> Retrying... Attempt #5
      › [SmartWait (5000ms)] Locating ~SIGN IN in 5000
    [1] <iOS-only actions> Retrying... Attempt #6
      › [SmartWait (5000ms)] Locating ~SIGN IN in 5000
    [1] <iOS-only actions> Error | Error: Element "~SIGN IN" was not found by text|CSS|XPath
    Emitted | step.failed (I see element "~SIGN IN")
    Emitted | step.finish (I see element "~SIGN IN")
    [1] <iOS-only actions> Error | Error: Element "~SIGN IN" was not found by text|CSS|XPath
    Emitted | step.failed (I tap "~SIGN IN")
    Emitted | step.finish (I tap "~SIGN IN")
    [1] <iOS-only actions> Error | Error: Element "~SIGN IN" was not found by text|CSS|XPath
    Emitted | step.failed (I fill field "~EMAIL", "**********************")
    Emitted | step.finish (I fill field "~EMAIL", "*******************")
    [1] <iOS-only actions> Error | Error: Element "~SIGN IN" was not found by text|CSS|XPath
    Emitted | step.failed (I fill field "~Password", "*********")
    Emitted | step.finish (I fill field "~Password", "********")
    [1] <iOS-only actions> Error | Error: Element "~SIGN IN" was not found by text|CSS|XPath
    Emitted | step.failed (I tap "~SIGN IN")
    Emitted | step.finish (I tap "~SIGN IN")
    [1] <iOS-only actions> Error | Error: Element "~SIGN IN" was not found by text|CSS|XPath
    Emitted | step.failed (I see element "~MARKET_HEADER_TITLE")
    Emitted | step.finish (I see element "~MARKET_HEADER_TITLE")
    [1] <iOS-only actions> Error | Error: Element "~SIGN IN" was not found by text|CSS|XPath
    Emitted | step.failed (I see element "~FOOTER_BUTTON_Profile")
    Emitted | step.finish (I see element "~FOOTER_BUTTON_Profile")
    [1] <iOS-only actions> Error | Error: Element "~SIGN IN" was not found by text|CSS|XPath
    Emitted | step.failed (I run on i o s () => {
        I.seeElement('~SIGN IN');
        I.tap('~SIGN IN');
        I.fillField('~EMAIL', globals.username);
        I.fillField('~Password', globals.password);
        I.tap('~SIGN IN');
        I.seeElement('~MARKET_HEADER_TITLE');
        I.seeElement('~FOOTER_BUTTON_Profile');
      })
    Emitted | step.finish (I run on i o s () => {
        I.seeElement('~SIGN IN');
        I.tap('~SIGN IN');
        I.fillField('~EMAIL', globals.username);
        I.fillField('~Password', globals.password);
        I.tap('~SIGN IN');
        I.seeElement('~MARKET_HEADER_TITLE');
        I.seeElement('~FOOTER_BUTTON_Profile');
      })
    [1] <iOS-only actions> Error | Error: Element "~SIGN IN" was not found by text|CSS|XPath
    Emitted | step.failed (I close app )
    Emitted | step.finish (I close app )
    [1] <iOS-only actions> Error | Error: Element "~SIGN IN" was not found by text|CSS|XPath
    [1] <iOS-only actions> Starting <teardown> session
    Emitted | test.failed ([object Object])
    Emitted | test.finish ([object Object])
    [1] <teardown> Stopping recording promises
 › <screenshotOnFail> Test failed, saving screenshot
 › Screenshot has been saved to /Users/distiller/cem-qa/cem-qa-mobile/output/test_app_installed_and_sign_in_to_the_APP.failed.png
  ✖ FAILED in 37939ms

    [2] Starting recording promises
    Emitted | test.after ([object Object])
    Emitted | suite.after ([object Object])
test logout --
    Emitted | suite.before ([object Object])
  logout test @smoke
    Emitted | test.before ([object Object])
    Emitted | test.start ([object Object])
    Emitted | step.before (I run on android () => {
        I.seeAppIsInstalled("com.kaddra.cem.members.app.test");
      })
    Emitted | step.after (I run on android () => {
        I.seeAppIsInstalled("com.kaddra.cem.members.app.test");
      })
    Emitted | step.before (I run on i o s () => {
        I.seeElement('~MARKET_HEADER_TITLE');
        I.seeElement('~FOOTER_BUTTON_Profile');
        I.tap('~FOOTER_BUTTON_Profile');
        I.seeElement('~SETTINGS');
        I.tap('~SETTINGS');
        I.seeElement('~SIGN OUT');
        I.tap('~SIGN OUT');
        I.seeElement('~NOT_USER_BUTTON');
        I.tap('~NOT_USER_BUTTON');
        I.seeElement('~BACK');
        I.tap('~BACK');
      })
    Emitted | step.after (I run on i o s () => {
        I.seeElement('~MARKET_HEADER_TITLE');
        I.seeElement('~FOOTER_BUTTON_Profile');
        I.tap('~FOOTER_BUTTON_Profile');
        I.seeElement('~SETTINGS');
        I.tap('~SETTINGS');
        I.seeElement('~SIGN OUT');
        I.tap('~SIGN OUT');
        I.seeElement('~NOT_USER_BUTTON');
        I.tap('~NOT_USER_BUTTON');
        I.seeElement('~BACK');
        I.tap('~BACK');
      })
    Emitted | step.before (I close app )
    Emitted | step.after (I close app )
    Emitted | step.start (I run on android () => {
        I.seeAppIsInstalled("com.kaddra.cem.members.app.test");
      })
    I run on android () => {
        I.seeAppIsInstalled("com.kaddra.cem.members.app.test");
      }
    Emitted | step.passed (I run on android () => {
        I.seeAppIsInstalled("com.kaddra.cem.members.app.test");
      })
    Emitted | step.finish (I run on android () => {
        I.seeAppIsInstalled("com.kaddra.cem.members.app.test");
      })
    Emitted | step.start (I run on i o s () => {
        I.seeElement('~MARKET_HEADER_TITLE');
        I.seeElement('~FOOTER_BUTTON_Profile');
        I.tap('~FOOTER_BUTTON_Profile');
        I.seeElement('~SETTINGS');
        I.tap('~SETTINGS');
        I.seeElement('~SIGN OUT');
        I.tap('~SIGN OUT');
        I.seeElement('~NOT_USER_BUTTON');
        I.tap('~NOT_USER_BUTTON');
        I.seeElement('~BACK');
        I.tap('~BACK');
      })
    I run on i o s () => {
        I.seeElement('~MARKET_HEADER_TITLE');
        I.seeElement('~FOOTER_BUTTON_Profile');
        I.tap('~FOOTER_BUTTON_Profile');
        I.seeElement('~SETTINGS');
        I.tap('~SETTINGS');
        I.seeElement('~SIGN OUT');
        I.tap('~SIGN OUT');
        I.seeElement('~NOT_USER_BUTTON');
        I.tap('~NOT_USER_BUTTON');
        I.seeElement('~BACK');
        I.tap('~BACK');
      }
    [2] Starting <iOS-only actions> session
    Emitted | step.before (I see element "~MARKET_HEADER_TITLE")
    Emitted | step.after (I see element "~MARKET_HEADER_TITLE")
    Emitted | step.before (I see element "~FOOTER_BUTTON_Profile")
    Emitted | step.after (I see element "~FOOTER_BUTTON_Profile")
    Emitted | step.before (I tap "~FOOTER_BUTTON_Profile")
    Emitted | step.after (I tap "~FOOTER_BUTTON_Profile")
    Emitted | step.before (I see element "~SETTINGS")
    Emitted | step.after (I see element "~SETTINGS")
    Emitted | step.before (I tap "~SETTINGS")
    Emitted | step.after (I tap "~SETTINGS")
    Emitted | step.before (I see element "~SIGN OUT")
    Emitted | step.after (I see element "~SIGN OUT")
    Emitted | step.before (I tap "~SIGN OUT")
    Emitted | step.after (I tap "~SIGN OUT")
    Emitted | step.before (I see element "~NOT_USER_BUTTON")
    Emitted | step.after (I see element "~NOT_USER_BUTTON")
    Emitted | step.before (I tap "~NOT_USER_BUTTON")
    Emitted | step.after (I tap "~NOT_USER_BUTTON")
    Emitted | step.before (I see element "~BACK")
    Emitted | step.after (I see element "~BACK")
    Emitted | step.before (I tap "~BACK")
    Emitted | step.after (I tap "~BACK")
    Emitted | step.start (I see element "~MARKET_HEADER_TITLE")
    Appium: _runWithCaps 
      I see element "~MARKET_HEADER_TITLE"
      › [SmartWait (5000ms)] Locating ~MARKET_HEADER_TITLE in 5000
    [2] <iOS-only actions> Retrying... Attempt #2
      › [SmartWait (5000ms)] Locating ~MARKET_HEADER_TITLE in 5000
    [2] <iOS-only actions> Retrying... Attempt #3
      › [SmartWait (5000ms)] Locating ~MARKET_HEADER_TITLE in 5000
    [2] <iOS-only actions> Retrying... Attempt #4
      › [SmartWait (5000ms)] Locating ~MARKET_HEADER_TITLE in 5000
    [2] <iOS-only actions> Retrying... Attempt #5
      › [SmartWait (5000ms)] Locating ~MARKET_HEADER_TITLE in 5000
    [2] <iOS-only actions> Retrying... Attempt #6
      › [SmartWait (5000ms)] Locating ~MARKET_HEADER_TITLE in 5000
    [2] <iOS-only actions> Error | Error: Element "~MARKET_HEADER_TITLE" was not found by text|CSS|XPath
    Emitted | step.failed (I see element "~MARKET_HEADER_TITLE")
    Emitted | step.finish (I see element "~MARKET_HEADER_TITLE")
    [2] <iOS-only actions> Error | Error: Element "~MARKET_HEADER_TITLE" was not found by text|CSS|XPath
    Emitted | step.failed (I see element "~FOOTER_BUTTON_Profile")
    Emitted | step.finish (I see element "~FOOTER_BUTTON_Profile")
    [2] <iOS-only actions> Error | Error: Element "~MARKET_HEADER_TITLE" was not found by text|CSS|XPath
    Emitted | step.failed (I tap "~FOOTER_BUTTON_Profile")
    Emitted | step.finish (I tap "~FOOTER_BUTTON_Profile")
    [2] <iOS-only actions> Error | Error: Element "~MARKET_HEADER_TITLE" was not found by text|CSS|XPath
    Emitted | step.failed (I see element "~SETTINGS")
    Emitted | step.finish (I see element "~SETTINGS")
    [2] <iOS-only actions> Error | Error: Element "~MARKET_HEADER_TITLE" was not found by text|CSS|XPath
    Emitted | step.failed (I tap "~SETTINGS")
    Emitted | step.finish (I tap "~SETTINGS")
    [2] <iOS-only actions> Error | Error: Element "~MARKET_HEADER_TITLE" was not found by text|CSS|XPath
    Emitted | step.failed (I see element "~SIGN OUT")
    Emitted | step.finish (I see element "~SIGN OUT")
    [2] <iOS-only actions> Error | Error: Element "~MARKET_HEADER_TITLE" was not found by text|CSS|XPath
    Emitted | step.failed (I tap "~SIGN OUT")
    Emitted | step.finish (I tap "~SIGN OUT")
    [2] <iOS-only actions> Error | Error: Element "~MARKET_HEADER_TITLE" was not found by text|CSS|XPath
    Emitted | step.failed (I see element "~NOT_USER_BUTTON")
    Emitted | step.finish (I see element "~NOT_USER_BUTTON")
    [2] <iOS-only actions> Error | Error: Element "~MARKET_HEADER_TITLE" was not found by text|CSS|XPath
    Emitted | step.failed (I tap "~NOT_USER_BUTTON")
    Emitted | step.finish (I tap "~NOT_USER_BUTTON")
    [2] <iOS-only actions> Error | Error: Element "~MARKET_HEADER_TITLE" was not found by text|CSS|XPath
    Emitted | step.failed (I see element "~BACK")
    Emitted | step.finish (I see element "~BACK")
    [2] <iOS-only actions> Error | Error: Element "~MARKET_HEADER_TITLE" was not found by text|CSS|XPath
    Emitted | step.failed (I tap "~BACK")
    Emitted | step.finish (I tap "~BACK")
    [2] <iOS-only actions> Error | Error: Element "~MARKET_HEADER_TITLE" was not found by text|CSS|XPath
    Emitted | step.failed (I run on i o s () => {
        I.seeElement('~MARKET_HEADER_TITLE');
        I.seeElement('~FOOTER_BUTTON_Profile');
        I.tap('~FOOTER_BUTTON_Profile');
        I.seeElement('~SETTINGS');
        I.tap('~SETTINGS');
        I.seeElement('~SIGN OUT');
        I.tap('~SIGN OUT');
        I.seeElement('~NOT_USER_BUTTON');
        I.tap('~NOT_USER_BUTTON');
        I.seeElement('~BACK');
        I.tap('~BACK');
      })
    Emitted | step.finish (I run on i o s () => {
        I.seeElement('~MARKET_HEADER_TITLE');
        I.seeElement('~FOOTER_BUTTON_Profile');
        I.tap('~FOOTER_BUTTON_Profile');
        I.seeElement('~SETTINGS');
        I.tap('~SETTINGS');
        I.seeElement('~SIGN OUT');
        I.tap('~SIGN OUT');
        I.seeElement('~NOT_USER_BUTTON');
        I.tap('~NOT_USER_BUTTON');
        I.seeElement('~BACK');
        I.tap('~BACK');
      })
    [2] <iOS-only actions> Error | Error: Element "~MARKET_HEADER_TITLE" was not found by text|CSS|XPath
    Emitted | step.failed (I close app )
    Emitted | step.finish (I close app )
    [2] <iOS-only actions> Error | Error: Element "~MARKET_HEADER_TITLE" was not found by text|CSS|XPath
    [2] <iOS-only actions> Starting <teardown> session
    Emitted | test.failed ([object Object])
    Emitted | test.finish ([object Object])
    [2] <teardown> Stopping recording promises
 › <screenshotOnFail> Test failed, saving screenshot
 › Screenshot has been saved to /Users/distiller/cem-qa/cem-qa-mobile/output/logout_test_@smoke.failed.png
  ✖ FAILED in 37830ms

    [3] Starting recording promises
    Emitted | test.after ([object Object])
    Emitted | suite.after ([object Object])

-- FAILURES:

  1) test user login
       test app installed and sign in to the APP:
     Element "~SIGN IN" was not found by text|CSS|XPath
  
  Scenario Steps:
  
  - I.runOnIOS(() => {
          I.seeElement('~SIGN IN');
          I.tap('~SIGN IN');
          I.fillField('~EMAIL', globals.username);
          I.fillField('~Password', globals.password);
          I.tap('~SIGN IN');
          I.seeElement('~MARKET_HEADER_TITLE');
          I.seeElement('~FOOTER_BUTTON_Profile');
        }) at Test.<anonymous> (tests/login_test.js:9:9)
  - I.runOnAndroid(() => {
          I.seeAppIsInstalled("com.kaddra.cem.members.app.test");
          I.seeElement('//android.widget.TextView[@content-desc="Sign_in"]');
          I.tap('//android.widget.TextView[@content-desc="Sign_in"]');
        }) at Test.<anonymous> (tests/login_test.js:4:7)
  
  Error: Element "~SIGN IN" was not found by text|CSS|XPath
      at new ElementNotFound (node_modules/codeceptjs/lib/helper/errors/ElementNotFound.js:14:11)
      at assertElementExists (node_modules/codeceptjs/lib/helper/WebDriver.js:2453:11)
      at Appium.seeElement (node_modules/codeceptjs/lib/helper/WebDriver.js:1106:5)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)

  2) test logout
       logout test @smoke:
     Element "~MARKET_HEADER_TITLE" was not found by text|CSS|XPath
  
  Scenario Steps:
  
  - I.runOnIOS(() => {
          I.seeElement('~MARKET_HEADER_TITLE');
          I.seeElement('~FOOTER_BUTTON_Profile');
          I.tap('~FOOTER_BUTTON_Profile');
          I.seeElement('~SETTINGS');
          I.tap('~SETTINGS');
          I.seeElement('~SIGN OUT');
          I.tap('~SIGN OUT');
          I.seeElement('~NOT_USER_BUTTON');
          I.tap('~NOT_USER_BUTTON');
          I.seeElement('~BACK');
          I.tap('~BACK');
        }) at Test.<anonymous> (tests/logout_test.js:7:9)
  - I.runOnAndroid(() => {
          I.seeAppIsInstalled("com.kaddra.cem.members.app.test");
        }) at Test.<anonymous> (tests/logout_test.js:4:7)
  
  Error: Element "~MARKET_HEADER_TITLE" was not found by text|CSS|XPath
      at new ElementNotFound (node_modules/codeceptjs/lib/helper/errors/ElementNotFound.js:14:11)
      at assertElementExists (node_modules/codeceptjs/lib/helper/WebDriver.js:2453:11)
      at Appium.seeElement (node_modules/codeceptjs/lib/helper/WebDriver.js:1106:5)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)


  FAIL  | 0 passed, 2 failed   // 5m
    Emitted | global.result ([object Object])
    Emitted | global.after ([object Object])
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cem-qa-mobile@1.0.0 kaddra-cem-qa-mobile-test: `npx codeceptjs run --steps --verbose --config=./codecept.conf.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the cem-qa-mobile@1.0.0 kaddra-cem-qa-mobile-test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/distiller/.npm/_logs/2020-03-29T03_46_10_729Z-debug.log


Exited with code exit status 1
CircleCI received exit code 1
```
> Provide test source code if related

```js
Feature('test user login');

Scenario('test app installed and sign in to the APP', (I, globals) => {
    I.runOnAndroid(() => {
        I.seeElement('//android.widget.TextView[@content-desc="Sign_in"]');
        I.tap('//android.widget.TextView[@content-desc="Sign_in"]');
      });
      I.runOnIOS(() => {
        I.seeElement('~SIGN IN');
        I.tap('~SIGN IN');
        I.fillField('~EMAIL', globals.username);
        I.fillField('~Password', globals.password);
        I.tap('~SIGN IN');
        I.seeElement('~MARKET_HEADER_TITLE');
        I.seeElement('~FOOTER_BUTTON_Profile');
      });
      I.closeApp();
});
```

### Details

* CodeceptJS version: 2.5.0
* NodeJS Version: v13.12.0
* Operating System: MacOS
* Appium: 1.17.0
* Configuration file: 

```js
exports.config = {
  tests: 'tests/*_test.js',
  output: './output',
  helpers: {
    Appium: {
      smartWait: 5000,
      app: '/tmp/workspace/artifacts/kaddra.app',
      platform: 'iOS',
       desiredCapabilities: {
         deviceName: "iPhone 11",
         automationName: "XCUITest",
         autoWebview: false,
         newCommandTimeout: 3600,
         platformVersion: "13.0",
         fullReset: false,
         noReset: true,
         isHeadless: true,
         locationServicesEnabled: true,
         locationServicesAuthorized: true,
         calendarAccessAuthorized: true
       }
    }
  },
  include: {
    I: './steps_file.js',
    globals:'./globals.js'
  },
  bootstrap: null,
  mocha: {
    reporterOptions: {
      mochaFile: 'output/result.xml'
    }
  },
  rerun: {
    // run 2 times until 1st success, command:"npx codeceptjs run-rerun"
    minSuccess: 1,
    maxReruns: 2,
  },
  name: 'cem-qa-mobile',
  plugins: {
    retryFailedStep: {
      enabled: true
    },
    screenshotOnFail: {
      enabled: true
    }
  }
}
```

**Comment by DavertMik** [comment]
can't help
