### ISSUE TITLE
Cannot pass json as argument to override on Windows

### ISSUE THREAD

**Issue by flo223** [codeceptjs/CodeceptJS#2444]
#### What are you trying to achieve?
I'm trying to pass a configuration option as a command line argument using the documentation example:
npx codeceptjs run --override '{ "helpers": {"WebDriver": {"browser": "chrome"}}}'

I tried escaping quote with the same result

npx codeceptjs run --override '{ \\"helpers\\": {\\"WebDriver\\": {\\"browser\\": \\"chrome\\"}}}'
#### What do you get instead?

SyntaxError: Unexpected token h in JSON at position 1
    at JSON.parse (<anonymous>)
    at Command.module.exports (C:\Workspace\fxs_signals_front_at.git\node_modules\codeceptjs\lib\command\run.js:21:33)
    at Command.listener (C:\Workspace\fxs_signals_front_at.git\node_modules\commander\index.js:315:8)
    at Command.emit (events.js:310:20)
    at Command.parseArgs (C:\Workspace\fxs_signals_front_at.git\node_modules\commander\index.js:651:12)
    at Command.parse (C:\Workspace\fxs_signals_front_at.git\node_modules\commander\index.js:474:21)
    at Object.<anonymous> (C:\Workspace\fxs_signals_front_at.git\node_modules\codeceptjs\bin\codecept.js:228:9)
    at Module._compile (internal/modules/cjs/loader.js:1133:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
    at Module.load (internal/modules/cjs/loader.js:977:32)

### Details

* CodeceptJS version: 2.6.5
* NodeJS Version: 12.16.3
* Operating System: Windows 10
* protractor

**Comment by shpyrkova** [comment]
same! just tried it yesterday.

**Comment by DavertMik** [comment]
sorry, can't help
