### ISSUE TITLE
Trying to read datatable from another module in codeceptjs. But getting 'TypeError: data.map is not a function' error

### ISSUE THREAD

**Issue by sreekanthjkprojects** [codeceptjs/CodeceptJS#2470]
#### What are you trying to achieve?
Trying to read datatable values from another js file.

#### What do you get instead?
TypeError: data.map is not a function

> Provide console output if related. Use `--verbose` mode for more details.

```sh
bashTypeError: data.map is not a function
    at Object.Scenario (C:\Users\xx\Desktop\CodeceptJs_Project\node_modules\codeceptjs\lib\data\context.js:15:26)
    at Object.<anonymous> (C:\Users\xx\Desktop\CodeceptJs_Project\Tests\AccountViewer_login_test.js:16:27)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at C:\Users\xxx\Desktop\CodeceptJs_Project\node_modules\mocha\lib\mocha.js:334:36
    at Array.forEach (<anonymous>)

TypeError: data.map is not a function

Error: 
    at Codecept.run (C:\Users\xx\Desktop\CodeceptJs_Project\node_modules\codeceptjs\lib\codecept.js:177:13)
    at C:\Users\xx\Desktop\CodeceptJs_Project\node_modules\codeceptjs\lib\command\run.js:34:16
    at module.exports (C:\Users\xx\Desktop\CodeceptJs_Project\node_modules\codeceptjs\lib\hooks.js:28:13)
    at Codecept.runBootstrap (C:\Users\xx\Desktop\CodeceptJs_Project\node_modules\codeceptjs\lib\codecept.js:112:5)
    at Command.module.exports (C:\Users\xx\Desktop\CodeceptJs_Project\node_modules\codeceptjs\lib\command\run.js:30:14)
    at Command.listener (C:\Users\xx\Desktop\CodeceptJs_Project\node_modules\commander\index.js:315:8)
    at Command.emit (events.js:311:20)
    at Command.parseArgs (C:\Users\xx\Desktop\CodeceptJs_Project\node_modules\commander\index.js:651:12)
    at Command.parse (C:\Users\xx\Desktop\CodeceptJs_Project\node_modules\commander\index.js:474:21)
    at Object.<anonymous> (C:\Users\xx\Desktop\CodeceptJs_Project\node_modules\codeceptjs\bin\codecept.js:226:9)
# paste output here
```

> Provide test source code if related:
```js
const DataTable = require('./TestData');
Feature('login, account');

const {I,LoginPageMethods,LoginPageElements,Testdata} = inject();

Data(DataTable.testdata1).Scenario('Login to Account Viewer application', (I,LoginPageMethods,LoginPageElements,current) => {
    I.amOnPage("https://xxxx.com/");
    LoginPageMethods.Login(current.login,current.password);
    //console.log(LoginPageElements.Login_elements.username);
    //console.log(ReadingapiResponse.name)
}).tag('@testdata');
```
================
TestData.js looks like below:
```js
module.exports = {
  //accounts1 : new DataTable(['login', 'password']),
  testdata1(){

var accounts = new DataTable(['login', 'password']);
accounts.add(['davert', '123456']); // adding records to a table
//accounts.add(['admin', '123456']);//     let accounts = new DataTable(['login', 'password'])
//     accounts.add(['davert', '123456']) // adding records to a table
// accounts.add(['admin', '123456']);
      return accounts;
  }
}
```

```js
// paste test
```

### Details

* CodeceptJS version:
* NodeJS Version:
* Operating System:
* puppeteer || webdriverio || protractor || testcafe version (if related)
* Configuration file:

```js
# paste config here
```

**Comment by Vorobeyko** [comment]
Hi!
You using `DataTable.testdata1` but this is function. 
You must to use `DataTable.testdata1()`.
