### ISSUE TITLE
JavaScript heap out of memory

### ISSUE THREAD

**Issue by arturslogins** [codeceptjs/CodeceptJS#2510]
Hello 

i am using codeception/codeceptjs as a docker container 

Running one of my tests i get error about JS heap memory 

`<--- Last few GCs --->
codeceptjs_1  |
codeceptjs_1  | [24:0x35e8800]    91614 ms: Scavenge 2039.2 (2051.8) -> 2033.5 (2052.3) MB, 11.7 / 0.0 ms  (average mu = 0.112, current mu = 0.058) allocation failure
codeceptjs_1  |
codeceptjs_1  |
codeceptjs_1  | <--- JS stacktrace --->
codeceptjs_1  |
codeceptjs_1  | ==== JS stack trace =========================================
codeceptjs_1  |
codeceptjs_1  |     0: ExitFrame [pc: 0x134e879]
codeceptjs_1  | Security context: 0x34efce3f34f1 <JSObject>
codeceptjs_1  |     1: split [0x34efce3fed99](this=0x106ff39a3811 <String[655]\: pressKey\n    at Step.setTrace (/codecept/lib/step.js:48:11)\n    at new Step (/codecept/lib/step.js:43:10)\n    at Object.ob
j.<computed>.obj.<computed> [as pressKey] (/codecept/lib/actor.js:33:26)\n    at Object.fillSelect (/tests/steps_file.js:27:14)\n    at Test.<anonymous> (/tests/tests/create_c...
codeceptjs_1  |
codeceptjs_1  | FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
codeceptjs_1  |  1: 0x9bcb80 node::Abort() [node]
codeceptjs_1  |  2: 0x9bdd16 node::OnFatalError(char const*, char const*) [node]
codeceptjs_1  |  3: 0xb1948e v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [node]
codeceptjs_1  |  4: 0xb19809 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [node]
codeceptjs_1  |  5: 0xcca1f5  [node]
codeceptjs_1  |  6: 0xcca866 v8::internal::Heap::RecomputeLimits(v8::internal::GarbageCollector) [node]
codeceptjs_1  |  7: 0xcd609a v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [node]
codeceptjs_1  |  8: 0xcd6fa5 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [node]
codeceptjs_1  |  9: 0xcd86af v8::internal::Heap::HandleGCRequest() [node]
codeceptjs_1  | 10: 0xc60e74 v8::internal::StackGuard::HandleInterrupts() [node]
codeceptjs_1  | 11: 0xfc9417 v8::internal::Runtime_StackGuard(int, unsigned long*, v8::internal::Isolate*) [node]
codeceptjs_1  | 12: 0x134e879  [node]
codeceptjs_1  | /codecept/docker/run.sh: line 28:    24 Aborted                 codeceptjs run $CODECEPT_ARGS
`

Question is - how can i fix this error ?? 

My docker-compose config: 

`
version: '3.6'

services:
  codeceptjs:
    image: codeception/codeceptjs
    environment:
    - CODECEPT_ARGS=tests/create_campaign_test.js --steps
    volumes:
    - ./:/tests
`

And test i just a 44 lines long, when i delete out half of steps, test is working 

Is there any extra parameter for increase JS memory ?

**Comment by arturslogins** [comment]
Problem was with infinity loop in select field
