### ISSUE TITLE
Iframe chromium tests no longer works

### ISSUE THREAD

**Issue by vimar** [codeceptjs/CodeceptJS#2577]
#### What are you trying to achieve?

I let tests unchanged yet they no longer pass on my PR.

#### What do you get instead?

More info there: https://github.com/codeceptjs/CodeceptJS/pull/2576/checks

```bash
-- FAILURES:
2020-09-10T09:44:36.1937137Z 
2020-09-10T09:44:36.1943137Z [0m  1) within
2020-09-10T09:44:36.1943421Z        switch iframe manually @WebDriverIO @Puppeteer @Playwright @Protractor:
2020-09-10T09:44:36.1943890Z [0m[31m     Text "Email Address" was not found on page after 1 sec
2020-09-10T09:44:36.1944447Z page.waitForFunction: Timeout 1000ms exceeded.
2020-09-10T09:44:36.1945004Z Note: use DEBUG=pw:api environment variable and rerun to capture Playwright logs.[0m[90m
2020-09-10T09:44:36.1945153Z   
2020-09-10T09:44:36.1945279Z   Scenario Steps:
2020-09-10T09:44:36.1945389Z   
2020-09-10T09:44:36.1945789Z   - I.waitForText("Email Address") at Test.<anonymous> (test/acceptance/within_test.js:20:5)
2020-09-10T09:44:36.1946191Z   - I.click("Sign in!") at Test.<anonymous> (test/acceptance/within_test.js:19:5)
2020-09-10T09:44:36.1946577Z   - I.fillField("rus", "Updated") at Test.<anonymous> (test/acceptance/within_test.js:18:5)
2020-09-10T09:44:36.1946968Z   - I.switchTo("iframe") at Test.<anonymous> (test/acceptance/within_test.js:17:5)
2020-09-10T09:44:36.1947351Z   - I.amOnPage("/iframe") at Test.<anonymous> (test/acceptance/within_test.js:15:5)
2020-09-10T09:44:36.1947486Z   
2020-09-10T09:44:36.1947596Z   
2020-09-10T09:44:36.1947702Z   
2020-09-10T09:44:36.1948028Z   Run with --verbose flag to see NodeJS stacktrace
2020-09-10T09:44:36.1948460Z [0m
2020-09-10T09:44:36.1950695Z [0m  2) within
2020-09-10T09:44:36.1950957Z        within on iframe @WebDriverIO @Puppeteer @Playwright @Protractor @Nightmare:
2020-09-10T09:44:36.1951416Z [0m[31m     Text "Email Address" was not found on page after 1 sec
2020-09-10T09:44:36.1951635Z page.waitForFunction: Timeout 1000ms exceeded.
2020-09-10T09:44:36.1952096Z Note: use DEBUG=pw:api environment variable and rerun to capture Playwright logs.[0m[90m
2020-09-10T09:44:36.1952243Z   
2020-09-10T09:44:36.1952366Z   Scenario Steps:
2020-09-10T09:44:36.1952481Z   
2020-09-10T09:44:36.1952921Z   - I.waitForText("Email Address") at /home/runner/work/CodeceptJS/CodeceptJS/test/acceptance/within_test.js:32:7
2020-09-10T09:44:36.1953358Z   - I.click("Sign in!") at /home/runner/work/CodeceptJS/CodeceptJS/test/acceptance/within_test.js:31:7
2020-09-10T09:44:36.1953820Z   - I.fillField("rus", "Updated") at /home/runner/work/CodeceptJS/CodeceptJS/test/acceptance/within_test.js:30:7
2020-09-10T09:44:36.1954230Z   - I.amOnPage("/iframe") at Test.<anonymous> (test/acceptance/within_test.js:28:5)
2020-09-10T09:44:36.1954362Z   
2020-09-10T09:44:36.1954453Z   
2020-09-10T09:44:36.1954559Z   
2020-09-10T09:44:36.1954877Z   Run with --verbose flag to see NodeJS stacktrace
2020-09-10T09:44:36.1955138Z [0m
2020-09-10T09:44:36.1957396Z [0m  3) within
2020-09-10T09:44:36.1957679Z        within on nested iframe depth 1 @WebDriverIO @Puppeteer @Playwright @Protractor @Nightmare:
2020-09-10T09:44:36.1958140Z [0m[31m     Text "Email Address" was not found on page after 1 sec
2020-09-10T09:44:36.1958356Z page.waitForFunction: Timeout 1000ms exceeded.
2020-09-10T09:44:36.1958829Z Note: use DEBUG=pw:api environment variable and rerun to capture Playwright logs.[0m[90m
2020-09-10T09:44:36.1958969Z   
2020-09-10T09:44:36.1959092Z   Scenario Steps:
2020-09-10T09:44:36.1959202Z   
2020-09-10T09:44:36.1959626Z   - I.waitForText("Email Address") at /home/runner/work/CodeceptJS/CodeceptJS/test/acceptance/within_test.js:63:7
2020-09-10T09:44:36.1960069Z   - I.click("Sign in!") at /home/runner/work/CodeceptJS/CodeceptJS/test/acceptance/within_test.js:62:7
2020-09-10T09:44:36.1960514Z   - I.fillField("rus", "Updated") at /home/runner/work/CodeceptJS/CodeceptJS/test/acceptance/within_test.js:61:7
2020-09-10T09:44:36.1960907Z   - I.amOnPage("/iframe") at Test.<anonymous> (test/acceptance/within_test.js:59:5)
2020-09-10T09:44:36.1961038Z   
2020-09-10T09:44:36.1961146Z   
2020-09-10T09:44:36.1961252Z   
2020-09-10T09:44:36.1961566Z   Run with --verbose flag to see NodeJS stacktrace
2020-09-10T09:44:36.1961825Z [0m
2020-09-10T09:44:36.1994203Z [0m  4) within
2020-09-10T09:44:36.1994504Z        within on nested iframe depth 2 @WebDriverIO @Puppeteer @Playwright @Protractor:
2020-09-10T09:44:36.1994588Z 
2020-09-10T09:44:36.1995025Z       [31mexpected [1mweb application[22m to include "[1mEmail Address[22m"[0m
2020-09-10T09:44:36.1995359Z       [32m+ expected[0m [31m- actual[0m
2020-09-10T09:44:36.1995612Z 
2020-09-10T09:44:36.1995974Z       [31m-Nested Iframe test[0m
2020-09-10T09:44:36.1996267Z       [32m+Email Address[0m
2020-09-10T09:44:36.1996532Z       [0m[90m
2020-09-10T09:44:36.1996651Z   
2020-09-10T09:44:36.1996777Z   Scenario Steps:
2020-09-10T09:44:36.1996892Z   
2020-09-10T09:44:36.1997298Z   - I.see("Email Address") at /home/runner/work/CodeceptJS/CodeceptJS/test/acceptance/within_test.js:74:7
2020-09-10T09:44:36.1997729Z   - I.click("Sign in!") at /home/runner/work/CodeceptJS/CodeceptJS/test/acceptance/within_test.js:73:7
2020-09-10T09:44:36.1998170Z   - I.fillField("rus", "Updated") at /home/runner/work/CodeceptJS/CodeceptJS/test/acceptance/within_test.js:72:7
2020-09-10T09:44:36.1998571Z   - I.amOnPage("/iframe_nested") at Test.<anonymous> (test/acceptance/within_test.js:70:5)
2020-09-10T09:44:36.1998703Z   
2020-09-10T09:44:36.1998815Z   
2020-09-10T09:44:36.1998920Z   
2020-09-10T09:44:36.1999236Z   Run with --verbose flag to see NodeJS stacktrace
2020-09-10T09:44:36.1999658Z [0m
2020-09-10T09:44:36.1999932Z [0m  5) within
2020-09-10T09:44:36.2000182Z        within on nested iframe depth 2 and mixed id and xpath selector @WebDriverIO @Puppeteer @Playwright @Protractor:
2020-09-10T09:44:36.2000285Z 
2020-09-10T09:44:36.2000666Z       [31mexpected [1mweb application[22m to include "[1mEmail Address[22m"[0m
2020-09-10T09:44:36.2000991Z       [32m+ expected[0m [31m- actual[0m
2020-09-10T09:44:36.2001059Z 
2020-09-10T09:44:36.2001346Z       [31m-Nested Iframe test[0m
2020-09-10T09:44:36.2001628Z       [32m+Email Address[0m
2020-09-10T09:44:36.2001889Z       [0m[90m
2020-09-10T09:44:36.2002005Z   
2020-09-10T09:44:36.2002109Z   Scenario Steps:
2020-09-10T09:44:36.2002221Z   
2020-09-10T09:44:36.2002634Z   - I.see("Email Address") at /home/runner/work/CodeceptJS/CodeceptJS/test/acceptance/within_test.js:85:7
2020-09-10T09:44:36.2003064Z   - I.click("Sign in!") at /home/runner/work/CodeceptJS/CodeceptJS/test/acceptance/within_test.js:84:7
2020-09-10T09:44:36.2003520Z   - I.fillField("rus", "Updated") at /home/runner/work/CodeceptJS/CodeceptJS/test/acceptance/within_test.js:83:7
2020-09-10T09:44:36.2004294Z   - I.amOnPage("/iframe_nested") at Test.<anonymous> (test/acceptance/within_test.js:81:5)
2020-09-10T09:44:36.2004439Z   
2020-09-10T09:44:36.2004547Z   
2020-09-10T09:44:36.2004655Z   
2020-09-10T09:44:36.2109209Z   Run with --verbose flag to see NodeJS stacktrace
2020-09-10T09:44:36.2111950Z [0m
2020-09-10T09:44:36.2112444Z [0m  6) within
2020-09-10T09:44:36.2112935Z        within on nested iframe depth 2 and mixed class and xpath selector @WebDriverIO @Puppeteer @Playwright @Protractor:
2020-09-10T09:44:36.2113157Z 
2020-09-10T09:44:36.2113752Z       [31mexpected [1mweb application[22m to include "[1mEmail Address[22m"[0m
2020-09-10T09:44:36.2114293Z       [32m+ expected[0m [31m- actual[0m
2020-09-10T09:44:36.2114631Z 
2020-09-10T09:44:36.2115177Z       [31m-Nested Iframe test[0m
2020-09-10T09:44:36.2115663Z       [32m+Email Address[0m
2020-09-10T09:44:36.2116150Z       [0m[90m
2020-09-10T09:44:36.2116429Z   
2020-09-10T09:44:36.2116665Z   Scenario Steps:
2020-09-10T09:44:36.2116895Z   
2020-09-10T09:44:36.2117478Z   - I.see("Email Address") at /home/runner/work/CodeceptJS/CodeceptJS/test/acceptance/within_test.js:96:7
2020-09-10T09:44:36.2118224Z   - I.click("Sign in!") at /home/runner/work/CodeceptJS/CodeceptJS/test/acceptance/within_test.js:95:7
2020-09-10T09:44:36.2118926Z   - I.fillField("rus", "Updated") at /home/runner/work/CodeceptJS/CodeceptJS/test/acceptance/within_test.js:94:7
2020-09-10T09:44:36.2119694Z   - I.amOnPage("/iframe_nested") at Test.<anonymous> (test/acceptance/within_test.js:92:5)
2020-09-10T09:44:36.2120008Z   
2020-09-10T09:44:36.2120375Z   
2020-09-10T09:44:36.2120608Z   
2020-09-10T09:44:36.2121098Z   Run with --verbose flag to see NodeJS stacktrace
```

**Comment by DavertMik** [comment]
Thanks, this was a bug due to some change in Playwright's API. 
The fix for it should arrive in 2.6.11
