### ISSUE TITLE
run-rerun exits with non-zero exit code when rerun conditions met, but a failed run occurred in a Before* or After*

### ISSUE THREAD

**Issue by anthlam** [codeceptjs/CodeceptJS#2581]
#### What are you trying to achieve?
When running `codeceptjs run-rerun --debug --verbose`, I was expecting a successful retry run after a run that experienced a failure to result in codeceptjs exiting with an exit code of 0, regardless of whether the failure occurred in a before or after hook, or in the test itself.

#### What do you get instead?
If the failure occurs in a `BeforeSuite`, `Before`, `AfterSuite`, or `After` hook, and then there is a successful retry run, codeceptjs will exit with an exit code of 1.  The exit code is only 0 if the failure occurs in the `Scenario`.

> Provide console output if related. Use `--verbose` mode for more details.

```bash
$ FAIL_ATTEMPT=0 npx codeceptjs run-rerun tests/anth.test.js --debug --verbose
CodeceptJS v2.6.10
Using test root "/Users/anthlam/code/anthlam/test-codecept-project"
Helpers: Playwright, AssertWrapper, ChaiWrapper, Mochawesome
Plugins: screenshotOnFail

Run-Rerun testing --
    [1] Starting recording promises
    Emitted | suite.before ([object Object])
 › [Session] Starting singleton browser session
    Emitted | hook.start ([object Object])
RunRerun BeforeSuite
1
    [1] Error | Error: Test Error
    [1] Starting <teardown> session
    Emitted | test.failed ([object Object])
    [1] <teardown> Stopping recording promises
 › <screenshotOnFail> Test failed, try to save a screenshot
 › Screenshot is saving to /Users/anthlam/code/anthlam/test-codecept-project/output/Run-Rerun__1599838660.failed.png
    Emitted | hook.failed ([object Object])
  ✖ FAILED in 258ms

    Emitted | hook.start ([object Object])
    [2] Starting recording promises
RunRerun AfterSuite
    Emitted | hook.passed ([object Object])
    Emitted | suite.after ([object Object])

-- FAILURES:

  1) Run-Rerun testing
       "before all" hook: BeforeSuite for "Fail one, pass one @rerun":
     Test Error
  rror: Test Error
      at testCode (tests/anth.test.js:7:11)
      at Context.<anonymous> (tests/anth.test.js:13:3)
      at Context.<anonymous> (node_modules/codeceptjs/lib/scenario.js:140:10)


  FAIL  | 0 passed, 1 failed   // 597ms

Fail run 1 of max 2, success runs 0/1

Error: 1 tests fail
    at /Users/anthlam/code/anthlam/test-codecept-project/node_modules/codeceptjs/lib/rerun.js:28:20
    at done (/Users/anthlam/code/anthlam/test-codecept-project/node_modules/mocha/lib/mocha.js:843:7)
    at Runner.<anonymous> (/Users/anthlam/code/anthlam/test-codecept-project/node_modules/mocha/lib/runner.js:918:5)
    at Runner.emit (events.js:322:22)
    at /Users/anthlam/code/anthlam/test-codecept-project/node_modules/mocha/lib/runner.js:903:12
    at /Users/anthlam/code/anthlam/test-codecept-project/node_modules/mocha/lib/runner.js:772:9
    at next (/Users/anthlam/code/anthlam/test-codecept-project/node_modules/mocha/lib/runner.js:362:14)
    at Immediate.<anonymous> (/Users/anthlam/code/anthlam/test-codecept-project/node_modules/mocha/lib/runner.js:425:5)
    at processImmediate (internal/timers.js:456:21)
CodeceptJS v2.6.10
Using test root "/Users/anthlam/code/anthlam/test-codecept-project"
Helpers: Playwright, AssertWrapper, ChaiWrapper, Mochawesome
Plugins: screenshotOnFail

Run-Rerun testing --
    Emitted | suite.before ([object Object])
    Emitted | hook.start ([object Object])
RunRerun BeforeSuite
2
    Emitted | hook.passed ([object Object])
  Fail one, pass one @rerun
    Emitted | test.before ([object Object])
    Emitted | hook.start ([object Object])
RunRerun Before
    Emitted | hook.passed ([object Object])
    Emitted | test.start ([object Object])
RunRerun Scenario
    Emitted | test.passed ([object Object])
    Emitted | test.finish ([object Object])
  ✔ OK in 0ms

    Emitted | hook.start ([object Object])
RunRerun After
    Emitted | hook.passed ([object Object])
    Emitted | test.after ([object Object])
 › [Session] cleaning cookies and localStorage
    Emitted | hook.start ([object Object])
RunRerun AfterSuite
    Emitted | hook.passed ([object Object])
    Emitted | suite.after ([object Object])

  OK  | 1 passed   // 9ms

Process run 2 of max 2, success runs 1/1

    Emitted | global.result ([object Object])
    Emitted | global.after ([object Object])


$ echo $?    <---- prints out exit code from previous command
1

```

> Provide test source code if related

```js
Feature("Run-Rerun testing");

function testCode() {
  process.env.FAIL_ATTEMPT = parseInt(process.env.FAIL_ATTEMPT) + 1;
  console.log(process.env.FAIL_ATTEMPT);
  if (process.env.FAIL_ATTEMPT === "1") {
    throw new Error("Test Error");
  }
}

BeforeSuite((I) => {
  console.log("RunRerun BeforeSuite");
  testCode();
});

Before((I) => {
  console.log("RunRerun Before");
});

After((I) => {
  console.log("RunRerun After");
});

AfterSuite((I) => {
  console.log("RunRerun AfterSuite");
});

Scenario("Fail one, pass one @rerun", (I) => {
  console.log("RunRerun Scenario");
});
```

### Details

* CodeceptJS version: 2.6.10
* NodeJS Version: 12.16.2
* Operating System: macOS v10.15.5
* playwright 1.4.0 (but unlikely to be related to the issue)
* Configuration file:

```js
// updates process.env based on the contents of a .env file
if (process.env.ENV_FILE) {
  console.log(`Loading [${process.env.ENV_FILE}]...`);
  require("dotenv").config({ path: process.env.ENV_FILE });
} else {
  require("dotenv").config();
}

const path = require("path");

const ROOT = process.cwd();
const outputUniqueId = process.env.OUTPUT_UID
  ? `-${process.env.OUTPUT_UID}`
  : "";

const config = {
  name: "Functional Tests",
  tests: path.join(ROOT, "tests/**/*test.js"),
  timeout: 10000,
  output: path.join(ROOT, "output"),

  rerun: {
    minSuccess: 1,
    maxReruns: 2,
  },

  helpers: {
    Playwright: {
      url: "http://localhost",
      show: false,
      browser: "chromium",
      waitForTimeout: 30000
    },
    AssertWrapper: {
      require: "codeceptjs-assert",
    },
    ChaiWrapper: {
      require: "codeceptjs-chai",
    },
    Mochawesome: {
      includeScreenshots: true,
      shortScrFileNames: true,
      uniqueScreenshotNames: true,
      screenshotUseRelativePath: true,
      inlineAssets: true,
    },
  },

  multiple: {
    jenkins: { browsers: ["chrome"] },
    basic: {
      browsers: [
        "safari",
        "internet explorer",
        "chrome",
        "firefox",
        "microsoft edge",
      ],
    },
  },

  mocha: {
    reporterOptions: {
      "mocha-junit-reporter": {
        stdout: "-",
        options: {
          mochaFile: path.join(ROOT, `output/result${outputUniqueId}.xml`),
          reportDir: path.join(ROOT, "output"),
          enableCharts: true,
          inlineAssets: true,
        },
      },
      mochawesome: {
        stdout: path.join(ROOT, `output/console${outputUniqueId}.log`),
        options: {
          reportDir: path.join(ROOT, "output"),
          reportFilename: `mochawesome${outputUniqueId}`,
        },
      },
      "codeceptjs-cli-reporter": {
        stdout: "-",
        options: {
          verbose: process.env.VERBOSE_OUTPUT == "true",
          steps: process.env.STEP_OUTPUT == "true",
        },
      },
    },
  },

  bootstrap: false,
  teardown: null,
  hooks: [],
};

module.exports = {
  config,
};
```

I also forked the repo and added some tests to `/test/runner/run_rerun_test.js` to demonstrate this behavior.  Those tests can be found in https://github.com/anthlam/CodeceptJS/commit/300d8d8ff4891d170aaf95ef94b10c23268bbdc2

**Comment by ryust-ax** [comment]
Agreed, found this while using the "Background" statement block via BDD/Gherkin and had to de-dry the statements back to only using Scenario blocks.  My retry logic didn't use the command-line options; I used the helper `_before` hook suggestion 
```
    recorder.retry({
      retries: 2,
      when: (error) => error.message.includes("500"),
    });
```
