### ISSUE TITLE
[QUESTION] - How to interact with tables, Helper required???

### ISSUE THREAD

**Issue by boursawb** [codeceptjs/CodeceptJS#2584]
I will apologize ahead of time for posting a question here, as I don't believe this is the correct forum.  That said, I am on weeks of trying to find anyone that can help me answer this question, with zero responses from anywhere I've posted.  I am trying to understand if the methods provided by codeceptjs allows for the interaction and iteration of html tables.  All very standard stuff that is fairly easily done with other frameworks.  

Can this be done with codeceptjs, or should this be pushed off to a Helper?

I have made a number of attempts at getting this to work and so far, all have failed at some level.  Most recent attempt is shown below via a simple function within a page object of my project (codeceptjs/Puppeteer)

```
async selectSiteById(siteId) {
    I.waitForElement('table');
    let rows = await I.grabAttributeFrom('tbody tr');
    for (let i = 1; i < rows.length; i++) {
      I.say('Current row: ' + i);
      let val = await I.grabTextFrom(
        `tbody tr:nth-child(${i}) td:nth-child(2)`,
      );
      if (val === siteId) {
        I.say('Val: ' + val + ' -- Site Id: ' + siteId);      
        within(`tbody tr:nth-child(${i}) td:nth-child(1)`, () => {
          I.click('input');
        });
      }
    }
  },
```
When I attempt to call this function, I am getting the following.

```
 tableFragment: selectSiteById
      I grab text from "tbody tr:nth-child(1) td:nth-child(2)"
    Emitted | test.after ([object Object])
    Emitted | step.passed (I grab text from "tbody tr:nth-child(1) td:nth-child(2)")
    Emitted | step.finish (I grab text from "tbody tr:nth-child(1) td:nth-child(2)")
    Emitted | step.before (I grab text from "tbody tr:nth-child(2) td:nth-child(2)")
    Emitted | step.after (I grab text from "tbody tr:nth-child(2) td:nth-child(2)")
    Emitted | step.comment (Val: IDH -- Site Id: IDH)
   Val: IDH -- Site Id: IDH
    [1] Starting <within> session
    Emitted | step.before (I click "input")
    Emitted | step.after (I click "input")
    [1] <within> Error | TypeError: Cannot read property '$$' of null
    Emitted | step.failed (I click "input")
    Emitted | step.finish (I click "input")
    [1] <within> Error | TypeError: Cannot read property '$$' of null
    [1] <within> Error | TypeError: Cannot read property '$$' of null
    Emitted | step.failed (I grab text from "tbody tr:nth-child(2) td:nth-child(2)")
    Emitted | step.finish (I grab text from "tbody tr:nth-child(2) td:nth-child(2)")
(node:19928) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '$$' of null
    at findElements (C:\projects\csPptr\ipt\node_modules\codeceptjs\lib\helper\Puppeteer.js:2189:42)
    at Puppeteer._locate (C:\projects\csPptr\ipt\node_modules\codeceptjs\lib\helper\Puppeteer.js:776:12)
    at async Puppeteer._withinBegin (C:\projects\csPptr\ipt\node_modules\codeceptjs\lib\helper\Puppeteer.js:555:17)
(node:19928) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with 
.catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:19928) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
    Emitted | suite.after ([object Object])
    [1] <within> Error | TypeError: Cannot read property '$$' of null
    Emitted | test.failed ([object Object])
  × "after all" hook: codeceptjs.afterSuite for "More goofing around" in 2ms
    [1] <within> Error | TypeError: Cannot read property '$$' of null
TypeError: Cannot read property '$$' of null

-- FAILURES:

  1) Sandbox to play around in
       "after all" hook: codeceptjs.afterSuite for "More goofing around":
     Cannot read property '$$' of null
  ypeError: Cannot read property '$$' of null
      at findElements (node_modules\codeceptjs\lib\helper\Puppeteer.js:2189:42)
      at Puppeteer._locate (node_modules\codeceptjs\lib\helper\Puppeteer.js:776:12)
      at async Puppeteer._withinBegin (node_modules\codeceptjs\lib\helper\Puppeteer.js:555:17)


  FAIL  | 1 passed, 1 failed   // 8s
    Emitted | global.result ([object Object])
    Emitted | global.after ([object Object])
```

After struggling with this for 'way too long' I have tried to implement a VERY basic Helper function that will ultimately hold various table operations.

I have started with a simple function to try and grab the total number of rows in the table body of a given page.

Code of my helper class shown below.

I am not sure if my 'require' declarations at the top of the page are correct as the documentation showed differently than what the npx command generated when I built the class.

```
// const { Helper } = codeceptjs;
const Helper = codecept_helper;
const puppeteer = require('puppeteer');

class TableHelper extends Helper {

  // add custom methods here
  // If you need to access other helpers
  // use: this.helpers['helperName']
  getRowCount() {
    const { page } = this.helpers.Puppeteer;

    const tableRows = 'tbody tr'
    const rowCount = page.$$eval(tableRows, (e) => e.length)
      
    return rowCount.length;
  }

}

module.exports = TableHelper;
```

Possibly I am not yet totally familiar with exactly how promises work in Javascript and part of my issue is with getting the value back.

If anyone could assist me in / point me in the right direction for how to successfully interact with tables, I would SO hugely appreciated it.

**Comment by boursawb** [comment]
After many trials and mistakes on my part, this is actually quite easy to do and works well.

Here is what I've come up with.  If others have suggestions for how this can be improved, I am always open to that.

**Locate a row, tick a check box in col1 of identified row**

```
    async selectSiteById(siteId) {
        // Get total number of rows in table (body)
        const totalRows = await I.grabAttributeFrom('tbody tr');
        
        //  Loop through all rows of the table
        for (let i = 0; i < totalRows.length; i++) {
    
          // Get the value of the site ID and store to str
          let str = await I.grabTextFrom(`tbody tr:nth-child(${i+1}) td:nth-child(2)`);
    
          // Click the checkbox in col1 for the identified row
          if (str === siteId) {
            within(`tbody tr:nth-child(${i+1}) td:nth-child(1) span span`, () => {
              I.click('input');
            })
          }
        }
      },
```
