### ISSUE TITLE
Could not load helper TestCafe from module './helper/TestCafe'

### ISSUE THREAD

**Issue by Benyon** [codeceptjs/CodeceptJS#2604]
#### I get the following error.

```bash
jordanbenyon@Jordans-MBP codeceptJStestcafe % npx codeceptjs init   

  Welcome to CodeceptJS initialization tool
  It will prepare and configure a test environment for you

Installing to /Users/jordanbenyon/Desktop/Dev Workspace/Automation/projects/codeceptJStestcafe
? Where are your tests located? ./*_test.js
? What helpers do you want to use? TestCafe
? Where should logs, screenshots, and reports to be stored? ./output
? Do you want localization for tests? (See https://codecept.io/translation/) English (no localization)
Error: Cannot find module 'qrcode-terminal'
Configure helpers...

Steps file created at ./steps_file.js
Config created at /Users/jordanbenyon/Desktop/Dev Workspace/Automation/projects/codeceptJStestcafe/codecept.conf.js
Directory for temporary output files created at './output'
Intellisense enabled in /Users/jordanbenyon/Desktop/Dev Workspace/Automation/projects/codeceptJStestcafe/jsconfig.json
(node:44418) UnhandledPromiseRejectionWarning: Error: Could not load helper TestCafe from module './helper/TestCafe':
Cannot find module 'qrcode-terminal'
Error: Cannot find module 'qrcode-terminal'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/Users/jordanbenyon/Desktop/Dev Workspace/Automation/projects/codeceptJStestcafe/node_modules/codeceptjs/lib/helper/TestCafe.js:5:16)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at createHelpers (/Users/jordanbenyon/Desktop/Dev Workspace/Automation/projects/codeceptJStestcafe/node_modules/codeceptjs/lib/container.js:166:13)
    at Function.create (/Users/jordanbenyon/Desktop/Dev Workspace/Automation/projects/codeceptJStestcafe/node_modules/codeceptjs/lib/container.js:42:25)
    at Codecept.init (/Users/jordanbenyon/Desktop/Dev Workspace/Automation/projects/codeceptJStestcafe/node_modules/codeceptjs/lib/codecept.js:56:15)
    at module.exports (/Users/jordanbenyon/Desktop/Dev Workspace/Automation/projects/codeceptJStestcafe/node_modules/codeceptjs/lib/command/definitions.js:42:12)
    at finish (/Users/jordanbenyon/Desktop/Dev Workspace/Automation/projects/codeceptJStestcafe/node_modules/codeceptjs/lib/command/init.js:194:7)
    at inquirer.prompt.then (/Users/jordanbenyon/Desktop/Dev Workspace/Automation/projects/codeceptJStestcafe/node_modules/codeceptjs/lib/command/init.js:228:7)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:44418) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:44418) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

### Details

* CodeceptJS version: 2.6.11
* NodeJS Version: v10.22.1 (also tried with latest)
* Operating System: MacOS Catalina V10.15.6
* Configuration file: not set up

**Comment by brunoklein** [comment]
Hello @Benyon 

> Error: Cannot find module 'qrcode-terminal'

It seems you don't have the module `qrcode-terminal` installed.

So, run `npm install qrcode-terminal` and then `npx codeceptjs init`
Let me know if it works.

Sincerely,
Bruno Klein

**Comment by brunoklein** [comment]
Hello @Benyon 

> Error: Cannot find module 'qrcode-terminal'

It seems you don't have the module `qrcode-terminal` installed.

Try to run:

1. `npm init -y`
2. `npm install qrcode-terminal`
3. `npx codeceptjs init`

Let me know if it works.

Sincerely,
Bruno Klein
