### ISSUE TITLE
You are using webdriverio v5. It is recommended to update to webdriverio@6. Support of webdriverio v5 is deprecated and will be removed in CodeceptJS 3.0

### ISSUE THREAD

**Issue by sanketharad** [codeceptjs/CodeceptJS#2610]
#### What are you trying to achieve?
I am trying to configure Appium. I have followed all the steps mentioned on the link below
https://codecept.io/mobile/

#### What do you get instead?
I am facing the webdriverio version issue even after upgrading the webdriverio version

> Provide console output if related. Use `--verbose` mode for more details.
npm install webdriverio --save-dev   
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

+ webdriverio@6.5.2

npx codeceptjs run
DEPRECATION NOTICE:
You are using webdriverio v5. It is recommended to update to webdriverio@6.
Support of webdriverio v5 is deprecated and will be removed in CodeceptJS 3.0

CodeceptJS v3.0.0
Using test root "C:\POCM"

2020-10-06T05:54:11.813Z ERROR webdriver: Request failed due to Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:205:27)
2020-10-06T05:54:11.818Z ERROR webdriver: Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:205:27)
  × "before each" hook: codeceptjs.before for "test something" in 8291ms
Error: Can't connect to WebDriver.
Error: Failed to create session.
read ECONNRESET

Please make sure Selenium Server (ChromeDriver or PhantomJS) is running and accessible

```bash
# paste output here
```

> Provide test source code if related

```js
// paste test
```

### Details

* CodeceptJS version:
* NodeJS Version:
* Operating System:
* puppeteer || webdriverio || protractor || testcafe version (if related)
* Configuration file:

```js
# paste config here
```
const { setHeadlessWhen } = require('@codeceptjs/configure');

// turn on headless mode when running with HEADLESS=true environment variable
// export HEADLESS=true && npx codeceptjs run
setHeadlessWhen(process.env.HEADLESS);

exports.config = {
  tests: './*_test.js',
  output: './output',
  helpers: {
    Appium: {
      app: 'http://localhost',
      platform: 'Android',
      device: 'emulator'
    }
  },
  include: {
    I: './steps_file.js'
  },
  bootstrap: null,
  mocha: {},
  name: 'POCM',
  plugins: {
    pauseOnFail: {},
    retryFailedStep: {
      enabled: true
    },
    tryTo: {
      enabled: true
    },
    screenshotOnFail: {
      enabled: true
    }
  }
}

**Comment by prabhushan** [comment]
Hi,

Even i am facing the same issue for Codecept 3.0 with webdriver.

{
    "name": "codeceptjs-tests",
    "version": "0.1.0",
    "private": true,
    "scripts": {
        "codeceptjs": "codeceptjs run --steps",
        "codeceptjs:headless": "HEADLESS=true codeceptjs run --steps",
        "codeceptjs:ui": "codecept-ui --app",
        "codeceptjs:demo": "codeceptjs run --steps -c node_modules/@codeceptjs/examples",
        "codeceptjs:demo:headless": "HEADLESS=true codeceptjs run --steps -c node_modules/@codeceptjs/examples",
        "codeceptjs:demo:ui": "codecept-ui --app  -c node_modules/@codeceptjs/examples"
    },
    "devDependencies": {
        "@codeceptjs/configure": "github:codeceptjs/configure",
        "@codeceptjs/examples": "^1.2.1",
        "@codeceptjs/ui": "^0.4.1",
        "@wdio/cli": "^6.3.6",
        "@wdio/selenium-standalone-service": "^6.6.2",
        "codeceptjs": "^3.0.0",
        "playwright": "^1.4.2",
        "webdriverio": "^6.6.2"
    },
    "dependencies": {
        "webdriverio": "^6.6.2"
    }
}


When I do 
**npx codeceptjs run**
DEPRECATION NOTICE:
You are using webdriverio v5. It is recommended to update to webdriverio@6.
Support of webdriverio v5 is deprecated and will be removed in CodeceptJS 3.0

(node:91601) UnhandledPromiseRejectionWarning: Error: Could not load plugin wdio from module './plugin/wdio':
Cannot read property 'outputDir' of undefined

**Comment by ptmkenny** [comment]
I'm getting the same error message with webdriverio v7 as well.

**Comment by kobenguyent** [comment]
Closed for now! Feel free to reopen if you still encounter the issue with latest version and would be nice to provide a sample code to reproduce the issue.
