### ISSUE TITLE
CodeceptUI start failed:Cannot find module 'uuid/v4'

### ISSUE THREAD

**Issue by arcsun** [codeceptjs/CodeceptJS#2618]
#### What are you trying to achieve?
npx create-codeceptjs .
npm run codeceptjs:demo:ui

#### What do you get instead?
UnhandledPromiseRejectionWarning: Error: Cannot find module 'uuid/v4'

> Provide console output if related. Use `--verbose` mode for more details.

```bash
Creating CodeceptJS project in /Users/sun/uitest/codecept-v3-test

Powered by Playwright engine
package.json file does not exist in current dir, creating it...
Installing packages:  codeceptjs@3.0.0, @codeceptjs/ui, @codeceptjs/examples, @codeceptjs/configure, playwright@1

> playwright@1.5.0 install /Users/sun/uitest/codecept-v3-test/node_modules/playwright
> node install.js


> core-js@3.6.5 postinstall /Users/sun/uitest/codecept-v3-test/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"


> electron@7.3.3 postinstall /Users/sun/uitest/codecept-v3-test/node_modules/electron
> node install.js

Downloading electron-v7.3.3-darwin-x64.zip: [==============================================] 100% ETA: 0.0 seconds
+ @codeceptjs/ui@0.4.1
+ playwright@1.5.0
+ @codeceptjs/configure@0.6.0
+ @codeceptjs/examples@1.2.1
+ codeceptjs@3.0.0
added 641 packages from 475 contributors and audited 640 packages in 6652.701s

46 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

Finished installing packages.

What's next?

Try CodeceptJS now with a demo project:
➕ npm run codeceptjs:demo - executes codeceptjs tests for a demo project
➕ npm run codeceptjs:demo:headless - executes codeceptjs tests headlessly (no window shown)
➕ npm run codeceptjs:demo:ui - starts codeceptjs UI application for a demo project

Initialize CodeceptJS for your project:
🔨 npx codeceptjs init - initialize codeceptjs for current project (required)
➕ npm run codeceptjs - runs codeceptjs tests for current project
➕ npm run codeceptjs:headless - executes codeceptjs tests headlessly (no window shown)
➕ npm run codeceptjs:ui - starts codeceptjs UI application for current project

IT-C02YD3E8JHD2:codecept-v3-test sun$ npm run codeceptjs:demo:ui

> codeceptjs-tests@0.1.0 codeceptjs:demo:ui /Users/sun/uitest/codecept-v3-test
> codecept-ui --app  -c node_modules/@codeceptjs/examples

(node:72042) UnhandledPromiseRejectionWarning: Error: Cannot find module 'uuid/v4'
Require stack:
- /Users/sun/uitest/codecept-v3-test/node_modules/@codeceptjs/ui/lib/codeceptjs/console-recorder.helper.js
- /Users/sun/uitest/codecept-v3-test/node_modules/@codeceptjs/ui/lib/model/codeceptjs-factory.js
- /Users/sun/uitest/codecept-v3-test/node_modules/@codeceptjs/ui/lib/commands/init.js
- /Users/sun/uitest/codecept-v3-test/node_modules/@codeceptjs/ui/bin/codecept-ui.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:780:15)
    at Function.Module._load (internal/modules/cjs/loader.js:685:27)
    at Module.require (internal/modules/cjs/loader.js:838:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/sun/uitest/codecept-v3-test/node_modules/@codeceptjs/ui/lib/codeceptjs/console-recorder.helper.js:3:14)
    at Module._compile (internal/modules/cjs/loader.js:945:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:962:10)
    at Module.load (internal/modules/cjs/loader.js:798:32)
    at Function.Module._load (internal/modules/cjs/loader.js:711:12)
    at Module.require (internal/modules/cjs/loader.js:838:19)
(node:72042) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:72042) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

**Comment by arcsun** [comment]
I modified console-recorder.helper.js：
replace
_const uuid = require('uuid/v4');_
with
_const uuid = require('uuid');_

and run 
_npm install uuid_
and then it works.

**Comment by gulench** [comment]
Looks like an incompatible version of `uuid` is getting pulled in by the test project.

`@codeceptjs/ui` launches if you pin the `uuid` dependency in the test project, to a version compatible with `@codeceptjs/ui`. However, this sounds like a workaround; we should be addressing the “dependency incompatibilities” overall.

Refer issue https://github.com/codeceptjs/ui/issues/91:

https://github.com/codeceptjs/ui/blob/f95c86c0d33fe61c7d12b26b98a2f60b3b8f5715/package.json#L67

```json
    "uuid": "^3.4.0",
```

**Comment by henzlmarek** [comment]
replacing in console-recorder.helper.js works
// const uuid = require('uuid/v4');
const { v4: uuidv4 } = require('uuid');

see:
https://stackoverflow.com/questions/62549457/error-err-package-path-not-exported-package-subpath-v4-is-not-defined-by

**Comment by DavertMik** [comment]
Thanks, I will update codeceptui
