### ISSUE TITLE
Mocha TypeError when running test

### ISSUE THREAD

**Issue by balsigergil** [codeceptjs/CodeceptJS#2623]
#### What are you trying to achieve?

Run test with :
`npx codeceptjs run search_test.js`

#### What do you get instead?

> Provide console output if related. Use `--verbose` mode for more details.

```bash
TypeError: Cannot set property id of #<Test> which has only a getter
    at /home/gil/dev/heig/amt/OverFlow/e2e/node_modules/codeceptjs/lib/mochaFactory.js:53:46
    at Array.forEach (<anonymous>)
    at Suite.eachTest (/home/gil/dev/heig/amt/OverFlow/e2e/node_modules/mocha/lib/suite.js:438:14)
    at /home/gil/dev/heig/amt/OverFlow/e2e/node_modules/mocha/lib/suite.js:440:11
    at Array.forEach (<anonymous>)
    at Suite.eachTest (/home/gil/dev/heig/amt/OverFlow/e2e/node_modules/mocha/lib/suite.js:439:15)
    at Mocha.mocha.loadFiles (/home/gil/dev/heig/amt/OverFlow/e2e/node_modules/codeceptjs/lib/mochaFactory.js:53:21)
    at Mocha.run (/home/gil/dev/heig/amt/OverFlow/e2e/node_modules/mocha/lib/mocha.js:970:10)
    at /home/gil/dev/heig/amt/OverFlow/e2e/node_modules/codeceptjs/lib/codecept.js:170:15
    at new Promise (<anonymous>)

Cannot set property id of #<Test> which has only a getter

TypeError: 
    at /home/gil/dev/heig/amt/OverFlow/e2e/node_modules/codeceptjs/lib/mochaFactory.js:53:46
    at Array.forEach (<anonymous>)
    at Suite.eachTest (/home/gil/dev/heig/amt/OverFlow/e2e/node_modules/mocha/lib/suite.js:438:14)
    at /home/gil/dev/heig/amt/OverFlow/e2e/node_modules/mocha/lib/suite.js:440:11
    at Array.forEach (<anonymous>)
    at Suite.eachTest (/home/gil/dev/heig/amt/OverFlow/e2e/node_modules/mocha/lib/suite.js:439:15)
    at Mocha.mocha.loadFiles (/home/gil/dev/heig/amt/OverFlow/e2e/node_modules/codeceptjs/lib/mochaFactory.js:53:21)
    at Mocha.run (/home/gil/dev/heig/amt/OverFlow/e2e/node_modules/mocha/lib/mocha.js:970:10)
    at /home/gil/dev/heig/amt/OverFlow/e2e/node_modules/codeceptjs/lib/codecept.js:170:15
    at new Promise (<anonymous>)
```

> Provide test source code if related

Content of `search_test.js`:

```js
Feature('search');

Scenario('test search title', ({ I }) => {
    I.amOnPage('/')
    I.fillField('s', 'question 2')
    I.click('Search')
    I.see('Question 2')
    I.see('Contenu 2')
    I.dontSee('Question 1')
    I.dontSee('Contenu 1')
    I.dontSee('Question 3')
    I.dontSee('Contenu 3')
});

Scenario('test search author', ({ I }) => {
    I.amOnPage('/')
    I.fillField('s', 'gil')
    I.click('Search')
    I.see('Question 1')
    I.see('Contenu 1')
    I.dontSee('Question 2')
    I.dontSee('Contenu 2')
    I.dontSee('Question 3')
    I.dontSee('Contenu 3')
});

```

### Details

* CodeceptJS version: 3.0.0
* NodeJS Version: 12.18.4
* Operating System: Manjaro Linux
* Using Playwright 1.5.1

<details>
  <summary>Configuration file</summary>

```js
const { setHeadlessWhen } = require('@codeceptjs/configure');

// turn on headless mode when running with HEADLESS=true environment variable
// export HEADLESS=true && npx codeceptjs run
setHeadlessWhen(process.env.HEADLESS);

exports.config = {
  tests: './*_test.js',
  output: './output',
  helpers: {
    Playwright: {
      url: 'http://localhost:9080/overflow',
      show: true,
      browser: 'chromium'
    }
  },
  include: {
    I: './steps_file.js'
  },
  bootstrap: null,
  mocha: {},
  name: 'e2e',
  translation: 'fr-FR',
  plugins: {
    pauseOnFail: {},
    retryFailedStep: {
      enabled: true
    },
    tryTo: {
      enabled: true
    },
    screenshotOnFail: {
      enabled: true
    }
  }
}
```

</details>

**Comment by lukyth** [comment]
I have this same error as well, with the project that I just setup an hour ago. I fixed this by adding `mocha` to `package.json` as well, with the version pin to `"mocha": "8.1.3",`, so I think this is more likely a Mocha's issue than CodeceptJS.

**Comment by golfzaptw** [comment]
I found this same error as well, and I add dependency as @lukyth recommends and it already works for me. But when I using the command `codeceptjs dry-run` It still the same error `TypeError: Cannot set property id of #<Test> which has only a getter`

**Comment by golfzaptw** [comment]
But why am I not using mocha but I found this problem?

**Comment by PeterNgTr** [comment]
Codeceptjs uses mocha in the core afaik.

**Comment by vitaliisotnichenko** [comment]
the same error, especially when create a new project and on CI as well

**Comment by vitaliisotnichenko** [comment]
and it's starting from Saturday, because on Friday everything was working

**Comment by lucasbit** [comment]
I have experienced that on Friday around 14.00 Olso time. While performing instructions about"Quickstart" with Playwright posted on Codecept home page. Env: Node 12.19.0 Windows 10.
![image](https://user-images.githubusercontent.com/29520131/96447930-f5f33480-1212-11eb-93ea-8866fabf75a3.png)

**Comment by suryap666** [comment]
I also faced the same issue as above

**Comment by balsigergil** [comment]
## Quick fix

Open your `package.json` and specify explicitly the version **8.1.3** of Mocha :

```json
{
    "name": "codeceptjs-tests",
    "version": "0.1.0",
    "private": true,
    "scripts": {
        "codeceptjs": "codeceptjs run --steps",
        "codeceptjs:headless": "HEADLESS=true codeceptjs run --steps",
        "codeceptjs:ui": "codecept-ui --app"
    },
    "devDependencies": {
        "@codeceptjs/configure": "^0.6.0",
        "@codeceptjs/examples": "^1.2.1",
        "@codeceptjs/ui": "^0.4.1",
        "codeceptjs": "^3.0.0",
        "playwright": "^1.5.1",
        "mocha": "8.1.3"
    }
}
```

Apparently the bug occurs with the update of Mocha 8.2.0.

**Comment by PeterNgTr** [comment]
Codeceptjs v3.0.1 would be fixed that issue.
