### ISSUE TITLE
TypeError: Cannot set property id of #<Test> which has only a getter

### ISSUE THREAD

**Issue by npirotte** [codeceptjs/CodeceptJS#2647]
#### What are you trying to achieve?

After initializing a CodeceptJS project, when trying to run the tests, I have an exception (see below)

#### What do you get instead?

```bash
TypeError: Cannot set property id of #<Test> which has only a getter
    at {root}/node_modules/codeceptjs/lib/mochaFactory.js:53:46
    at Array.forEach (<anonymous>)
    at Suite.eachTest ({root}/node_modules/mocha/lib/suite.js:438:14)
    at {root}/node_modules/mocha/lib/suite.js:440:11
    at Array.forEach (<anonymous>)
    at Suite.eachTest ({root}/node_modules/mocha/lib/suite.js:439:15)
    at Mocha.mocha.loadFiles ({root}/node_modules/codeceptjs/lib/mochaFactory.js:53:21)
    at CodeceptjsFactory.reloadSuites ({root}/node_modules/@codeceptjs/ui/lib/model/codeceptjs-factory.js:141:11)
    at Object.reloadSuites ({root}/node_modules/@codeceptjs/ui/lib/model/scenario-repository.js:217:30)
    at module.exports ({root}/node_modules/@codeceptjs/ui/lib/api/list-scenarios.js:9:22)

```

### Details

* CodeceptJS version: 3.0.0
* NodeJS Version: 14.3.0
* Operating System: OSX 10.15.5
* Configuration file:

```js
const { setHeadlessWhen } = require('@codeceptjs/configure');

// turn on headless mode when running with HEADLESS=true environment variable
// export HEADLESS=true && npx codeceptjs run
setHeadlessWhen(process.env.HEADLESS);

exports.config = {
  tests: './tests/*_test.js',
  output: './output',
  helpers: {
    Puppeteer: {
      url: 'http://localhost',
      show: true,
      windowSize: '1200x900'
    }
  },
  include: {
    I: './steps_file.js'
  },
  bootstrap: null,
  mocha: {},
  name: 'hello-codecept',
  plugins: {
    pauseOnFail: {},
    retryFailedStep: {
      enabled: true
    },
    tryTo: {
      enabled: true
    },
    screenshotOnFail: {
      enabled: true
    }
  }
}
```

**Comment by PeterNgTr** [comment]
@npirotte please upgrade your codeceptjs 3.0.1

**Comment by npirotte** [comment]
Hi @PeterNgTr  It's working thanks.

It's strange that I got that issue using `create-codeceptjs` command this morning, maybe worth checking if this module is up to date :) 

Cheers

**Comment by bitcoder** [comment]
me too @npirotte .. I just installed codeceptjs and used npx.. .and then tried to run the demo code

**Comment by bitcoder** [comment]
with 3.0.1 it works.. maybe the template is being created with wrong package dependency..

**Comment by gianpaj** [comment]
upgrading from 3.0.0 to 3.0.1, fixed it for me
