### ISSUE TITLE
Run browser parallelization tests

### ISSUE THREAD

**Issue by javiergarciacotado** [codeceptjs/CodeceptJS#2661]
#### What are you trying to achieve?

Run tests against multiple browsers through Browserstack. 
For tests execution, we need to load a browser extension.

#### What do you get instead?

```
(node:27988) UnhandledPromiseRejectionWarning: Error: spawn ENAMETOOLONG
    at ChildProcess.spawn (internal/child_process.js:407:11)
    at spawn (child_process.js:553:9)
    at fork (child_process.js:121:10)
    at Command.<anonymous> (D:\workspace\infinity-e2e-test\ui\node_modules\codeceptjs\lib\command\run-multiple.js:177:16)
    at D:\workspace\infinity-e2e-test\ui\node_modules\codeceptjs\lib\command\run-multiple.js:102:54
    at Array.forEach (<anonymous>)
    at Command.module.exports (D:\workspace\infinity-e2e-test\ui\node_modules\codeceptjs\lib\command\run-multiple.js:102:17)
(node:27988) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting
 a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/
api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:27988) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with
a non-zero exit code.
```

> Provide console output if related. Use `--verbose` mode for more details.

```bash
> npm run build && npm run clean:dist && cross-env HOST=10.120.187.94 MULTI=true BROWSERSTACK_USERNAME='<aUser>' BROWSERSTACK_ACCESS_KEY='<aPassword>' codeceptjs ru
n-multiple --all --config ./config/browsers/browserstack/codecept.browserstack.parallel.conf.js --grep @functional
```

> Provide test source code if related

```js
// paste test
```

### Details

* CodeceptJS version: 3.0.1
* NodeJS Version: 12.19.0
* Operating System: Windows 10
* puppeteer || webdriverio || protractor || testcafe version (if related) : WebdriverIO
* Configuration file: codecept.browserstack.parallel.conf.js

```js
const merge = require('deepmerge');
const fs = require('fs');
const codeceptBrowserstack = require('./codecept.browserstack.conf');
const chromeExtension = __dirname + '/../extensions/chrome/browser-extension.crx';
const edgeExtension = __dirname + '/../extensions/edge/browser-extension-edge-1.0.8.crx';

exports.config = merge(codeceptBrowserstack.config,
    {
        helpers: {
            WebDriver: {
                browser: 'dummy'
            }
        },
        multiple: {
            all: {
                browsers: [
                    {
                        browser: 'chrome',
                        desiredCapabilities: {
                            browserName: 'chrome',
                            browserVersion: process.env.CHROME_VERSION || 'BROWSER_VERSION',
                            chromeOptions: {
                                extensions: [
                                    fs.readFileSync(chromeExtension).toString('base64')
                                ]
                            }
                        }
                    },
                    {
                        browser: 'firefox',
                        desiredCapabilities: {
                            browserName: 'firefox',
                            browserVersion: process.env.FIREFOX_VERSION || 'BROWSER_VERSION',
                        }
                    },
                    {
                        browser: 'edge',
                        desiredCapabilities: {
                            browserName: 'edge',
                            browserVersion: process.env.EDGE_VERSION || 'BROWSER_VERSION',
                            'browserstack.selenium_version': '3.141.59',
                            'browserstack.use_w3c': 'true',
                            'ms:edgeOptions': {
                                "extensions": [
                                    fs.readFileSync(edgeExtension).toString('base64')
                                ]
                            }
                        }
                    },
                    {
                        browser: 'ie',
                        desiredCapabilities: {
                            browserName: 'ie',
                            browserVersion: process.env.IE_VERSION || 'BROWSER_VERSION',
                            'browserstack.selenium_version': '3.5.2',
                            'browserstack.ie.enablePopups': 'true',
                        }
                    }
                ]
            }
        }
    },
    {
        clone: false
    }
);
```

**Comment by kobenguyent** [comment]
please check https://codecept.io/parallel/#parallel-execution-by-workers-on-multiple-browsers
