### ISSUE TITLE
codeceptjs wdio services (image comparision) integration

### ISSUE THREAD

**Issue by khanzzirfan** [codeceptjs/CodeceptJS#2702]
#### What are you trying to achieve?
Trying to integrate wdio-image-comparision-service within in codeceptjs plugins (wdio)

#### What do you get instead?
Error. Cannot run the tests. See below console output

> Provide console output if related. Use `--verbose` mode for more details.

```bash
> client@0.1.0 start C:\code\bitbuckets\VineaNova\VineaNovaWebProject   
> nps "e2e.chrome"     
   
nps is executing `e2e.chrome` : npx codeceptjs run --verbose --features --profile chrome 
   
Could not load plugin wdio from module './plugin/wdio':   
name.toLowerCase is not a function    
   
Error:    
 at createPlugins (C:\code\bitbuckets\VineaNova\VineaNovaWebProject\node_modules\codeceptjs\lib\container.js:275:13) 
 at Function.create (C:\code\bitbuckets\VineaNova\VineaNovaWebProject\node_modules\codeceptjs\lib\container.js:45:25)    
 at Codecept.init (C:\code\bitbuckets\VineaNova\VineaNovaWebProject\node_modules\codeceptjs\lib\codecept.js:56:15)    
 at Command.module.exports (C:\code\bitbuckets\VineaNova\VineaNovaWebProject\node_modules\codeceptjs\lib\command\run.js:27:14) 
 at Command.listener (C:\code\bitbuckets\VineaNova\VineaNovaWebProject\node_modules\commander\index.js:315:8) 
 at Command.emit (events.js:315:20)   
 at Command.parseArgs (C:\code\bitbuckets\VineaNova\VineaNovaWebProject\node_modules\commander\index.js:651:12)   
 at Command.parse (C:\code\bitbuckets\VineaNova\VineaNovaWebProject\node_modules\commander\index.js:474:21)    
 at Object.<anonymous> (C:\code\bitbuckets\VineaNova\VineaNovaWebProject\node_modules\codeceptjs\bin\codecept.js:227:9)  
 at Module._compile (internal/modules/cjs/loader.js:1138:30)  
The script called "e2e.chrome" which runs "npx codeceptjs run --verbose --features --profile chrome" failed with exit code 1 https://github.com/sezna/nps/blob/master/other/ERRORS_AND_WARNINGS.md#failed-with-exit-code 
npm ERR! code ELIFECYCLE   
npm ERR! errno 1    
npm ERR! client@0.1.0 start: `nps "e2e.chrome"`    
npm ERR! Exit status 1     
npm ERR!     
npm ERR! Failed at the client@0.1.0 start script.  

```

### Details

* CodeceptJS version: 3.0.0
* NodeJS Version: 12
* Operating System: windows 10
* puppeteer || webdriverio || protractor || testcafe version (if related) webdriverio
* Configuration file:

```js
const debug = require('debug')('acceptance:config');
const { setHeadlessWhen } = require('@codeceptjs/configure');
const { join } = require('path');

setHeadlessWhen(process.env.HEADLESS);

const WebDriverCommands = require.resolve('../helpers/webdriver-commands.helper.js');
const customMethods = require.resolve('../helpers/custom-methods.js');
const customHelpers = require.resolve('../helpers/custom-helpers.js');

const BROWSER = process.profile || 'chrome';

const conf = {
  helpers: {
    WebDriver: {
      browser: BROWSER,
      smartWait: 5000,
      waitForTimeout: 20000,
      timeouts: {
        implicit: 5000,
        script: 60000,
        'page load': 10000,
      },
    },
    WebDriver_commands: {
      require: WebDriverCommands,
    },
    CustomHelper: {
      require: customHelpers,
    },
    // ResembleHelper: {
    //   require: 'codeceptjs-resemblehelper',
    //   screenshotFolder: '../../../e2e/screenshots/actual/',
    //   baseFolder: '../../../e2e/screenshots/base/',
    //   diffFolder: '../../../e2e/screenshots/diff/',
    //   prepareBaseImage: true,
    // },
  },
  plugins: {
    screenshotOnFail: {
      enabled: true,
    },
    allure: {
      enabled: true,
    },
    autoDelay: {
      enabled: true,
      delayBefore: 400,
    },
    retryFailedStep: {
      enabled: true,
      retries: 5,
    },
    wdio: {
      enabled: true,
      services: [
        'selenium-standalone',
        [
          'image-comparison',
          {
            // Some options, see the docs for more
            baselineFolder: join(process.cwd(), './e2e/screenshots/base/'),
            formatImageName: '{tag}-{logName}-{width}x{height}',
            screenshotPath: join(process.cwd(), './e2e/screenshots/actual/'),
            savePerInstance: true,
            autoSaveBaseline: true,
            blockOutStatusBar: true,
            blockOutToolBar: true,
          },
        ],
      ],
    },
  },
  multiple: {
    parallel: {
      chunks: files => {
        let chunks = [];
        files.forEach(file => {
          chunks.push([file]);
        });
        return chunks;
      },
    },
    smoke: {
      grep: '@smoke',
      browsers: [BROWSER],
    },
  },
  include: {
    I: customMethods,
  },
};

module.exports = conf;

```

The tests start working if I remove the  'image-comparison' from the plugins services setup.

**Comment by DavertMik** [comment]
Sorry, can't help
