### ISSUE TITLE
[Puppteer][IFrame] Doesn't change to Iframe :( 

### ISSUE THREAD

**Issue by conradkirschner** [codeceptjs/CodeceptJS#2735]
#### What are you trying to achieve?
Click on a Element inside a iframe
#### What do you get instead?
Element not found 

```bash
     Clickable element ".btn-accept-all" was not found by text|CSS|XPath
      at new ElementNotFound (node_modules/codeceptjs/lib/helper/errors/ElementNotFound.js:14:11)
      at assertElementExists (node_modules/codeceptjs/lib/helper/Puppeteer.js:2520:11)
      at Puppeteer.proceedClick (node_modules/codeceptjs/lib/helper/Puppeteer.js:2284:5)
  
  Scenario Steps:
  - I.click(".btn-accept-all") at Object.accept (/...../accept-all.ts:21:20)
  - I.switchTo("#sp_message_iframe_398781") at Object.accept (/...../accept-all.ts:18:17)

```

> Provide test source code if related

```js
        const cookieBannerId = await I.grabAttributeFrom('//div/iframe', 'id');
        await I.switchTo( '#'+cookieBannerId);
        await I.click('.btn-accept-all');
```

### Details

* CodeceptJS version: "3.0.2",
* NodeJS Version: v12.20.0
* Operating System: Ubuntu latest
* puppeteer
* Configuration file:
default config for puppteer (from docu)

**Comment by conradkirschner** [comment]
also tried with withIn() but same result... 

when I tried it in pause mode it also doesnt find the element

**Comment by cat-ninja** [comment]
Did you tried to run the test in headless mode?
Some time ago I've had the same issue and when I switched to headless its gone

**Comment by conradkirschner** [comment]
yes tried but didn't worked

**Comment by kobenguyent** [comment]
Closed for now! Feel free to reopen if you still encounter the issue with latest version and would be nice to provide a sample code to reproduce the issue.
