### ISSUE TITLE
codeceptjs-appium integration is failed

### ISSUE THREAD

**Issue by aaccde** [codeceptjs/CodeceptJS#2737]
#### What are you trying to achieve?
Hello! I want to make mobile automation with codeceptjs by using appium.  To do this, I followed the steps below.
-install appium, codeceptjs(helper: Appium), Android studio(for using Emulator).
But when I write npx codeceptjs run to terminal, I am getting the error below. Please help me.

ERROR webdriver: RequestError: write ECONNABORTED
    at ClientRequest.<anonymous> (C:\Users\ademir\IdeaProjects\MobileTesting1\node_modules\got\dist\source\core\index.js:953:111)
    at Object.onceWrapper (events.js:300:26)
    at ClientRequest.emit (events.js:215:7)
    at ClientRequest.EventEmitter.emit (domain.js:475:20)
    at ClientRequest.origin.emit (C:\Users\ademir\IdeaProjects\MobileTesting1\node_modules\@szmarczak\http-timer\dist\source\index.js:39:20)
    at Socket.socketErrorListener (_http_client.js:406:9)
    at Socket.emit (events.js:210:5)
    at Socket.EventEmitter.emit (domain.js:475:20)
    at errorOrDestroy (internal/streams/destroy.js:108:12)
    at onwriteError (_stream_writable.js:446:5)
    at afterWriteDispatched (internal/stream_base_commons.js:150:25)
    at writeGeneric (internal/stream_base_commons.js:141:3)
    at Socket._writeGeneric (net.js:771:11)
    at Socket._write (net.js:783:8)
    at doWrite (_stream_writable.js:431:12)
    at writeOrBuffer (_stream_writable.js:415:5)
    at Socket.Writable.write (_stream_writable.js:305:11)
    at ClientRequest._writeRaw (_http_outgoing.js:295:17)
    at ClientRequest._send (_http_outgoing.js:271:15)
    at ClientRequest.end (_http_outgoing.js:732:10)
Error: Can't connect to WebDriver.
Error: Failed to create session.
write ECONNABORTED

Please make sure Selenium Server (ChromeDriver or PhantomJS) is running and accessible

### Details
codeceptVersion:  "3.0.4"
nodeInfo:  12.13.1
osInfo:  Windows 10

Appium: {
      platform: "Android",
      app: "myapp",
      deviceName: 'pixel_3a',
      deviceId:'emulator-5554',
      desiredCapabilities:{
        "version": "5.6",
        "platformName": "Android",
        "platformVersion": "5.6",
        "deviceName": "pixel_3a",

      },
    }

**Comment by yassineskiba** [comment]
Hello  !
I use CodeceptJS with Appium to test on Android and iOS.

Just to be sure you have all mandatory for appium can you share the information of "appium-doctor --android" and your package.json ?

Thank's !

**Comment by aaccde** [comment]
The problem was caused appPackage in desired capabilities. I fixed as below and it worked.
      appPackage: 'xxx',
      platform: 'Android',
      device: 'emulator-5554',
      automationName: 'UiAutomator',
      platformVersion: 11
 
Thank you:)
