### ISSUE TITLE
[Appium] grabAttributeFrom method can't be used with #id selector

### ISSUE THREAD

**Issue by akapitoha** [codeceptjs/CodeceptJS#2759]
#### What are you trying to achieve?
Trying to use `grabAttributeFrom` method which is present in Appium helper documentation
https://codecept.io/helpers/Appium.html#grabattributefrom

#### What do you get instead?
I see this there is no `grabAttributeFrom` function inside the Appium helper class in codeceptjs: https://github.com/codeceptjs/CodeceptJS/blob/3.x/lib/helper/Appium.js

If use it with id from a native Android app like `I.grabAttributeFrom("#some.app:id/nextBtn", 'enabled')`, then I get error
```
Invalid CSS selector '#some.app:id/nextBtn'. Reason: 'Error: Rule expected but "/" found.'
```

as a workaround this seems to work
`I.grabAttributeFrom("//android.widget.Button[@resource-id='some.app:id/nextBtn']")`

### Details

* CodeceptJS version: 3.0.4
* NodeJS Version: 14.5.2
* Operating System: Mac OS 10.14.6
* appium

**Comment by nlespiaucq** [comment]
Hi,

Same issue with the method `grabNumberOfVisibleElements`, on CodeceptJS version: 3.0.7

It's possible to interact with the #id of the android item with most of the method offered by the framework (ex: `I.tap`, `I.seeElement`, etc.) except following methods: `grabNumberOfVisibleElements`, `grabAttributeFrom`.

**Error:**
![image](https://user-images.githubusercontent.com/87313129/127286098-6961213f-1b90-46ac-beb6-34493dcdc403.png)

**Stacktrace:**
```
     Appium error: Locator Strategy 'css selector' is not supported for this session
      at Object.getErrorFromResponseBody (node_modules/webdriver/build/utils.js:94:12)
      at WebDriverRequest._request (node_modules/webdriver/build/request.js:133:31)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at Browser.wrapCommandFn (node_modules/@wdio/utils/build/shim.js:58:29)
      at Browser.$$ (node_modules/webdriverio/build/commands/browser/$$.js:6:17)
      at Browser.wrapCommandFn (node_modules/@wdio/utils/build/shim.js:58:29)
      at Appium._locate (node_modules/codeceptjs/lib/helper/WebDriver.js:804:19)
      at Appium.grabNumberOfVisibleElements (node_modules/codeceptjs/lib/helper/WebDriver.js:1539:17)
```
