### ISSUE TITLE
Codeceptjs test fails after executing I.usePlaywrightTo Function 

### ISSUE THREAD

**Issue by gurjeetbains** [codeceptjs/CodeceptJS#2761]
#### What are you trying to achieve?
I am trying to use I.usePlaywrightTo function in my test, but it fails even if the function is successfully able to do it's task

#### What do you get instead?

> Provide console output if related. Use `--verbose` mode for more details.

```bash
t827923@mac20200301 Digital_Automation_Test_Framework % npm run test

> code3@1.0.0 test /Users/t827923/Desktop/Digital_Automation_Test_Framework
> codeceptjs run --grep @toDebug

CodeceptJS v3.0.4
Using test root "/Users/t827923/Desktop/Digital_Automation_Test_Framework"
Helpers: ChaiWrapper, Playwright
Plugins: screenshotOnFail, retryFailedStep, tryTo, allure, stepByStepReport

TC_Demo --
    [1]  Starting recording promises
  TC_Demo @toDebug
    I am on page "https://www.rahulshettyacademy.com/AutomationPractice/"
    › Screenshot is saving to /Users/t827923/Desktop/Digital_Automation_Test_Framework/output/record_6eb207fa2b9a43683e128d4227ae4124/0000.png
    I use playwright to "Trying my code", async ({ page }) => {
        // Click text=/.*Radio2.*/ >> input[name="radioButton"]
        await page.click('text=/.*Radio2.*/ >> input[name="radioButton"]');
        // Click input[placeholder="Type to Select Countries"]
        await page.click('input[placeholder="Type to Select Countries"]');
        // Fill input[placeholder="Type to Select Countries"]
        await page.fill('input[placeholder="Type to Select Countries"]', 'fadsf');
        // Check input[name="checkBoxOption1"]
        await page.check('input[name="checkBoxOption1"]');
    }
    › Screenshot is saving to /Users/t827923/Desktop/Digital_Automation_Test_Framework/output/record_6eb207fa2b9a43683e128d4227ae4124/0001.png
    [1] Retrying... Attempt #2
    [1] Retrying... Attempt #3
    [1] Retrying... Attempt #4
    [1] Retrying... Attempt #5
    [1] Retrying... Attempt #6
    [1] Error | TypeError: arg.toString is not a function
    [1] Error | TypeError: arg.toString is not a function
    [1] Starting <teardown> session
Error processing test.failed event:
TypeError: arg.toString is not a function
    at /Users/t827923/Desktop/Digital_Automation_Test_Framework/node_modules/codeceptjs/lib/step.js:111:20
    at Array.map (<anonymous>)
    at Step.humanizeArgs (/Users/t827923/Desktop/Digital_Automation_Test_Framework/node_modules/codeceptjs/lib/step.js:96:22)
    at Step.toString (/Users/t827923/Desktop/Digital_Automation_Test_Framework/node_modules/codeceptjs/lib/step.js:136:67)
    at persist (/Users/t827923/Desktop/Digital_Automation_Test_Framework/node_modules/codeceptjs/lib/plugin/stepByStepReport.js:178:23)
    at EventEmitter.<anonymous> (/Users/t827923/Desktop/Digital_Automation_Test_Framework/node_modules/codeceptjs/lib/plugin/stepByStepReport.js:112:5)
    at EventEmitter.emit (events.js:327:22)
    at Object.emit (/Users/t827923/Desktop/Digital_Automation_Test_Framework/node_modules/codeceptjs/lib/event.js:143:28)
    at /Users/t827923/Desktop/Digital_Automation_Test_Framework/node_modules/codeceptjs/lib/scenario.js:64:17
    at /Users/t827923/Desktop/Digital_Automation_Test_Framework/node_modules/codeceptjs/lib/recorder.js:227:9
    [1] <teardown> Stopping recording promises
    › <screenshotOnFail> Test failed, try to save a screenshot
    › Screenshot is saving to /Users/t827923/Desktop/Digital_Automation_Test_Framework/output/TC_Demo_@toDebug.failed.png
  ✖ FAILED in 5387ms

    [2]  Starting recording promises

-- FAILURES:
  ✖ "after all" hook: codeceptjs.afterSuite in "TC_Demo" in 5ms
```

> Provide test source code if related

```js
Feature('TC_Demo');
Before(({ I }) => {
    I.amOnPage('https://www.rahulshettyacademy.com/AutomationPractice/');
})

Scenario('TC_Demo', async ({ I }) => {
    await I.usePlaywrightTo('Trying my code', async ({ page }) => {
        // Click text=/.*Radio2.*/ >> input[name="radioButton"]
        await page.click('text=/.*Radio2.*/ >> input[name="radioButton"]');
        // Click input[placeholder="Type to Select Countries"]
        await page.click('input[placeholder="Type to Select Countries"]');
        // Fill input[placeholder="Type to Select Countries"]
        await page.fill('input[placeholder="Type to Select Countries"]', 'fadsf');
        // Check input[name="checkBoxOption1"]
        await page.check('input[name="checkBoxOption1"]');
    })
    pause()
}).tag('@toDebug')
```

### Details

* CodeceptJS version: 3.0.4
* NodeJS Version:
* Operating System:
* playwright version (if related) 1.7.1
* Configuration file:

```js
exports.config = {
  tests: 'tests/**/*_Test.js',
  output: './output',
  helpers: {
    ChaiWrapper : {
      require: "codeceptjs-chai"
    },
    Playwright: {
      url: 'http://localhost',
      show: true,
      browser: 'chromium',
      waitForNavigation: 'load',
      ignoreHTTPSErrors: true,
      restart: true,
      keepCookies: false
    }
  },
  include: {
    I: './steps_file.js'
  },
  bootstrap: null,
  mocha: {
    reporter: 'mocha-multi',
    reporterOptions: {
      "codeceptjs-cli-reporter": {
        stdout: "-",
        options: {
          verbose: true,
          steps: true,
        }
      },
      "mocha-junit-reporter":{
        stdout: "./junitReports/console.log",
        options:{
          mochaFile: './junitReports/results.xml'
        }
      }
    }
  },
  name: 'code3',
  plugins: {
    pauseOnFail: {},
    retryFailedStep: {
      enabled: true
    },
    tryTo: {
      enabled: true
    },
    screenshotOnFail: {
      enabled: true
    },
    allure: {
      enabled: true
    },
    stepByStepReport: {
      enabled: true,
      deleteSuccessful: false
    }
  }
}
```

**Comment by elaichenkov** [comment]
Hey

This issue has been fixed in [1.0.2](https://www.npmjs.com/package/@codeceptjs/helper/v/1.0.2) version
Please, update your dependencies and check it again.

**Comment by gurjeetbains** [comment]
I am already using version 3.0.4 of codecept @elaichenkov ... Not sure if it was fixed in 3.0.2 I presume why it is still coming as a bug in 3.0.4

**Comment by elaichenkov** [comment]
It was fixed in the `helper` [package](https://www.npmjs.com/package/@codeceptjs/helper/v/1.0.2), not in the `codeceptjs`.
So, just update the `helper` package to [1.0.2](https://www.npmjs.com/package/@codeceptjs/helper/v/1.0.2) version and enjoy testing.

If it doesn't work for you, please add your `helper` [package](https://www.npmjs.com/package/@codeceptjs/helper) version

**Comment by PeterNgTr** [comment]
https://github.com/codeceptjs/CodeceptJS/commit/7987f41a092e9ff11e985d1a00435da7292d657d

new release codeceptjs would fix the issue :)
