### ISSUE TITLE
handleDownloads waits for first "download" event before creating the downloadPath folder

### ISSUE THREAD

**Issue by blazarr** [codeceptjs/CodeceptJS#2785]
I posted the requested information below but I did spend some time looking into this issue and stepping through the code. The issue appears to be that the downloadPath folder is not created until the "download" event is received. That means that when I.amInPath is called, we are pointing at a non existent directory, then when I.waitForFile is called an unhanded exception occurs (which is caught) when we attempt to access this location on the file system.

Note that this is not normally an issue whenever you have a download that starts, the event seems to beat the rest of codeceptjs, so its more of a race condition. This is easy to reproduce if you comment out the call to I.click (never initiating the download). This will cause waitForFile to throw an error every time, this error is being caught at line 81 in FileSystem.js but it is not an expected error case. Once this is thrown codecept closes out the browser which then causes the waitForEvent to throw an UnhandledPromiseRejectionWarning because the page it has a handle on was closed prematurely.

Suggestion: I.handleDownloads should create the folder immediately.

#### What are you trying to achieve?
Test should wait for file to download and fail when it does not occur.

#### What do you get instead?
UnhandledPromiseRejectionWarning is thrown, the browser page is close, and codeceptjs exits after the timeout completes.

> Provide console output if related. Use `--verbose` mode for more details.

```bash
# paste output here
```
Note: Swapped local path to "localpath"
(node:16972) UnhandledPromiseRejectionWarning: Error: Page closed
Note: use DEBUG=pw:api environment variable and rerun to capture Playwright logs.
    at Page.waitForEvent (localpath\node_modules\playwright\lib\client\page.js:293:68)
    at Playwright.handleDownloads (localpath\node_modules\codeceptjs\lib\helper\Playwright.js:1040:15)
    at Step.run (localpath\node_modules\codeceptjs\lib\step.js:66:47)
    at localpath\node_modules\codeceptjs\lib\actor.js:117:23

> Provide test source code if related
Code follows the examples
   * I.handleDownloads('downloads/avatar.jpg');
   * I.click('Download Avatar');
   * I.amInPath('output/downloads');
   * I.waitForFile('downloads/avatar.jpg', 5);

```js
// paste test
```

### Details

* CodeceptJS version: 3.0.4
* NodeJS Version: 14.2.0
* Operating System: Windows 10
* Playwright
* Configuration file:

```js
# paste config here
```

**Comment by Elverslane** [comment]
+1

**Comment by kobenguyent** [comment]
Closed for now! Feel free to reopen if you still encounter the issue with latest version and would be nice to provide a sample code to reproduce the issue.

**Comment by blazarr** [comment]
Be honest, did you even read the issue?

I broke it down for you in detail, and I did provide a code sample…
