### ISSUE TITLE
Unable to start codecept because of issue: "ChromeDriver only supports Chrome version 85" even though I have the latest chromedriver

### ISSUE THREAD

**Issue by taher435** [codeceptjs/CodeceptJS#2885]
#### What are you trying to achieve?
Trying to run codecept with `npx codeceptjs run`

#### What do you get instead?

```
SessionNotCreatedError: session not created: This version of ChromeDriver only supports Chrome version 85
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
```
This is my current chromedriver version
```
$ chromeDriver -v
ChromeDriver 91.0.4472.19 (1bf021f248676a0b2ab3ee0561d83a59e424c23e-refs/branch-heads/4472@{#288})
```
Google Chrome version
```
Version 90.0.4430.85 (Official Build) (x86_64)
```

As per [Google's site](https://sites.google.com/a/chromium.org/chromedriver/downloads) I have the latest web driver installed.

**Stack trace**
```
 at Object.checkLegacyResponse (/Users/maverick/Galen/code/galen-cloud-frontend/EUFrontEnd/node_modules/selenium-webdriver/lib/error.js:546:15)
    at parseHttpResponse (/Users/maverick/Galen/code/galen-cloud-frontend/EUFrontEnd/node_modules/selenium-webdriver/lib/http.js:509:13)
    at doSend.then.response (/Users/maverick/Galen/code/galen-cloud-frontend/EUFrontEnd/node_modules/selenium-webdriver/lib/http.js:441:30)
    at process._tickCallback (internal/process/next_tick.js:68:7)
From: Task: WebDriver.createSession()
    at Function.createSession (/Users/maverick/Galen/code/galen-cloud-frontend/EUFrontEnd/node_modules/selenium-webdriver/lib/webdriver.js:769:24)
    at Function.createSession (/Users/maverick/Galen/code/galen-cloud-frontend/EUFrontEnd/node_modules/selenium-webdriver/chrome.js:761:15)
    at createDriver (/Users/maverick/Galen/code/galen-cloud-frontend/EUFrontEnd/node_modules/selenium-webdriver/index.js:170:33)
    at Builder.build (/Users/maverick/Galen/code/galen-cloud-frontend/EUFrontEnd/node_modules/selenium-webdriver/index.js:626:16)
    at Hosted.getNewDriver (/Users/maverick/Galen/code/galen-cloud-frontend/EUFrontEnd/node_modules/protractor/built/driverProviders/driverProvider.js:53:33)
    at Runner.createBrowser (/Users/maverick/Galen/code/galen-cloud-frontend/EUFrontEnd/node_modules/protractor/built/runner.js:195:43)
    at Protractor._startBrowser (/Users/maverick/Galen/code/galen-cloud-frontend/EUFrontEnd/node_modules/codeceptjs/lib/helper/Protractor.js:213:29)
    at Protractor._before (/Users/maverick/Galen/code/galen-cloud-frontend/EUFrontEnd/node_modules/codeceptjs/lib/helper/Protractor.js:241:72)
    at recorder.add (/Users/maverick/Galen/code/galen-cloud-frontend/EUFrontEnd/node_modules/codeceptjs/lib/listener/helpers.js:26:69)
```

### Details

* CodeceptJS version:  2.6.11
* NodeJS Version: 10.16.3
* Operating System: macOS 11.1 (Big Surr)
* protractor version: 5.4.3
* Configuration file: 

```js
{
  tests: './e2e/**/*.e2e-spec.ts',
  output: './e2e-output',
  helpers: {
    Protractor: {
      url: 'http://localhost:4200',
      driver: 'hosted',
      browser: 'chrome',
      rootElement: 'app-root',
      angular: true,
      keepCookies: true, // keep the cookies for all tests
    }
  },
  include: {
    I: './steps_file.js'
  },
  bootstrap: null,
  mocha: {
    reporterOptions: {
      reportDir: "e2e-output",
      inlineAssets: true,
      reportPageTitle: "E2E Test Reports",
      reportTitle: "E2E Test Reports"
    }
  },
  name: 'MyProject',
  plugins: {
    wdio: {
      enabled: true,
      services: ['selenium-standalone']
    },
    retryFailedStep: {
      enabled: true
    },
    screenshotOnFail: {
      enabled: true
    }
  }
};
```

**Comment by khanzzirfan** [comment]
Can you add the below config and give a try again.  Make sure your driver  version exists on online below urls
```
// wdio.conf.js
const drivers = {
  chrome: { version: '89.0.4389.23' }, // https://chromedriver.chromium.org/
  firefox: { version: '0.29.0' }, // https://github.com/mozilla/geckodriver/releases
  chromiumedge: { version: '89.0.774.76' }, // https://developer.microsoft.com/en-us/microsoft-edge/tools/webdriver/
};

```
... plugins
```
 wdio: {
      enabled: true,
      services: ['selenium-standalone'],
      seleniumArgs: { drivers },
      seleniumInstallArgs: { drivers },
    },
    
```
