### ISSUE TITLE
CodeceptJS_SupportObject 'I' and helper object is undefined in event.all.before hook

### ISSUE THREAD

**Issue by mighty98** [codeceptjs/CodeceptJS#2918]
#### What are you trying to achieve?
My framework requires login workflow to be part of event.all.before hook as I need to launch application and login to it before running any testcase For this I can either use bootstrap or create a plugin using events but looks like I cant launch URL or use any functions of 'I' or helpers in these

#### What do you get instead?
'I' or this.helpers.playwright is UNDEFINED
> Provide console output if related. Use `--verbose` mode for more details.
`Error processing global.before event:
TypeError: Cannot read property 'catch' of undefined
    at Object.catchWithoutStop (C:\Users\mr\OneDrive - McAfee\MWG - Repositories\uce_ui_automation\node_modules\codeceptjs\lib\recorder.js:241:30)
    at recordStep (C:\Users\mr\OneDrive - McAfee\MWG - Repositories\uce_ui_automation\node_modules\codeceptjs\lib\actor.js:128:12)
    at Actor.actor.<computed>.actor.<computed> [as amOnPage] (C:\Users\mr\OneDrive - McAfee\MWG - Repositories\uce_ui_automation\node_modules\codeceptjs\lib\actor.js:92:22)
    at loginToDev (C:\Users\mr\OneDrive - McAfee\MWG - Repositories\uce_ui_automation\launcher.js:13:5)
    at EventEmitter.<anonymous> (C:\Users\mr\OneDrive - McAfee\MWG - Repositories\uce_ui_automation\launcher.js:31:9)
    at EventEmitter.emit (events.js:315:20)
    at EventEmitter.emit (domain.js:467:12)
    at Object.emit (C:\Users\mr\OneDrive - McAfee\MWG - Repositories\uce_ui_automation\node_modules\codeceptjs\lib\event.js:145:28)
    at C:\Users\mr\OneDrive - McAfee\MWG - Repositories\uce_ui_automation\node_modules\codeceptjs\lib\codecept.js:177:15
    at new Promise (<anonymous>)
CodeceptJS v3.0.7`

> Provide test source code if related

```
module.exports = function launch(config) {
  event.dispatcher.on(event.all.before, (test) => {
    console.log('--- I am before test --');
    switch (mode) {
      case 'dev':
        loginToDev();
        break;
      case 'integ':
        loginToInteg();
        break;
      case 'preprod':
        loginToPreprod();
        break;
    }
  });
};
```

### Details

* CodeceptJS version: v3.0.7
* Operating System: Windows
* playwright
* Configuration file:

**Comment by DavertMik** [comment]
I is not available in before.all, tests are not even initialized at that point
