### ISSUE TITLE
Job finished successfully with status code 0 when playwright cannot connect to remote wss url

### ISSUE THREAD

**Issue by Xotabu4** [codeceptjs/CodeceptJS#2952]
#### What are you trying to achieve?

Getting 0 exit code, and job finished with success when playwright cannot connect to remote wss url.
Expected job to be failed.
#### What do you get instead?

```bash
e2e_1       | CodeceptJS v3.0.7
e2e_1       | Using test root "/tests"
e2e_1       | Helpers: 
e2e_1       | Plugins: 
e2e_1       | 
e2e_1       | Some test --
e2e_1       | Error: Cannot connect to websocket endpoint.
e2e_1       | 
e2e_1       | Please make sure remote browser is running and accessible.
e2e_1       | (node:116) UnhandledPromiseRejectionWarning: TypeError: input.replace is not a function
e2e_1       |     at MochaJUnitReporter.removeInvalidCharacters (/tests/node_modules/mocha-junit-reporter/index.js:362:16)
e2e_1       |     at MochaJUnitReporter.getTestcaseData (/tests/node_modules/mocha-junit-reporter/index.js:346:20)
e2e_1       |     at MochaJUnitReporter.<anonymous> (/tests/node_modules/mocha-junit-reporter/index.js:234:27)
e2e_1       |     at EventEmitter.emit (events.js:327:22)
e2e_1       |     at EventEmitter.emit (domain.js:467:12)
e2e_1       |     at /tests/node_modules/mocha-multi/mocha-multi.js:200:14
e2e_1       |     at withReplacedStdout (/tests/node_modules/mocha-multi/mocha-multi.js:159:12)
e2e_1       |     at Runner.<anonymous> (/tests/node_modules/mocha-multi/mocha-multi.js:199:7)
e2e_1       |     at Runner.emit (events.js:327:22)
e2e_1       |     at Runner.EventEmitter.emit (domain.js:467:12)
e2e_1       | (Use `node --trace-warnings ...` to show where the warning was created)
e2e_1       | (node:116) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
e2e_1       | (node:116) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
e2e_1 exited with code 0
```

### Details

* CodeceptJS version: 3.0.7
* NodeJS Version:
* Operating System:
* playwright 1.10
* Configuration file:

**Comment by DavertMik** [comment]
Should be fixed in 3.1.0
