### ISSUE TITLE
TypeError: Unable to require file: test/steps.d.ts

### ISSUE THREAD

**Issue by bperel** [codeceptjs/CodeceptJS#2955]
#### What are you trying to achieve?

Running a Codeconcept test suite with TypeScript and Playwright (`npx codeceptjs run -f start`). The error occurs even when I don't have any other file than `steps.d.ts` in my `test` directory.

#### What do you get instead?

> Provide console output if related. Use `--verbose` mode for more details.

```bash
# npx codeceptjs run -f start
TypeError: Unable to require file: test/steps.d.ts
This is usually the result of a faulty configuration or import. Make sure there is a `.js`, `.json` or other executable extension with loader attached before `ts-node` available.
    at getOutput (/myworkspace/myproject/node_modules/ts-node/src/index.ts:817:17)
    at Object.compile (/myworkspace/myproject/node_modules/ts-node/src/index.ts:1111:30)
    at Module.m._compile (/myworkspace/myproject/node_modules/ts-node/src/index.ts:1224:30)
    at Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Object.require.extensions.<computed> [as .ts] (/myworkspace/myproject/node_modules/ts-node/src/index.ts:1228:12)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at /myworkspace/myproject/node_modules/mocha/lib/mocha.js:390:36

Unable to require file: test/steps.d.ts
This is usually the result of a faulty configuration or import. Make sure there is a `.js`, `.json` or other executable extension with loader attached before `ts-node` available.

TypeError: 
    at getOutput (/myworkspace/myproject/node_modules/ts-node/src/index.ts:817:17)
    at Object.compile (/myworkspace/myproject/node_modules/ts-node/src/index.ts:1111:30)
    at Module.m._compile (/myworkspace/myproject/node_modules/ts-node/src/index.ts:1224:30)
    at Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Object.require.extensions.<computed> [as .ts] (/myworkspace/myproject/node_modules/ts-node/src/index.ts:1228:12)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at /myworkspace/myproject/node_modules/mocha/lib/mocha.js:390:36

```

> Provide test source code if related

Generated `steps.d.ts` in the `test` directory:
```
/// <reference types='codeceptjs' />

declare namespace CodeceptJS {
  interface SupportObject {
    I: I
    current: any
  }
  interface Methods extends Playwright {}
  interface I extends WithTranslation<Methods> {}
  namespace Translation {
    interface Actions {}
  }
}

```

### Details

* CodeceptJS version: 3.0.7
* NodeJS Version: v12.22.2
* Operating System: Ubuntu
* Playwright version: 1.12.3
* Typescript version: 4.3.5
* Configuration file:
```js
require('ts-node/register')

exports.config = {
  tests: './test/*.ts',
  output: './test/output',
  helpers: {
    Playwright: {
      url: 'http://localhost:3000',
      show: true,
      browser: 'firefox',
    },
  },
  bootstrap: null,
  mocha: {},
  name: 'myproject',
  plugins: {
    pauseOnFail: {},
    retryFailedStep: {
      enabled: true,
    },
    tryTo: {
      enabled: true,
    },
    screenshotOnFail: {
      enabled: true,
    },
  },
}

```

I googled this error and it seems to happen when multiple files have the same same, however in my case I don't have any other file than `steps.d.ts` in my `test` directory.

**Comment by DavertMik** [comment]
Sorry, cant help with this one.
