### ISSUE TITLE
Could not load helper Playwright from module './helper/Playwright'

### ISSUE THREAD

**Issue by skumar070** [codeceptjs/CodeceptJS#3167]
#### What are you trying to achieve?
Run just a test script using codeceptjs run command

#### What do you get instead?
Could not load helper Playwright from module './helper/Playwright':
Required modules are not installed.

RUN: [sudo] npm install -g playwright@^1
Error: Required modules are not installed.

RUN: [sudo] npm install -g playwright@^1
    at createHelpers (Users\AppData\Roaming\npm\node_modules\codeceptjs\lib\container.js:177:17)
    at Function.create (Users\AppData\Roaming\npm\node_modules\codeceptjs\lib\container.js:43:25)
    at Codecept.init (Users\AppData\Roaming\npm\node_modules\codeceptjs\lib\codecept.js:56:15)
    at module.exports (Users\AppData\Roaming\npm\node_modules\codeceptjs\lib\command\run.js:24:14)
    at Command.<anonymous> (Users\AppData\Roaming\npm\node_modules\codeceptjs\bin\codecept.js:9:11)
    at Command.listener (Users\AppData\Roaming\npm\node_modules\codeceptjs\node_modules\commander\index.js:315:8)
    at Command.emit (events.js:315:20)
    at Command.parseArgs (Users\AppData\Roaming\npm\node_modules\codeceptjs\node_modules\commander\index.js:651:12)
    at Command.parse (Users\AppData\Roaming\npm\node_modules\codeceptjs\node_modules\commander\index.js:474:21)
    at Object.<anonymous> (Users\AppData\Roaming\npm\node_modules\codeceptjs\bin\codecept.js:202:9)

### Details

* CodeceptJS version: 3.0.7
* NodeJS Version: 14.15.0
* Operating System: Windows
* Playwright: 1.17.1
* Configuration file:

```js
# paste config here
Playwright: {
      url: HOST_URL,
      show: false,
      restart: true,
      keepCookies: true,
      fullPageScreenshots: true,
      windowSize: "1500 x 800",
      "chromium": {
        "args": ["--no-sandbox"],
      },
      args: '--start-fullscreen',
      browser: 'chromium',
      waitForNavigation: "domcontentloaded",
    },

**Comment by kobenguyent** [comment]
Closed for now! Feel free to reopen if you still encounter the issue with latest version and would be nice to provide a sample code to reproduce the issue.
