### ISSUE TITLE
Puppeteer always gives warnings that popups exist

### ISSUE THREAD

**Issue by adampbutler** [codeceptjs/CodeceptJS#3177]
#### What are you trying to achieve?
View concise test output of tests with popups (eg. window.confirm)

#### What do you get instead?
Verbose output complaining about popups existing. Also in our application the unhandled promises cause tests fail but running with a new project they seem to only show a warning - still doing an investigation into why but ideally there should be no warning either.

Please see bare-bones sample project generated from `codeceptjs init` here: https://github.com/adampbutler/codecept-popup-issue

Setting restart: true on puppeteer works but makes the tests very slow. I believe the dialog event is not getting removed between tests and the clear method is not exposed so I believe we cannot remove ourselves.

```bash
> codecept-issue@1.0.0 test C:\work\codecept-issue\codecept-app
> codeceptjs run --steps

CodeceptJS v3.2.2
Using test root "C:\work\codecept-issue\codecept-app"

popup1 --
  test something1
    I am on page "https://adampbutler.github.io/codecept-popup-issue/test_page.html"
    I see "Click Me"
  √ OK in 468ms

popup2 --
  test something2
    I am on page "https://adampbutler.github.io/codecept-popup-issue/test_page.html"
    I click "Click Me"
Popup already exists and was not closed. Popups must always be closed by calling either I.acceptPopup() or I.cancelPopup()
(node:24484) UnhandledPromiseRejectionWarning: Error: Cannot accept dialog which is already handled!
    at assert (C:\work\codecept-issue\codecept-app\node_modules\puppeteer\lib\cjs\puppeteer\common\assert.js:26:15)
    at Dialog.accept (C:\work\codecept-issue\codecept-app\node_modules\puppeteer\lib\cjs\puppeteer\common\Dialog.js:79:32)
    at C:\work\codecept-issue\codecept-app\node_modules\codeceptjs\lib\helper\Puppeteer.js:483:25
(Use `node --trace-warnings ...` to show where the warning was created)
(node:24484) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:24484) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
    I accept popup
    I see "Click Me"
  √ OK in 446ms
```

> Provide test source code if related

```js
// the failure does not happen if the popup is opened on the first feature
Feature('popup1');
Scenario('test something1', async ({ I }) => {
  await I.amOnPage('https://adampbutler.github.io/codecept-popup-issue/test_page.html');
  await I.see('Click Me');
});
```
```js
Feature('popup2');
Scenario('test something2', async ({ I }) => {
  await I.amOnPage('https://adampbutler.github.io/codecept-popup-issue/test_page.html');
  await I.click('Click Me');
  await I.acceptPopup();
  await I.see('Click Me');
});
```

### Details

* CodeceptJS version: 3.2.2
* NodeJS Version: 14.7.3
* Operating System: Windows
* puppeteer 13.0.1
* Configuration file:

```js
const { setHeadlessWhen } = require('@codeceptjs/configure');

// turn on headless mode when running with HEADLESS=true environment variable
// export HEADLESS=true && npx codeceptjs run
setHeadlessWhen(process.env.HEADLESS);

exports.config = {
  tests: './*_test.js',
  output: './output',
  helpers: {
    Puppeteer: {
      url: 'https://adampbutler.github.io/codecept-popup-issue/test_page.html',
      show: true,
      restart: false,
      windowSize: '1200x900'
    }
  },
  include: {
    I: './steps_file.js'
  },
  bootstrap: null,
  mocha: {},
  name: 'codecept-app',
  plugins: {
    pauseOnFail: {},
    retryFailedStep: {
      enabled: true
    },
    tryTo: {
      enabled: true
    },
    screenshotOnFail: {
      enabled: true
    }
  }
}
```

**Comment by kobenguyent** [comment]
Closed for now as this doesn't happen with latest version.

```
CodeceptJS v3.5.8 #StandWithUkraine
Using test root "/Users/t/Downloads/highlight_error_sample"
Helpers: Puppeteer, PixelmatchHelper, MailSlurp
Plugins: screenshotOnFail, customLocator, tryTo, retryFailedStep, commentStep, autoLogin

My --
    [1]  Starting recording promises
    Timeouts: 
  popup
    --- STARTED "before each" hook: Before for "popup" ---
 › Cannot save user session with empty cookies from auto login's fetch method
    I am on page "https://google.com"
    › [Url] https://www.google.com/
    › [Browser:Info] 
    --- ENDED "before each" hook: Before for "popup" ---
    I am on page "https://adampbutler.github.io/codecept-popup-issue/test_page.html"
    › [Url] https://adampbutler.github.io/codecept-popup-issue/test_page.html
    › [Browser:Error] 
    I see "Click Me"
  ✔ OK in 598ms


  OK  | 1 passed   // 4s
```
