### ISSUE TITLE
uploading files through non-input HTML tag

### ISSUE THREAD

**Issue by maojunxyz** [codeceptjs/CodeceptJS#3178]
#### What are you trying to achieve?
uploading files through non-input HTML tag

Support playwright filechooser api:

https://playwright.dev/python/docs/api/class-filechooser

![image](https://user-images.githubusercontent.com/28778042/147456969-b3806615-2b21-42ea-817f-cca3335c2bd3.png)

```
    [1]  Starting recording promises
 » [Session] Starting singleton browser session
  h5上传 @h5上传
   打开网页
    I am on page "https://postimages.org/"
    » [Browser:Error] 
    » [Browser:Error] 
    I wait 3
    I attach file "//span[@id="uploadFile"]", "2.jrs"
    [1] Retrying... Attempt #2
    [1] Retrying... Attempt #3
    [1] Retrying... Attempt #4
    [1] Retrying... Attempt #5
    [1] Retrying... Attempt #6
    [1] Error | Error: elementHandle.setInputFiles: Error: Node is not an HTMLInputElement
    [1] Error | Error: elementHandle.setInputFiles: Error: Node is not an HTMLInputElement
    [1] Starting <teardown> session
    [1] <teardown> Stopping recording promises
 » <screenshotOnFail> Test failed, try to save a screenshot
 » Screenshot is saving to C:\Users\king\tests\palywright\t2\t3\output\h5上传_@h5上传.failed.png
  × FAILED in 12862ms

    [2]  Starting recording promises

-- FAILURES:

  1) uirecorder
       h5上传 @h5上传:
     elementHandle.setInputFiles: Error: Node is not an HTMLInputElement
      at Playwright.attachFile (C:\Users\king\tests\palywright\node_modules\codeceptjs\lib\helper\Playwright.js:1353:18)

  Scenario Steps:
  - I.attachFile("//span[@id="uploadFile"]", "2.jrs") at Test.<anonymous> (.\tests\Z测试目录\h5文件上传_test.js:9:7)
  FAIL  | 0 passed, 1 failed   // 14s
PS C:\Users\king\tests\palywright\t2\t3> npx codeceptjs run --verbose --grep '@h5上传'
CodeceptJS v3.1.3
```

**Comment by maojunxyz** [comment]
Solved, you can call the underlying api like:
```js
  I.usePlaywrightTo('upload file', async ({ page }) => {
    page.click('//span[contains(text(),"上传文件")]')
    page.on('filechooser', async (fileChooser) => {
      await fileChooser.setFiles('2.jrs');
    });
  });
```

refer:

https://codecept.io/helpers/Playwright/#useplaywrightto

https://playwright.dev/docs/api/class-page#page-event-file-chooser
