### ISSUE TITLE
WebdriverIO: moveCursorTo throws error

### ISSUE THREAD

**Issue by DanDeMicco** [codeceptjs/CodeceptJS#942]
#### What are you trying to achieve?
Moving cursor to an element in firefox 58.0.2 using webdriverio helper

#### What do you get instead?
Test fails due to: An unknown server-side error occurred while processing the command. (UnknownError:undefined)

> Provide console output if related. Use `--verbose` mode for more details.

```bash
# paste output here
CodeceptJS v1.1.4
Using test root "/Users/ddemicco/git/box-content-preview"

File Options --
   [1] Starting recording promises
   Emitted | suite.before ([object Object])
   [1] Queued | hook WebDriverIO._beforeSuite()
 test @test
   Emitted | test.before
   [1] Queued | hook WebDriverIO._before()
   Emitted | hook.start ([object Object])
   Emitted | step.before (I am on page "/functional-tests/file-options.html")
   [1] Queued | hook WebDriverIO._beforeStep()
   [1] Queued | amOnPage: "/functional-tests/file-options.html"
   Emitted | step.after (I am on page "/functional-tests/file-options.html")
   [1] Queued | hook WebDriverIO._afterStep()
   [1] Queued | step passed
   [1] Queued | return result
   Emitted | step.before (I wait for element ".bp-loaded")
   [1] Queued | hook WebDriverIO._beforeStep()
   [1] Queued | waitForElement: ".bp-loaded"
   Emitted | step.after (I wait for element ".bp-loaded")
   [1] Queued | hook WebDriverIO._afterStep()
   [1] Queued | step passed
   [1] Queued | return result
   Emitted | step.before (I wait for element ".bp-default-logo")
   [1] Queued | hook WebDriverIO._beforeStep()
   [1] Queued | waitForElement: ".bp-default-logo"
   Emitted | step.after (I wait for element ".bp-default-logo")
   [1] Queued | hook WebDriverIO._afterStep()
   [1] Queued | step passed
   [1] Queued | return result
   [1] Queued | fire hook.passed
   [1] Queued | finish before hook
   Emitted | step.start (I am on page "/functional-tests/file-options.html")
 • I am on page "/functional-tests/file-options.html"
   Emitted | step.passed (I am on page "/functional-tests/file-options.html")
   Step finished in 1.077 sec
   Emitted | step.start (I wait for element ".bp-loaded")
 • I wait for element ".bp-loaded"
   Emitted | step.passed (I wait for element ".bp-loaded")
   Step finished in 1.118 sec
   Emitted | step.start (I wait for element ".bp-default-logo")
 • I wait for element ".bp-default-logo"
   Emitted | step.passed (I wait for element ".bp-default-logo")
   Step finished in 0.02 sec
   Emitted | hook.passed ([object Object])
   Emitted | test.start ([object Object])
   Emitted | step.before (I move cursor to ".bp-default-logo")
   [1] Queued | hook WebDriverIO._beforeStep()
   [1] Queued | moveCursorTo: ".bp-default-logo"
   Emitted | step.after (I move cursor to ".bp-default-logo")
   [1] Queued | hook WebDriverIO._afterStep()
   [1] Queued | step passed
   [1] Queued | return result
   [1] Queued | fire test.passed
   [1] Queued | finish test
   Emitted | step.start (I move cursor to ".bp-default-logo")
 • I move cursor to ".bp-default-logo"
 > [SmartWait (90000ms)] Locating .bp-default-logo in 90000
   [1] Error | Error: An unknown server-side error occurred while processing the command. (UnknownError:undefined)
   Emitted | step.failed (I move cursor to ".bp-default-logo")
   Step finished in 0.075 sec
   [1] Error | Error: An unknown server-side error occurred while processing the command. (UnknownError:undefined)
   [1] Starting <teardown> session
   Emitted | test.failed ([object Object])
   [1] <teardown> Queued | hook WebDriverIO._failed()
   [1] <teardown> Queued | () => done(err)
   [1] <teardown> Stopping recording promises
 > Screenshot has been saved to /Users/ddemicco/git/box-content-preview/functional-tests/output/test_@test.failed.png
 ✖ FAILED in 421ms

   [2] Starting recording promises
   Emitted | test.after
   [2] Queued | hook WebDriverIO._after()
   Emitted | suite.after ([object Object])
   [2] Queued | hook WebDriverIO._afterSuite()

-- FAILURES:

  1) File Options
       test @test:
     An unknown server-side error occurred while processing the command. (UnknownError:undefined)
  
  Scenario Steps:
  
  - I.moveCursorTo(".bp-default-logo") at Test.Scenario (functional-tests/fileOptions_test.js:20:7)
  
  Error: An unknown server-side error occurred while processing the command. (UnknownError:undefined)
      at new RuntimeError (node_modules/webdriverio/build/lib/utils/ErrorHandler.js:144:12)
      at Request._callback (node_modules/webdriverio/build/lib/utils/RequestHandler.js:313:39)
      at Request.self.callback (node_modules/request/request.js:186:22)
      at Request.<anonymous> (node_modules/request/request.js:1163:10)
      at IncomingMessage.<anonymous> (node_modules/request/request.js:1085:12)


  FAIL  | 0 passed, 1 failed   // 5s
   Emitted | global.result ([object Object])
   [2] Queued | hook WebDriverIO._finishTest()
```

> Provide test source code if related

```js
// paste test
Scenario("test @test", (I) => {
    I.moveCursorTo('.bp-default-logo'); // move focus to make nav dissappear
})
```

### Details

* CodeceptJS version: v1.1.4
* NodeJS Version: v8.9.4
* Operating System: osx 10.12.6
* Protractor || WebDriverIO || Nightmare version (if related): webdriverIO 4.10.2
* Configuration file:

```js
# paste suite config here
{
  "tests": "./functional-tests/*_test.js",
  "timeout": 10000,
  "output": "./output",
  "helpers": {
    "WebDriverIO": {
      "url": "http://localhost:8000",
      "browser": "firefox"
    }
  },
  "include": {},
  "bootstrap": false,
  "mocha": {},
  "name": "box-content-preview"
}

```

**Comment by DanDeMicco** [comment]
I am guessing this is a selenium error, but hoping for some work arounds

**Comment by reubenmiller** [comment]
Yeah I have a feeling that it is a gecko issue. Have a look [here](https://github.com/nightwatchjs/nightwatch/issues/1664)

The WebDriverIO helper uses `moveTo` at the moment, and that api is marked as deprecated, though I'm not yet 100% sure what is replacing it. I'll have a dig around.

**Comment by DanDeMicco** [comment]
Thanks for the quick response @reubenmiller! Is there any workarounds you can think of in the meantime to simulate mouse movement?

**Comment by reubenmiller** [comment]
You can always switch browser. It seems to be fine in chrome. Or you can use the Puppeteer helper (again only chrome).

**Comment by reubenmiller** [comment]
It looks like webdriverio is migrating some of the api like `moveTo`, `rightClick` to something called [actions](http://webdriver.io/api/protocol/actions.html). I haven't tried it out yet but hopefully it works in firefox, chrome and safari...

**Comment by DanDeMicco** [comment]
Hmm, ok well thats unfortunate that its broken, hopefully it gets fixed soon.

I found a workaround for my problem. I just needed to trigger a mousemove event, so I used I.executeScript to trigger one manually

**Comment by icedream** [comment]
Just looked into it, the implementation of code that moves the cursor around would indeed need to be rewritten to make use of the already mentioned [Actions API](http://webdriver.io/api/protocol/actions.html). As [it is part of the standard](https://www.w3.org/TR/webdriver/#actions), I would expect this to work with other browsers as well as long as it's implemented properly there as well.
