### ISSUE TITLE
singleElementSelector 'idea', locator.substr is not a function & invalid selector 

### ISSUE THREAD

**Issue by xhoi12** [codeceptjs/CodeceptJS#990]
HI all, 
I usually use CSS classes to locate  e.g. `element`, and write my step as in `I.click('.element')` and then pageObjectify it in a separate file (let's say the file is called `pageObjects`) like this e.g.
`grid: ".element"` in order to have something like this: `I.click(pageObject.grid)`. 

Now, the output of your step on your terminal will be `I.click('.element')` even if you are using a page object. Also, let's say the class `element` is used multiple times on the page, you'll get an annoying warning. A workaround for the warning is to pass the element in your `pageObject` file from
`grid: 'element` to `grid: { js: () => document.querySelector(".element")}` this allows to bypass the annoying warning. You can write it like this
```
` grid: {
js: () => document.querySelector(".element"),
toJSON: () => "All Projects page"
}
````
The `toJSON` allows the terminal input to say `All projects page` instead of `.element`. Now, with interactions (clicks, fillfields etc) I get the error below, it's fine for wait (e.g. waitforelement, waitForVisible) etx
`.substring error: "is not a function"`

**BUT** we cam bodge this by implementing `substring` as a function, just like `toJSON`
but it would be cleaner to write a reusable helper for this

```
const singleElementSelector = (selector, name) => {
return {
js: () => document.querySelector(selector),
toJSON: () => name,
substring: (...args) => selector.substring(...args)
};
};
module.exports = singleElementSelector
```
which you would then use like:

```
const singleElementSelector = require('./singleElement');

const pageObject = {
grid: singleElementSelector('.element', All projects page')
}
```
However, I keep getting the error ``locator.substr is not a function` ` hence U tried to pass a fake string: 
```
const singleElementSelector = (selector, name) => {
  const fakeString = new String(selector)
  fakeString.js = () => document.querySelector(selector),
  fakeString.toJSON = () => name
  return fakeString
};
```
However CodeceptJS doesn't seem to like it and I get the` invalid selector ` error

### Details

* CodeceptJS version: CodeceptJS v1.1.1
* NodeJS Version: 8.9.4
* Operating System: ubuntu 16.04LTS
* Protractor 
* Configuration file:

**Comment by xhoi12** [comment]
```
^C⏎
 ~/md1> yarn codeceptjs run -g "@ele11" --debug
yarn run v1.5.1
$ /home/xhoi/md1/node_modules/.bin/codeceptjs run -g @ele11 --debug
CodeceptJS v1.1.1
Using test root "/home/xhoi/md1"

(node:16078) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
RT-projectScreen @E2E --
 > [Session] Starting singleton browser session
 Single element scenario @ele11
 • I resize window 1600, 1100 ("0.112 sec")
 • I am outside angular app  ("0 sec")
 • I.say("I'm logging in to localhost 💪")
 • I am on page "/"
 > Visited http://localhost:8081/
 ("0.391 sec")
 • I fill field ".email-text-field input", "/" ("0.283 sec")
 • I fill field ".password-text-field input", "/" ("0.246 sec")
 • I click "LOGIN" ("0.075 sec")
 • I wait for authentication  ("0.153 sec")
 •I.say("I'm waiting for the page to render 🍮");
 • I wait for visible ".full-page", 10 ("4.738 sec")
 • I am on page "http://localhost:8081/#/resources/dashboard"
 > Visited http://localhost:8081/#/resources/dashboard
 ("0.519 sec")
 • I wait for visible ".ra-navigation", 5 ("0.185 sec")
 • I wait for visible "All Projects page", 35 ("25.432 sec")
 • I click "Create Project" ("0.048 sec")
 > Screenshot has been saved to /home/xhoi/md1/test-xhoi/output/Single_element_scenario_@ele11.failed.png
 ✖ FAILED in 26205ms


-- FAILURES:

  1) RT-projectScreen @E2E
       Single element scenario @ele11:
     locator.substr is not a function
  
  Scenario Steps:
  
  - I.click("Create Project") at Test.I (test-xhoi/RT-projectScreen_test.js:311:7)
  - I.waitForVisible("All Projects page", 35) at Test.I (test-xhoi/RT-projectScreen_test.js:310:7)
  
  
  
  Run with --verbose flag to see NodeJS stacktrace


  FAIL  | 0 passed, 1 failed   // 34s
error An unexpected error occurred: "Command failed.
Exit code: 1
Command: sh
Arguments: -c /home/xhoi/md1/node_modules/.bin/codeceptjs run -g @ele11 --debug
Directory: /home/xhoi/md1
Output:
".
info If you think this is a bug, please open a bug report with the information provided in "/home/xhoi/md1/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
